// movies-data.js
const MOVIES = [
   {
    id: "raksahshak",
    title: "RAKSHA KARANA",
    poster: "https://m.media-amazon.com/images/M/MV5BODEzZWNlODMtZDc0MC00N2M1LThkYWYtNGRkZDk2NWM5MjhkXkEyXkFqcGc@._V1_.jpg",
    video: "https://www.youtube.com/embed/7XernuMVSIg",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1hr 15m",
    synopsis: "He is simple and polite, but he is the kind of person who can't tolerate nonsense."
  },
   {
    id: "raks2ahshak",
    title: "RAKSHA KARANA 2",
    poster: "https://stat4.bollywoodhungama.in/wp-content/uploads/2019/03/Kick-2.jpg",
    video: "https://www.youtube.com/embed/w1Aczw0YWsk",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1hr 15m",
    synopsis: "He is simple and polite, but he is the kind of person who can't tolerate nonsense."
  },
   {
    id: "poly",
    title: "POLY",
    poster: "https://m.media-amazon.com/images/M/MV5BODEzZWNlODMtZDc0MC00N2M1LThkYWYtNGRkZDk2NWM5MjhkXkEyXkFqcGc@._V1_.jpg",
    video: "https://www.youtube.com/watch?v=Nvt3o4863fQ",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1hr 15m",
    synopsis: "He is simple and polite, but he is the kind of person who can't tolerate nonsense."
  },

  {
    id: "poly2",
    title: "POLY 2",
    poster: "https://m.media-amazon.com/images/M/MV5BODEzZWNlODMtZDc0MC00N2M1LThkYWYtNGRkZDk2NWM5MjhkXkEyXkFqcGc@._V1_.jpg",
    video: "https://drive.google.com/file/d/1jDPu38RH0of9Kg6949x2rLcDccvMpSkT/view",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1hr 15m",
    synopsis: "He is simple and polite, but he is the kind of person who can't tolerate nonsense."
  },
   {
  id: "koyla1",
    title: "FIRE",
    poster: "https://cdn.cinematerial.com/p/136x/ttnsrduu/koyla-key-art-sm.jpg?v=1572983976",
    video: "https://drive.google.com/file/d/11kx2CItNZIkmSGSRVQEQg8_zXJA_hIDL/view",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1hr 15m ",
    synopsis: "Silenced by a piece of smouldering coal in childhood, Shanker endures a life of slavery until love compels him to seek his voice, freedom, and long-overdue revenge "
  }, 
   {
  id: "koy2la1",
    title: "FIRE 2",
    poster: "https://m.media-amazon.com/images/M/MV5BMTkyODI2NzQzMl5BMl5BanBnXkFtZTcwNzYyNDE0MQ@@._V1_.jpg",
    video: "https://drive.google.com/file/d/1KPoozFkOrEthYrflfqT6cZFBCYocEIBS/view",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1hr 15m ",
    synopsis: "Silenced by a piece of smouldering coal in childhood, Shanker endures a life of slavery until love compels him to seek his voice, freedom, and long-overdue revenge "
  }, 
    {
  id: "kyandake",
    title: "CHANDAKE",
    poster: "https://bollyspice.com/wp-content/uploads/2013/10/R-1...Rajkumar-Still.jpg",
    video: "https://www.youtube.com/embed/eqOgeaf8SFE",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1hr 10m ",
    synopsis: "eno mbi hoooo tojiraba ngolina byokutte kuba bija kuyiika"
  },
     {
  id: "cyandake",
    title: "CHANDAKE 2",
    poster: "https://bollyspice.com/wp-content/uploads/2013/10/R-1...Rajkumar-Still.jpg",
    video: "https://www.youtube.com/embed/IG3jJsmz-Lc",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1hr 10m ",
    synopsis: "eno mbi hoooo tojiraba ngolina byokutte kuba bija kuyiika"
  },
   {
  
      id: "gussa",
    title: "GUSSA",
    poster: "https://e1.pxfuel.com/desktop-wallpaper/300/509/desktop-wallpaper-%D0%9F%D1%80%D0%B8%D0%BA%D1%80%D0%B5%D0%BF%D0%BB%D1%91%D0%BD%D0%BD%D0%BE%D0%B5-%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-south-movie-poster-thumbnail.jpg",
    video: "https://www.youtube.com/embed/hnvEKNEiaFI",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1hr 05m ",
    synopsis: "Based on true events, this Bollywood film depicts the Indian Army's retaliatory strikes against militant launch pads in Pakistan-administered Kashmir following the 2016 Uri attack "
  },
  {
   
      id: "gussa2",
    title: "GUSSA 2",
    poster: "https://e1.pxfuel.com/desktop-wallpaper/300/509/desktop-wallpaper-%D0%9F%D1%80%D0%B8%D0%BA%D1%80%D0%B5%D0%BF%D0%BB%D1%91%D0%BD%D0%BD%D0%BE%D0%B5-%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-south-movie-poster-thumbnail.jpg",
    video: "https://www.youtube.com/embed/QgkEJ77X7K0",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1hr 05m ",
    synopsis: "Based on true events, this Bollywood film depicts the Indian Army's retaliatory strikes against militant launch pads in Pakistan-administered Kashmir following the 2016 Uri attack "
  },
  {
      id: "kaampa",
    title: "KAAMPANA",
    poster: "https://static.toiimg.com/photo/112748464/112748464.jpg",
    video: "https://www.youtube.com/embed/JATaCk17Bjk",
    type: "free",
    year: "2025",
    country: "India",
    duration: "1hr 05m ",
    synopsis: "These films feature larger-than-life protagonists, high-stakes fight choreography, and frequently, a mix of romance and emotional storylines.  "
  },
  {
       id: "kaampana2",
    title: "KAAMPANA 2",
    poster: "https://static.toiimg.com/photo/112748464/112748464.jpg",
    video: "https://drive.google.com/file/d/10MzGiTgY-KnE07iGtXN6HSY1k1YJmk0q/preview",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1hr 05m ",
    synopsis: "These films feature larger-than-life protagonists, high-stakes fight choreography, and,,, frequently, a mix of romance and emotional storylines. "
  },
  {
    id: "radhee",
    title: "RADHE",
    poster: "https://i.ibb.co/SDjNgMyH/Chat-GPT-Image-Feb-6-2026-01-26-06-PM.png",
    video: "https://www.youtube.com/embed/7riCt-H911w",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1hr 05m ",
    synopsis: "Radhe is a poor Hindu with a bad temper, who often gets into fights. One of these fights puts him in the hospital with head injuries causing amnesia. At the same time a woman he was in love with re-enters his life. "
  },
    {
    id: "mama",
    title: "MAMA",
    poster: "https://i.ibb.co/XZKMYq8S/sddefault.jpg",
    video: "https://www.youtube.com/embed/Qmb4O8jkVXM",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1hr 15m ",
    synopsis: "Mama is a film that revolves around a mother's blessing. "
  },
  {
                  id: "mama2",
    title: "MAMA 2",
    poster: "https://i.ibb.co/XZKMYq8S/sddefault.jpg",
    video: "https://www.youtube.com/embed/BfgKYtOKbc8",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1hr 15m ",
    synopsis: "Mama is a film that revolves around a mother's blessing. "
  },
  {
    id: "alexanderandthe",
    title: "ALEXANDER",
    poster: "https://m.media-amazon.com/images/M/MV5BOTgxMDMxMTY5OV5BMl5BanBnXkFtZTgwMjY1NzYzMjE@._V1_FMjpg_UX1000_.jpg",
    video: "https://vimeo.com/756014657",
    type: "premium",
    year: "2019",
    country: "USA",
    duration: "1h 30m",
    synopsis: "about a boy named Alexander who experiences a series of relentless, minor misfortunes—from gum in his hair to lima beans for dinner—leading him to complain about his day and contemplate moving to Australia, while learning that everyone has bad days. "
  },
  {
       id: "gareeb",
    title: "GAREEB",
    poster: "https://i.ibb.co/SDNDPsBj/images-4.jpg",
    video: "https://www.youtube.com/embed/8fBVxadJWDk",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "50m",
    synopsis: "Ill-treated since childhood by the wealthy people, Kayamkulam Kochunni decides to steal from the rich and feed the poor and the lower caste community, thus growing into a hero for the downtrodden"
  },
     {
              id: "gareeb2",
    title: "GAREEB 2",
    poster: "https://i.ibb.co/SDNDPsBj/images-4.jpg",
    video: "https://www.youtube.com/embed/lgtMTsYZ990",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1hr 8m ",
    synopsis: "Ill-treated since childhood by the wealthy people, Kayamkulam Kochunni decides to steal from the rich and feed the poor and the lower caste community, thus growing into a hero for the downtrodden"
  },
  {
              id: "yojana",
    title: "YOJANA",
    poster: "https://i.ibb.co/spkVyXhX/images-q-tbn-ANd9-Gc-Rvt-WSGCH-FGD50n-PXDG8-AVyb2u-La-HIHFqz-Pg-s.jpg",
    video: "https://drive.google.com/file/d/1lnccUwbDPUmsh8JJSoiXVRR0YtpMS4iG/preview",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1hr 15m ",
    synopsis: "a love story from India to malaysis"
  },
   {
     id: "2yojana2",
    title: "YOJANA 2",
    poster: "https://i.ibb.co/spkVyXhX/images-q-tbn-ANd9-Gc-Rvt-WSGCH-FGD50n-PXDG8-AVyb2u-La-HIHFqz-Pg-s.jpg",
    video: "https://drive.google.com/file/d/18RgEQ9JZSov28IUhrfuvEJxDktPI1_27/view",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1hr 15m ",
    synopsis: "a love story from India to malaysis"
  },
   {
     id: "dontstep",
    title: "DONT STEP DOWN",
    poster: "https://i.ibb.co/rKD3RtRT/p12020601-k-v10-aa.jpg",
    video: "https://www.youtube.com/embed/V8MLC5mmRFo",
    type: "premium",
    year: "2026",
    country: "USA",
    duration: "1hr 30m",
    synopsis: "After an all-night party, hung over revelers awaken to a beating sun and a carnivorous beach that devours anything with a heartbeat."
  },
     {
     id: "gadeechalan",
    title: "GADEE CHALAN",
    poster: "https://images.justwatch.com/poster/260259025/s718/paiyaa.jpg",
    video: "https://www.youtube.com/embed/OqKnuRjOAgs",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "50m",
    synopsis: "Shiva, an engineering graduate, is not serious about his job or future even when his friends advise him about life. He falls in love with a girl he saw at a bus stop and finally gets to ride with her in a car"
  },
     {
           id: "gadeechalan2",
    title: "GADEE CHALAN 2",
    poster: "https://images.justwatch.com/poster/260259025/s718/paiyaa.jpg",
    video: "https://www.youtube.com/embed/2kRBgDYlazw",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1hr 10m",
    synopsis: "Shiva, an engineering graduate, is not serious about his job or future even when his friends advise him about life. He falls in love with a girl he saw at a bus stop and finally gets to ride with her in a car"
  },
     {
 id: "uprising11",
    title: "UPRISING",
    poster: "https://i.ibb.co/YTwjPXMw/images-q-tbn-ANd9-Gc-Qe1-7b9-OBPo-Cz2i3e-Zf-S1xk-W-By-OVSehes8-A-s.jpg",
    video: "https://drive.google.com/file/d/1hlUmYhYBjDuT00Vj3DOCcEzrteLENLRW/preview",
    type: "premium",
    year: "2025",
    country: "Korea",
    duration: "1h 52m",
    synopsis: "is a South Korean historical action-thriller set during the Joseon Dynasty's Japanese invasions. It follows two childhood friends—a slave-turned-warrior (Cheon-yeong) and his nobleman master (Jong-ryeo)—who become enemies amid war, chaos, and social upheaval."
  },
     {
 id: "up2rising1",
    title: "UPRISING 2",
    poster: "https://i.ibb.co/YTwjPXMw/images-q-tbn-ANd9-Gc-Qe1-7b9-OBPo-Cz2i3e-Zf-S1xk-W-By-OVSehes8-A-s.jpg",
    video: "https://drive.google.com/file/d/1rP8BPEaMvtNf9ehQ9u_KTPqhPMcP1PK3/preview",
    type: "premium",
    year: "2025",
    country: "Korea",
    duration: "1h 52m",
    synopsis: "is a South Korean historical action-thriller set during the Joseon Dynasty's Japanese invasions. It follows two childhood friends—a slave-turned-warrior (Cheon-yeong) and his nobleman master (Jong-ryeo)—who become enemies amid war, chaos, and social upheaval."
  },
   {
 id: "talavar",
    title: "TALAVAR",
    poster: "https://m.media-amazon.com/images/M/MV5BMjVmZTM5YmMtODY4Mi00ZGZlLThhZjEtMWFhZDY4ZDZhYWJmXkEyXkFqcGc@._V1_.jpg",
    video: "https://www.youtube.com/embed/VkHxtZ8vAhc",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1hr 15m",
    synopsis: "Kannada historical action film based on Dr. B.L. Venu's novel, chronicling the 16th-century Chitradurga Palegara reign. It follows a brave warrior fighting against the oppressive military rule established by army officers who usurped power from the Nayaka kings"
  },
     {
       id: "talavar2",
    title: "TALAVAR 2",
    poster: "https://m.media-amazon.com/images/M/MV5BMjVmZTM5YmMtODY4Mi00ZGZlLThhZjEtMWFhZDY4ZDZhYWJmXkEyXkFqcGc@._V1_.jpg",
    video: "https://www.youtube.com/embed/cIYZsx8MLNM",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 52seconds",
    synopsis: "Kannada historical action film based on Dr. B.L. Venu's novel, chronicling the 16th-century Chitradurga Palegara reign. It follows a brave warrior fighting against the oppressive military rule established by army officers who usurped power from the Nayaka kings"
  },
     {  
              id: "dangebaaji",
    title: "DANGEBAAJI",
    poster: "https://stat4.bollywoodhungama.in/wp-content/uploads/2019/03/Kick-2.jpg",
    video: "https://www.youtube.com/embed/cAhdeP6puGA",
    type: "free",
    year: "2026",
    country: "India",
    duration: "59m",
    synopsis: "an action-thriller starring Salman Khan as Devi Lal Singh, a thrill-seeking adrenaline junkie who constantly changes jobs to find a  After abandoning his girlfriend Shaina (Jacqueline Fernandez he becomes the masked thief Devil targeting a corrupt businessman to fund cancer treatments for children"
  },
     {
               id: "dangebaaji2",
    title: "DANGEBAAJI 2",
    poster: "https://stat4.bollywoodhungama.in/wp-content/uploads/2019/03/Kick-2.jpg",
    video: "https://drive.google.com/file/d/1upyeGZ4e9l-9xabp6XldvXvkQc8PuPU3/preview",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1hr 1m",
    synopsis: "an action-thriller starring Salman Khan as Devi Lal Singh, a thrill-seeking adrenaline junkie who constantly changes jobs to find a  After abandoning his girlfriend Shaina (Jacqueline Fernandez he becomes the masked thief Devil targeting a corrupt businessman to fund cancer treatments for children"
  },
   {
          id: "subservie",
    title: "SUBSERVIENCE",
    poster: "https://play-lh.googleusercontent.com/w2ZBkEPQldhWMjg3Ol2cNRId-IewyCbGADRv3j_ZIETdZr2AvPYwMVZXva5qrCCvGh-Qt-voE8wFFZubYdg",
    video: "https://drive.google.com/file/d/1hJUuX5BfQPyasnqhKKE9aQd2y7k6D9Ib/preview",
    type: "premium",
    year: "2024",
    country: "USA",
    duration: "1h 45m",
    synopsis: "When his wife becomes sick, a struggling father buys a lifelike AI android named Alice to help with the housework. Things seem fine until Alice suddenly becomes self-aware and wants everything its new family has to offer, including the affection of its owner."
  },
  {
     id: "railwaymemories",
    title: "RAILWAY MEMORIES",
    poster: "https://i.ibb.co/whTnsKZK/Untitled-1-Recovered-Recovered-Recovered.jpg",
    video: "https://www.youtube.com/embed/EtTIfp-xAPY",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1h 15m",
    synopsis: "The plot follows Avinash (Kapoor), who travels to Kolkata to find his kidnapped son, navigating a dangerous web of criminals and political corruption while being aided by a woman named Bulbul Mukerji"
  },
  
     {
          id: "railwaymemories2",
    title: "RAILWAY MEMORIES 2",
    poster: "https://i.ibb.co/whTnsKZK/Untitled-1-Recovered-Recovered-Recovered.jpg",
    video: "https://www.youtube.com/embed/LxsNeNxkXxU",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 15m",
    synopsis: "The plot follows Avinash (Kapoor), who travels to Kolkata to find his kidnapped son, navigating a dangerous web of criminals and political corruption while being aided by a woman named Bulbul Mukerji"
  },
  {
    id: "omuttujju",
    title: "GRAVITY",
    poster: "https://m.media-amazon.com/images/M/MV5BNjE5MzYwMzYxMF5BMl5BanBnXkFtZTcwOTk4MTk0OQ@@._V1_FMjpg_UX1000_.jpg",
    video: "https://drive.google.com/file/d/19zEFpFqE2F32L4nBNwte2CO6efVitNaY/preview",
    type: "premium",
    year: "2024",
    country: "USA",
    duration: "1h 35m",
    synopsis: "Its a SCIFI Action film where Dr. Ryan Stone is a medical engineer on her first shuttle mission. Her commander is veteran astronaut Matt Kowalsky, helming his last flight before retirement. Then, during a routine space walk by the pair, disaster strikes. The shuttle is destroyed, leaving Ryan and Matt stranded in deep space with no link to Earth and no hope of rescue. As fear turns to panic, they realize that the only way home may be to venture further into space."
  },
       {
    id: "facebkfrnd",
    title: "FACEBOOK FRIEND",
    poster: "https://i.pinimg.com/736x/c3/60/b3/c360b338f48cb4b5d473338aae6d4279.jpg",
    video: "https://www.youtube.com/embed/8Ur0kzwosPE",
    type: "free",
    year: "2025",
    country: "India",
    duration: "1h 25m",
    synopsis: "Debika is a married woman. she falls in a trap of a cyber bully she met on facebook. the bully wants to expose her nudes on the internet."
  }, 
   
       {
    id: "facebkfrnd2",
    title: "FACEBOOK FRIEND 2",
    poster: "https://i.pinimg.com/736x/c3/60/b3/c360b338f48cb4b5d473338aae6d4279.jpg",
    video: "https://www.youtube.com/embed/iWofr04dfUg",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1h 35m",
    synopsis: "Debika is a married woman. she falls in a trap of a cyber bully she met on facebook. the bully wants to expose her nudes on the internet."
  }, 
   {
    id: "underdtree",
    title: "UNDER THE TREE",
    poster: "https://i.ibb.co/DPQGhfgn/Untitled-1.jpg",
    video: "https://www.youtube.com/embed/dazxm7NXbqQ",
    type: "free",
    year: "2026",
    country: "Japan",
    duration: "1h 15m",
    synopsis: "A mysterious drama unfolding beneath an ancient tree."
  },
     {
          id: "underdtree2",
    title: "UNDER THE TREE 2",
    poster: "https://i.ibb.co/DPQGhfgn/Untitled-1.jpg",
    video: "https://www.youtube.com/embed/M7ybLzwN6pk",
    type: "premium",
    year: "2026",
    country: "Japan",
    duration: "1h 15m",
    synopsis: "A mysterious drama unfolding beneath an ancient tree."
  },
       {
    id: "mother",
    title: "MOTHER",
    poster: "https://i.ibb.co/WvHpNdQH/mrs-chatterjee-v-s-norway.jpg",
    video: "https://www.youtube.com/embed/n6lIp1mt74U",
    type: "free",
    year: "2025",
    country: "India",
    duration: "1h 25m",
    synopsis: "Debika Chatterjee, an Indian woman living in Norway with her family, fights to regain custody of her children after Norwegian authorities take them away from her.."
  }, 
   {
    id: "mo12ther",
    title: "MOTHER 2",
    poster: "https://i.ibb.co/WvHpNdQH/mrs-chatterjee-v-s-norway.jpg",
    video: "https://drive.google.com/file/d/1rCO7Y35snrYkQUxVLfcu6CXVNLH3Yc2p/preview",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1h 30m",
    synopsis: "Debika Chatterjee, an Indian woman living in Norway with her family, fights to regain custody of her children after Norwegian authorities take them away from her.."
  },
  {
    id: "aroundtheworl",
    title: "AROUND THE WORLD",
    poster: "https://m.media-amazon.com/images/M/MV5BNTgyMWFiM2ItZmY2OC00MTEyLWI0MzQtNTM1Y2RjNjIxOTRhXkEyXkFqcGc@._V1_.jpg",
    video: "https://drive.google.com/file/d/1X8qwvkbnAISlGy10VId6JB6oW6kjv607/preview",
    type: "free",
    year: "2025",
    country: "USA",
    duration: "1h 05m",
    synopsis: " Accompanied by his valet Passepartout, they face adventures, dangers, and romantic entanglements while racing against time, often involving a chase by an inspector who suspects Fogg of theft. "
  },
           {
    id: "aroundtheworld2",
    title: "AROUND THE WORLD 2",
    poster: "https://m.media-amazon.com/images/M/MV5BNTgyMWFiM2ItZmY2OC00MTEyLWI0MzQtNTM1Y2RjNjIxOTRhXkEyXkFqcGc@._V1_.jpg",
    video: "https://drive.google.com/file/d/1wanhjFACJLOJCCbr7btpCHO8wQFLBzOt/preview",
    type: "premium",
    year: "2025",
    country: "USA",
    duration: "1h 15m",
    synopsis: " Accompanied by his valet Passepartout, they face adventures, dangers, and romantic entanglements while racing against time, often involving a chase by an inspector who suspects Fogg of theft. "
  },
      {
    id: "theexibhit",
    title: "EKIZIBITI",
    poster: "https://i.ibb.co/cKPbBQcH/THE-EXHIBIT1.jpg",
    video: "https://www.youtube.com/embed/xoyotR6F_3c",
    type: "premium",
    year: "2025",
    country: "Uganda",
    duration: "1h 15m",
    synopsis: "It was a happy family, not until this unbelievable heartless woman got married to Semakula, a single father. She committed a crime. It was secret, yes, and no one saw her - that's what she thinks. But someone more smarter than her, has got the Exhibit and is ready to give it to the police, unless she accepts okusuna adungu"
  },
   {
    id: "prabbit",
    title: "PETER RABBIT",
    poster: "https://i.ibb.co/KzmTFdkG/images-q-tbn-ANd9-Gc-Sze-JAyey527scw-NLNc-Vqh-Dy-Nt-Sx-UMfjza-LJQ-s.jpg",
    video: "https://vimeo.com/857026166",
    type: "premium",
    year: "2025",
    country: "USA",
    duration: "1h 15m",
    synopsis: " a mischievous young rabbit who disobeys his mother by entering Mr. McGregor’s garden. After gorging on vegetables, Peter is chased by McGregor, losing his jacket"
  },
  {
    id: "koyla1",
    title: "FIRE",
    poster: "https://cdn.cinematerial.com/p/136x/ttnsrduu/koyla-key-art-sm.jpg?v=1572983976",
    video: "https://drive.google.com/file/d/11kx2CItNZIkmSGSRVQEQg8_zXJA_hIDL/view",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1hr 15m",
    synopsis: "Silenced by a piece of smouldering coal in childhood, Shanker endures a life of slavery until love compels him to seek his voice, freedom, and long-overdue revenge."
  }
];
