// movies-data.js
const MOVIES = [
   {
    id: "raksahshak",
    title: "RAKSHA KARANA",
    poster: "https://m.media-amazon.com/images/M/MV5BODEzZWNlODMtZDc0MC00N2M1LThkYWYtNGRkZDk2NWM5MjhkXkEyXkFqcGc@._V1_.jpg",
    video: "https://www.youtube.com/embed/7XernuMVSIg",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1hr 15m",
    synopsis: "He is simple and polite, but he is the kind of person who can't tolerate nonsense."
  },
   {
    id: "raks2ahshak",
    title: "RAKSHA KARANA 2",
    poster: "https://stat4.bollywoodhungama.in/wp-content/uploads/2019/03/Kick-2.jpg",
    video: "https://www.youtube.com/embed/w1Aczw0YWsk",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1hr 15m",
    synopsis: "He is simple and polite, but he is the kind of person who can't tolerate nonsense."
  },
   {
    id: "poly",
    title: "POLY",
    poster: "https://m.media-amazon.com/images/M/MV5BODEzZWNlODMtZDc0MC00N2M1LThkYWYtNGRkZDk2NWM5MjhkXkEyXkFqcGc@._V1_.jpg",
    video: "https://www.youtube.com/watch?v=Nvt3o4863fQ",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1hr 15m",
    synopsis: "He is simple and polite, but he is the kind of person who can't tolerate nonsense."
  },

  {
    id: "poly2",
    title: "POLY 2",
    poster: "https://m.media-amazon.com/images/M/MV5BODEzZWNlODMtZDc0MC00N2M1LThkYWYtNGRkZDk2NWM5MjhkXkEyXkFqcGc@._V1_.jpg",
    video: "https://drive.google.com/file/d/1jDPu38RH0of9Kg6949x2rLcDccvMpSkT/view",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1hr 15m",
    synopsis: "He is simple and polite, but he is the kind of person who can't tolerate nonsense."
  },
   {
  id: "koyla1",
    title: "FIRE",
    poster: "https://cdn.cinematerial.com/p/136x/ttnsrduu/koyla-key-art-sm.jpg?v=1572983976",
    video: "https://drive.google.com/file/d/11kx2CItNZIkmSGSRVQEQg8_zXJA_hIDL/view",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1hr 15m ",
    synopsis: "Silenced by a piece of smouldering coal in childhood, Shanker endures a life of slavery until love compels him to seek his voice, freedom, and long-overdue revenge "
  }, 
   {
  id: "koy2la1",
    title: "FIRE 2",
    poster: "https://m.media-amazon.com/images/M/MV5BMTkyODI2NzQzMl5BMl5BanBnXkFtZTcwNzYyNDE0MQ@@._V1_.jpg",
    video: "https://drive.google.com/file/d/1KPoozFkOrEthYrflfqT6cZFBCYocEIBS/view",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1hr 15m ",
    synopsis: "Silenced by a piece of smouldering coal in childhood, Shanker endures a life of slavery until love compels him to seek his voice, freedom, and long-overdue revenge "
  }, 
    {
  id: "kyandake",
    title: "CHANDAKE",
    poster: "https://bollyspice.com/wp-content/uploads/2013/10/R-1...Rajkumar-Still.jpg",
    video: "https://www.youtube.com/embed/eqOgeaf8SFE",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1hr 10m ",
    synopsis: "eno mbi hoooo tojiraba ngolina byokutte kuba bija kuyiika"
  },
     {
  id: "cyandake",
    title: "CHANDAKE 2",
    poster: "https://bollyspice.com/wp-content/uploads/2013/10/R-1...Rajkumar-Still.jpg",
    video: "https://www.youtube.com/embed/IG3jJsmz-Lc",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1hr 10m ",
    synopsis: "eno mbi hoooo tojiraba ngolina byokutte kuba bija kuyiika"
  },
   {
  
      id: "gussa",
    title: "GUSSA",
    poster: "https://e1.pxfuel.com/desktop-wallpaper/300/509/desktop-wallpaper-%D0%9F%D1%80%D0%B8%D0%BA%D1%80%D0%B5%D0%BF%D0%BB%D1%91%D0%BD%D0%BD%D0%BE%D0%B5-%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-south-movie-poster-thumbnail.jpg",
    video: "https://www.youtube.com/embed/hnvEKNEiaFI",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1hr 05m ",
    synopsis: "Based on true events, this Bollywood film depicts the Indian Army's retaliatory strikes against militant launch pads in Pakistan-administered Kashmir following the 2016 Uri attack "
  },
  {
   
      id: "gussa2",
    title: "GUSSA 2",
    poster: "https://e1.pxfuel.com/desktop-wallpaper/300/509/desktop-wallpaper-%D0%9F%D1%80%D0%B8%D0%BA%D1%80%D0%B5%D0%BF%D0%BB%D1%91%D0%BD%D0%BD%D0%BE%D0%B5-%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-south-movie-poster-thumbnail.jpg",
    video: "https://www.youtube.com/embed/QgkEJ77X7K0",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1hr 05m ",
    synopsis: "Based on true events, this Bollywood film depicts the Indian Army's retaliatory strikes against militant launch pads in Pakistan-administered Kashmir following the 2016 Uri attack "
  },
  {
      id: "kaampa",
    title: "KAAMPANA",
    poster: "https://static.toiimg.com/photo/112748464/112748464.jpg",
    video: "https://www.youtube.com/embed/JATaCk17Bjk",
    type: "free",
    year: "2025",
    country: "India",
    duration: "1hr 05m ",
    synopsis: "These films feature larger-than-life protagonists, high-stakes fight choreography, and frequently, a mix of romance and emotional storylines.  "
  },
  {
       id: "kaampana2",
    title: "KAAMPANA 2",
    poster: "https://static.toiimg.com/photo/112748464/112748464.jpg",
    video: "https://drive.google.com/file/d/10MzGiTgY-KnE07iGtXN6HSY1k1YJmk0q/preview",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1hr 05m ",
    synopsis: "These films feature larger-than-life protagonists, high-stakes fight choreography, and,,, frequently, a mix of romance and emotional storylines. "
  },
  {
    id: "radhee",
    title: "RADHE",
    poster: "https://i.ibb.co/SDjNgMyH/Chat-GPT-Image-Feb-6-2026-01-26-06-PM.png",
    video: "https://www.youtube.com/embed/7riCt-H911w",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1hr 05m ",
    synopsis: "Radhe is a poor Hindu with a bad temper, who often gets into fights. One of these fights puts him in the hospital with head injuries causing amnesia. At the same time a woman he was in love with re-enters his life. "
  },
    {
    id: "mama",
    title: "MAMA",
    poster: "https://i.ibb.co/XZKMYq8S/sddefault.jpg",
    video: "https://www.youtube.com/embed/Qmb4O8jkVXM",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1hr 15m ",
    synopsis: "Mama is a film that revolves around a mother's blessing. "
  },
  {
                  id: "mama2",
    title: "MAMA 2",
    poster: "https://i.ibb.co/XZKMYq8S/sddefault.jpg",
    video: "https://www.youtube.com/embed/BfgKYtOKbc8",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1hr 15m ",
    synopsis: "Mama is a film that revolves around a mother's blessing. "
  },
  {
    id: "alexanderandthe",
    title: "ALEXANDER",
    poster: "https://m.media-amazon.com/images/M/MV5BOTgxMDMxMTY5OV5BMl5BanBnXkFtZTgwMjY1NzYzMjE@._V1_FMjpg_UX1000_.jpg",
    video: "https://vimeo.com/756014657",
    type: "premium",
    year: "2019",
    country: "USA",
    duration: "1h 30m",
    synopsis: "about a boy named Alexander who experiences a series of relentless, minor misfortunes—from gum in his hair to lima beans for dinner—leading him to complain about his day and contemplate moving to Australia, while learning that everyone has bad days. "
  },
  {
       id: "gareeb",
    title: "GAREEB",
    poster: "https://i.ibb.co/SDNDPsBj/images-4.jpg",
    video: "https://www.youtube.com/embed/8fBVxadJWDk",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "50m",
    synopsis: "Ill-treated since childhood by the wealthy people, Kayamkulam Kochunni decides to steal from the rich and feed the poor and the lower caste community, thus growing into a hero for the downtrodden"
  },
     {
              id: "gareeb2",
    title: "GAREEB 2",
    poster: "https://i.ibb.co/SDNDPsBj/images-4.jpg",
    video: "https://www.youtube.com/embed/lgtMTsYZ990",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1hr 8m ",
    synopsis: "Ill-treated since childhood by the wealthy people, Kayamkulam Kochunni decides to steal from the rich and feed the poor and the lower caste community, thus growing into a hero for the downtrodden"
  },
  {
              id: "yojana",
    title: "YOJANA",
    poster: "https://i.ibb.co/spkVyXhX/images-q-tbn-ANd9-Gc-Rvt-WSGCH-FGD50n-PXDG8-AVyb2u-La-HIHFqz-Pg-s.jpg",
    video: "https://drive.google.com/file/d/1lnccUwbDPUmsh8JJSoiXVRR0YtpMS4iG/preview",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1hr 15m ",
    synopsis: "a love story from India to malaysis"
  },
   {
     id: "2yojana2",
    title: "YOJANA 2",
    poster: "https://i.ibb.co/spkVyXhX/images-q-tbn-ANd9-Gc-Rvt-WSGCH-FGD50n-PXDG8-AVyb2u-La-HIHFqz-Pg-s.jpg",
    video: "https://drive.google.com/file/d/18RgEQ9JZSov28IUhrfuvEJxDktPI1_27/view",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1hr 15m ",
    synopsis: "a love story from India to malaysis"
  },
   {
     id: "dontstep",
    title: "DONT STEP DOWN",
    poster: "https://i.ibb.co/rKD3RtRT/p12020601-k-v10-aa.jpg",
    video: "https://www.youtube.com/embed/V8MLC5mmRFo",
    type: "premium",
    year: "2026",
    country: "USA",
    duration: "1hr 30m",
    synopsis: "After an all-night party, hung over revelers awaken to a beating sun and a carnivorous beach that devours anything with a heartbeat."
  },
     {
     id: "gadeechalan",
    title: "GADEE CHALAN",
    poster: "https://images.justwatch.com/poster/260259025/s718/paiyaa.jpg",
    video: "https://www.youtube.com/embed/OqKnuRjOAgs",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "50m",
    synopsis: "Shiva, an engineering graduate, is not serious about his job or future even when his friends advise him about life. He falls in love with a girl he saw at a bus stop and finally gets to ride with her in a car"
  },
     {
           id: "gadeechalan2",
    title: "GADEE CHALAN 2",
    poster: "https://images.justwatch.com/poster/260259025/s718/paiyaa.jpg",
    video: "https://www.youtube.com/embed/2kRBgDYlazw",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1hr 10m",
    synopsis: "Shiva, an engineering graduate, is not serious about his job or future even when his friends advise him about life. He falls in love with a girl he saw at a bus stop and finally gets to ride with her in a car"
  },
     {
 id: "uprising11",
    title: "UPRISING",
    poster: "https://i.ibb.co/YTwjPXMw/images-q-tbn-ANd9-Gc-Qe1-7b9-OBPo-Cz2i3e-Zf-S1xk-W-By-OVSehes8-A-s.jpg",
    video: "https://drive.google.com/file/d/1hlUmYhYBjDuT00Vj3DOCcEzrteLENLRW/preview",
    type: "premium",
    year: "2025",
    country: "Korea",
    duration: "1h 52m",
    synopsis: "is a South Korean historical action-thriller set during the Joseon Dynasty's Japanese invasions. It follows two childhood friends—a slave-turned-warrior (Cheon-yeong) and his nobleman master (Jong-ryeo)—who become enemies amid war, chaos, and social upheaval."
  },
     {
 id: "up2rising1",
    title: "UPRISING 2",
    poster: "https://i.ibb.co/YTwjPXMw/images-q-tbn-ANd9-Gc-Qe1-7b9-OBPo-Cz2i3e-Zf-S1xk-W-By-OVSehes8-A-s.jpg",
    video: "https://drive.google.com/file/d/1rP8BPEaMvtNf9ehQ9u_KTPqhPMcP1PK3/preview",
    type: "premium",
    year: "2025",
    country: "Korea",
    duration: "1h 52m",
    synopsis: "is a South Korean historical action-thriller set during the Joseon Dynasty's Japanese invasions. It follows two childhood friends—a slave-turned-warrior (Cheon-yeong) and his nobleman master (Jong-ryeo)—who become enemies amid war, chaos, and social upheaval."
  },
   {
 id: "talavar",
    title: "TALAVAR",
    poster: "https://m.media-amazon.com/images/M/MV5BMjVmZTM5YmMtODY4Mi00ZGZlLThhZjEtMWFhZDY4ZDZhYWJmXkEyXkFqcGc@._V1_.jpg",
    video: "https://www.youtube.com/embed/VkHxtZ8vAhc",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1hr 15m",
    synopsis: "Kannada historical action film based on Dr. B.L. Venu's novel, chronicling the 16th-century Chitradurga Palegara reign. It follows a brave warrior fighting against the oppressive military rule established by army officers who usurped power from the Nayaka kings"
  },
     {
       id: "talavar2",
    title: "TALAVAR 2",
    poster: "https://m.media-amazon.com/images/M/MV5BMjVmZTM5YmMtODY4Mi00ZGZlLThhZjEtMWFhZDY4ZDZhYWJmXkEyXkFqcGc@._V1_.jpg",
    video: "https://www.youtube.com/embed/cIYZsx8MLNM",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 52seconds",
    synopsis: "Kannada historical action film based on Dr. B.L. Venu's novel, chronicling the 16th-century Chitradurga Palegara reign. It follows a brave warrior fighting against the oppressive military rule established by army officers who usurped power from the Nayaka kings"
  },
     {  
              id: "dangebaaji",
    title: "DANGEBAAJI",
    poster: "https://stat4.bollywoodhungama.in/wp-content/uploads/2019/03/Kick-2.jpg",
    video: "https://www.youtube.com/embed/cAhdeP6puGA",
    type: "free",
    year: "2026",
    country: "India",
    duration: "59m",
    synopsis: "an action-thriller starring Salman Khan as Devi Lal Singh, a thrill-seeking adrenaline junkie who constantly changes jobs to find a  After abandoning his girlfriend Shaina (Jacqueline Fernandez he becomes the masked thief Devil targeting a corrupt businessman to fund cancer treatments for children"
  },
     {
               id: "dangebaaji2",
    title: "DANGEBAAJI 2",
    poster: "https://stat4.bollywoodhungama.in/wp-content/uploads/2019/03/Kick-2.jpg",
    video: "https://drive.google.com/file/d/1upyeGZ4e9l-9xabp6XldvXvkQc8PuPU3/preview",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1hr 1m",
    synopsis: "an action-thriller starring Salman Khan as Devi Lal Singh, a thrill-seeking adrenaline junkie who constantly changes jobs to find a  After abandoning his girlfriend Shaina (Jacqueline Fernandez he becomes the masked thief Devil targeting a corrupt businessman to fund cancer treatments for children"
  },
   {
          id: "subservie",
    title: "SUBSERVIENCE",
    poster: "https://play-lh.googleusercontent.com/w2ZBkEPQldhWMjg3Ol2cNRId-IewyCbGADRv3j_ZIETdZr2AvPYwMVZXva5qrCCvGh-Qt-voE8wFFZubYdg",
    video: "https://drive.google.com/file/d/1hJUuX5BfQPyasnqhKKE9aQd2y7k6D9Ib/preview",
    type: "premium",
    year: "2024",
    country: "USA",
    duration: "1h 45m",
    synopsis: "When his wife becomes sick, a struggling father buys a lifelike AI android named Alice to help with the housework. Things seem fine until Alice suddenly becomes self-aware and wants everything its new family has to offer, including the affection of its owner."
  },
  {
     id: "railwaymemories",
    title: "RAILWAY MEMORIES",
    poster: "https://i.ibb.co/whTnsKZK/Untitled-1-Recovered-Recovered-Recovered.jpg",
    video: "https://www.youtube.com/embed/EtTIfp-xAPY",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1h 15m",
    synopsis: "The plot follows Avinash (Kapoor), who travels to Kolkata to find his kidnapped son, navigating a dangerous web of criminals and political corruption while being aided by a woman named Bulbul Mukerji"
  },
  
     {
          id: "railwaymemories2",
    title: "RAILWAY MEMORIES 2",
    poster: "https://i.ibb.co/whTnsKZK/Untitled-1-Recovered-Recovered-Recovered.jpg",
    video: "https://www.youtube.com/embed/LxsNeNxkXxU",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 15m",
    synopsis: "The plot follows Avinash (Kapoor), who travels to Kolkata to find his kidnapped son, navigating a dangerous web of criminals and political corruption while being aided by a woman named Bulbul Mukerji"
  },
  {
    id: "omuttujju",
    title: "GRAVITY",
    poster: "https://m.media-amazon.com/images/M/MV5BNjE5MzYwMzYxMF5BMl5BanBnXkFtZTcwOTk4MTk0OQ@@._V1_FMjpg_UX1000_.jpg",
    video: "https://drive.google.com/file/d/19zEFpFqE2F32L4nBNwte2CO6efVitNaY/preview",
    type: "premium",
    year: "2024",
    country: "USA",
    duration: "1h 35m",
    synopsis: "Its a SCIFI Action film where Dr. Ryan Stone is a medical engineer on her first shuttle mission. Her commander is veteran astronaut Matt Kowalsky, helming his last flight before retirement. Then, during a routine space walk by the pair, disaster strikes. The shuttle is destroyed, leaving Ryan and Matt stranded in deep space with no link to Earth and no hope of rescue. As fear turns to panic, they realize that the only way home may be to venture further into space."
  },
       {
    id: "facebkfrnd",
    title: "FACEBOOK FRIEND",
    poster: "https://i.pinimg.com/736x/c3/60/b3/c360b338f48cb4b5d473338aae6d4279.jpg",
    video: "https://www.youtube.com/embed/8Ur0kzwosPE",
    type: "free",
    year: "2025",
    country: "India",
    duration: "1h 25m",
    synopsis: "Debika is a married woman. she falls in a trap of a cyber bully she met on facebook. the bully wants to expose her nudes on the internet."
  }, 
   
       {
    id: "facebkfrnd2",
    title: "FACEBOOK FRIEND 2",
    poster: "https://i.pinimg.com/736x/c3/60/b3/c360b338f48cb4b5d473338aae6d4279.jpg",
    video: "https://www.youtube.com/embed/iWofr04dfUg",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1h 35m",
    synopsis: "Debika is a married woman. she falls in a trap of a cyber bully she met on facebook. the bully wants to expose her nudes on the internet."
  }, 
   {
    id: "underdtree",
    title: "UNDER THE TREE",
    poster: "https://i.ibb.co/DPQGhfgn/Untitled-1.jpg",
    video: "https://www.youtube.com/embed/dazxm7NXbqQ",
    type: "free",
    year: "2026",
    country: "Japan",
    duration: "1h 15m",
    synopsis: "A mysterious drama unfolding beneath an ancient tree."
  },
     {
          id: "underdtree2",
    title: "UNDER THE TREE 2",
    poster: "https://i.ibb.co/DPQGhfgn/Untitled-1.jpg",
    video: "https://www.youtube.com/embed/M7ybLzwN6pk",
    type: "premium",
    year: "2026",
    country: "Japan",
    duration: "1h 15m",
    synopsis: "A mysterious drama unfolding beneath an ancient tree."
  },
       {
    id: "mother",
    title: "MOTHER",
    poster: "https://i.ibb.co/WvHpNdQH/mrs-chatterjee-v-s-norway.jpg",
    video: "https://www.youtube.com/embed/n6lIp1mt74U",
    type: "free",
    year: "2025",
    country: "India",
    duration: "1h 25m",
    synopsis: "Debika Chatterjee, an Indian woman living in Norway with her family, fights to regain custody of her children after Norwegian authorities take them away from her.."
  }, 
   {
    id: "mo12ther",
    title: "MOTHER 2",
    poster: "https://i.ibb.co/WvHpNdQH/mrs-chatterjee-v-s-norway.jpg",
    video: "https://drive.google.com/file/d/1rCO7Y35snrYkQUxVLfcu6CXVNLH3Yc2p/preview",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1h 30m",
    synopsis: "Debika Chatterjee, an Indian woman living in Norway with her family, fights to regain custody of her children after Norwegian authorities take them away from her.."
  },
  {
    id: "aroundtheworl",
    title: "AROUND THE WORLD",
    poster: "https://m.media-amazon.com/images/M/MV5BNTgyMWFiM2ItZmY2OC00MTEyLWI0MzQtNTM1Y2RjNjIxOTRhXkEyXkFqcGc@._V1_.jpg",
    video: "https://drive.google.com/file/d/1X8qwvkbnAISlGy10VId6JB6oW6kjv607/preview",
    type: "free",
    year: "2025",
    country: "USA",
    duration: "1h 05m",
    synopsis: " Accompanied by his valet Passepartout, they face adventures, dangers, and romantic entanglements while racing against time, often involving a chase by an inspector who suspects Fogg of theft. "
  },
           {
    id: "aroundtheworld2",
    title: "AROUND THE WORLD 2",
    poster: "https://m.media-amazon.com/images/M/MV5BNTgyMWFiM2ItZmY2OC00MTEyLWI0MzQtNTM1Y2RjNjIxOTRhXkEyXkFqcGc@._V1_.jpg",
    video: "https://drive.google.com/file/d/1wanhjFACJLOJCCbr7btpCHO8wQFLBzOt/preview",
    type: "premium",
    year: "2025",
    country: "USA",
    duration: "1h 15m",
    synopsis: " Accompanied by his valet Passepartout, they face adventures, dangers, and romantic entanglements while racing against time, often involving a chase by an inspector who suspects Fogg of theft. "
  },
      {
    id: "theexibhit",
    title: "EKIZIBITI",
    poster: "https://i.ibb.co/cKPbBQcH/THE-EXHIBIT1.jpg",
    video: "https://www.youtube.com/embed/xoyotR6F_3c",
    type: "premium",
    year: "2025",
    country: "Uganda",
    duration: "1h 15m",
    synopsis: "It was a happy family, not until this unbelievable heartless woman got married to Semakula, a single father. She committed a crime. It was secret, yes, and no one saw her - that's what she thinks. But someone more smarter than her, has got the Exhibit and is ready to give it to the police, unless she accepts okusuna adungu"
  },
 {
    id: "saw51",
    title: "SAW",
    poster: "https://i.redd.it/o5a60xg8l6r61.jpg",
    video: "https://drive.google.com/file/d/17mY_LOnAAvFPUec1MU-XC4U-jZaYIPNW/preview",
    type: "premium",
    year: "2025",
    country: "USA",
    duration: "1h 15m",
    synopsis: " Photographer Adam Stanheight and oncologist Lawrence Gordon regain consciousness while chained to pipes at either end of a filthy bathroom. As the two men realize they've been trapped by a sadistic serial killer nicknamed jigsaw and must complete his perverse puzzle to live, flashbacks relate the fates of his previous victims. Meanwhile, Dr. Gordon's wife and young daughter are forced to watch his torture via closed-circuit video"
  },
    {
    id: "matilda",
    title: "MATILDA",
    poster: "https://media.vogue.mx/photos/63aa3de7a4dd10bbaf41871f/2:3/w_2560%2Cc_limit/matilda-alisha-weir-emma-thompsonjpg.jpg",
    video: "https://drive.google.com/file/d/197qsKXqNY7fM_EgqbAX7LgFrdWg_rixF/preview",
    type: "premium",
    year: "2025",
    country: "USA",
    duration: "1h 35m",
    synopsis: " a gifted girl forced to put up with a crude, distant father and mother. Worse, Agatha Trunchbull, the evil principal at Matilda's school, is a terrifyingly strict bully. However, when Matilda realizes she has the power of telekinesis, she begins to defend her friends from Trunchbull's wrath and fight back against her unkind parents."
  },
   {
    id: "rwanda",
    title: "HOTEL RWANDA",
    poster: "https://m.media-amazon.com/images/I/61jbFFhqOvL.jpg",
    video: "https://drive.google.com/file/d/1BYv48hR77jxOHvZWjuHKlc7OH5lIN1kr/preview",
    type: "premium",
    year: "2026",
    country: "Rwanda",
    duration: "1h 12m",
    synopsis: "Hutu Paul Rusesabagina manages the Hôtel des Mille Collines and lives a happy life with his Tutsi wife and their three children, but when Hutu military forces initiate a campaign of ethnic cleansing against the Tutsi minority, Paul is compelled to allow refugees to take shelter in his hotel. As the U.N. pulls out, Paul must struggle alone to protect the Tutsi refugees in the face of the escalating violence later known as the Rwandan genocide."
  },
         {
    id: "rwanda2",
    title: "HOTEL RWANDA 2",
    poster: "https://m.media-amazon.com/images/I/61jbFFhqOvL.jpg",
    video: "https://drive.google.com/file/d/16QwnMdiL21lLScVmJBMZlWwhyCXqI5jq/preview",
    type: "premium",
    year: "2026",
    country: "Rwanda",
    duration: "1h 12m",
    synopsis: "Hutu Paul Rusesabagina manages the Hôtel des Mille Collines and lives a happy life with his Tutsi wife and their three children, but when Hutu military forces initiate a campaign of ethnic cleansing against the Tutsi minority, Paul is compelled to allow refugees to take shelter in his hotel. As the U.N. pulls out, Paul must struggle alone to protect the Tutsi refugees in the face of the escalating violence later known as the Rwandan genocide."
  },
   
   {
    id: "josniper",
    title: "JOHN SNIPER",
    poster: "https://i.ibb.co/ynnpd3s4/urwjkjjd.jpg",
    video: "https://www.youtube.com/embed/EgchGwvEUEY",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1h 05m",
    synopsis: "John, an assassin, is filled with remorse after killing a family and decides to mend his ways. However, when his wife is kidnapped, he is forced to return to the criminal world one last time."
  },
   {
    id: "josnipe22r",
    title: "JOHN SNIPER 2",
    poster: "https://i.ibb.co/Q7vBC05R/nbvvf.jpg",
    video: "https://www.youtube.com/embed/I-oTe4htS6A",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 05m",
    synopsis: "John, an assassin, is filled with remorse after killing a family and decides to mend his ways. However, when his wife is kidnapped, he is forced to return to the criminal world one last time."
  },
      {
 id: "sa1kil",
    title: "SAIKIL",
    poster: "https://i.ibb.co/mPW1rrj/Untitled-design-2-9.jpg",
    video: "https://drive.google.com/file/d/1yPXRf8C1L3rQauEqn4U02mM-eolYw3cP/view",
    type: "free",
    year: "2025",
    country: "India",
    duration: "1hr 05m",
    synopsis: "Incredible action comedy movie. you will laugh and enjoy and forget your stress"
  },
         {
 id: "sa1kil22",
    title: "SAIKIL 2",
    poster: "https://i.ibb.co/mPW1rrj/Untitled-design-2-9.jpg",
    video: "https://drive.google.com/file/d/1Ghws-8MWfgL6s7MV5TQZhzRR7aH0fihH/view",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1hr 25m",
    synopsis: "Incredible action comedy movie. you will laugh and enjoy and forget your stress"
  },
  {
    id: "thesoft",
    title: "The SOFT and the SOLID",
    poster: "https://i.ibb.co/XfPD63kq/Untitled-1.jpg",
    video: "https://www.youtube.com/embed/I5qARzHbjGU",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 45m",
    synopsis: "Bangkok-based Johnny engages in a treachery that his employer, Ramona, witnesses. She blackmails him into killing a girl, Tanya, but suddenly something unexpected happens."
  },
       {
    id: "orion1",
    title: "ORION AND THE DARK",
    poster: "https://i.ibb.co/YncvYyd/photo-size-large-1920-scale-1-url-https-metadata-static-plex-tv-4-gracenote-484529c533.jpg",
    video: "https://drive.google.com/file/d/1l-X93mrCwSiE4Zvs2S6_jMHtgGyWSbI1/preview",
    type: "premium",
    year: "2025",
    country: "USA",
    duration: "1h 15m",
    synopsis: " deeply anxious 11-year-old boy paralyzed by fears—including bees, heights, and the dark—who is visited by the literal, gentle embodiment of dark. Dark takes him on a worldwide, magical journey to prove that nighttime is not to be feared, introducing him to other entities like Sleep, Quiet, and Insomnia. The story is revealed to be a tale told by an adult Orion to his daughter, ultimately focusing on conquering anxiety and embracing life"
  },
     {
    id: "jurassicrebirth",
    title: "JURRASIC WORLD Rebirth",
    poster: "https://i.ibb.co/Wvkwcgvz/FB-IMG-1751553903898.jpg",
    video: "https://drive.google.com/file/d/1SFy7HCO52Qe1d5pl8PpjdGqmLrpcB37r/preview",
    type: "premium",
    year: "2026",
    country: "USA",
    duration: "1h 15m",
    synopsis: " The team seeks a revolutionary drug to cure diseases, but finds the dinosaurs have mutated and a sinister secret is hidden in the ruins of an old, abandoned research facility. ."
  },
        {
    id: "jurassicrebirth",
    title: "JURRASIC WORLD Rebirth 2",
    poster: "https://i.ibb.co/Wvkwcgvz/FB-IMG-1751553903898.jpg",
    video: "https://drive.google.com/file/d/1-n6aSvRil0N0bNCawGJ01n0aTyRyR7TV/preview",
    type: "premium",
    year: "2026",
    country: "USA",
    duration: "1h 05m",
    synopsis: " The team seeks a revolutionary drug to cure diseases, but finds the dinosaurs have mutated and a sinister secret is hidden in the ruins of an old, abandoned research facility. ."
  },
       {
    id: "tanka",
    title: "TANK",
    poster: "https://gonewiththetwins.com/wp-content/uploads/2014/10/fury_tall.jpg",
    video: "https://www.youtube.com/embed/Z7L9lanYA-M",
    type: "free",
    year: "2025",
    country: "USA",
    duration: "1h 15m",
    synopsis: " In April 1945, the Allies are making their final push in the European theater. A battle-hardened Army sergeant named Don Wardaddy Collier, leading a Sherman tank and a five-man crew, undertakes a deadly mission behind enemy lines. Hopelessly outnumbered, outgunned and saddled with an inexperienced soldier in their midst, Wardaddy and his men face overwhelming odds as they move to strike at the heart of Nazi Germany.."
  },
     {
    id: "tanka2",
    title: "TANK 2",
    poster: "https://gonewiththetwins.com/wp-content/uploads/2014/10/fury_tall.jpg",
    video: "https://www.youtube.com/embed/jdRiEQWfUSg",
    type: "free",
    year: "2025",
    country: "USA",
    duration: "1h 15m",
    synopsis: " In April 1945, the Allies are making their final push in the European theater. A battle-hardened Army sergeant named Don Wardaddy Collier, leading a Sherman tank and a five-man crew, undertakes a deadly mission behind enemy lines. Hopelessly outnumbered, outgunned and saddled with an inexperienced soldier in their midst, Wardaddy and his men face overwhelming odds as they move to strike at the heart of Nazi Germany.."
  },
     {        
    id: "hinduta",
    title: "HINDUTAN",
    poster: "https://images.news18.com/webstories/uploads/2024/11/FotoJet-38-2024-11-893b35063c060c56bf57d5f2b89c47f0.jpg",
    video: "https://www.youtube.com/embed/2e2m8XLMpo4",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1h 15m",
    synopsis: "A great tale about a Moslem nation that could not allow their King mary a christian princess, yet  she was the only key to peace and unity among the nations."
  },
       {
    id: "hindutwo",
    title: "HINDUTAN 2",
    poster: "https://images.news18.com/webstories/uploads/2024/11/FotoJet-38-2024-11-893b35063c060c56bf57d5f2b89c47f0.jpg",
    video: "https://www.youtube.com/embed/Xpe9R7Wl_1Y",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 15m",
    synopsis: "A great tale about a Moslem nation that could not allow their King mary a christian princess, yet  she was the only key to peace and unity among the nations."
  },
       {
    id: "hinduthree",
    title: "HINDUTAN 3",
    poster: "https://images.news18.com/webstories/uploads/2024/11/FotoJet-38-2024-11-893b35063c060c56bf57d5f2b89c47f0.jpg",
    video: "https://www.youtube.com/embed/BV-ATSKOSrw",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 15m",
    synopsis: "A great tale about a Moslem nation that could not allow their King mary a christian princess, yet  she was the only key to peace and unity among the nations."
  },
          {
    id: "holynight",
    title: "HOLY NIGHT",
    poster: "https://images.justwatch.com/poster/330212273/s718/holy-night-demon-hunters.jpg",
    video: "https://drive.google.com/file/d/1MhfwHBOX3wxhHq5s1r_XicNI-_791RVv/preview",
    type: "premium",
    year: "2025",
    country: "Korea",
    duration: "1h 15m",
    synopsis: " is a South Korean supernatural action film where a specialized team—super-strong Ba Woo , exorcist Sharon, and researcher Kim Gun —combats a demonic cult, the Black Mass, that has unleashed chaos in Seoul. The team works to save a possessed girl"
  },
   {
    id: "chotebro",
    title: "CHOTE",
    poster: "https://img.indiaforums.com/movie/350x525/7/319-daaku-maharaaj.webp?c=2oO5F7",
    video: "https://www.youtube.com/embed/EQXcutRBXvA",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 25m",
    synopsis: "Everyone calls him brother. his love for his sister is endless. he can fight and even ready to die for her"
  },
             {
    id: "chotebros",
    title: "CHOTE 2",
    poster: "https://img.indiaforums.com/movie/350x525/7/319-daaku-maharaaj.webp?c=2oO5F7",
    video: "https://www.youtube.com/embed/GqZmqHF0rRU",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 25m",
    synopsis: "Everyone calls him brother. his love for his sister is endless. he can fight and even ready to die for her"
  },
               {
    id: "liwena",
    title: "SILVER SLIPPERS",
    poster: "https://i.ibb.co/FNgNbcL/BBBBB.jpg",
    video: "https://www.youtube.com/embed/DtRoBh0jppI",
    type: "premium",
    year: "2026",
    country: "USA",
    duration: "1h 15m",
    synopsis: "During a tornado, Dorothy is once again whisked away to the Land of Oz and encounters the cousin of the Wicked Witch of the West, who is attacking the Emerald City with an army of monstrous green elephants"
  },
   
      {
    id: "sankat1",
    title: "SANKAT",
    poster: "https://upload.wikimedia.org/wikipedia/hi/b/b9/%E0%A4%95%E0%A5%81%E0%A4%9B_%E0%A4%A4%E0%A5%8B_%E0%A4%B9%E0%A5%88.jpg",
    video: "https://drive.google.com/file/d/1A4UJn5OgPowpBPpJlZH6_g1Uk-UGgJrr/preview",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1h 05m",
    synopsis: "A group of college students face a tragedic semister when they enter a weird professor's house "
  },  
       {
    id: "1anna1",
    title: "ANNA",
    poster: "https://i.pinimg.com/736x/c2/3a/cd/c23acd89369cfcb3273f632c374ed2b4.jpg",
    video: "https://www.youtube.com/embed/K0-AdBt0ncg",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1h 05m",
    synopsis: "Anna is a griping emotional action moviet that you can't miss"
  },
          {
    id: "1anna2",
    title: "ANNA 2",
    poster: "https://i.pinimg.com/736x/c2/3a/cd/c23acd89369cfcb3273f632c374ed2b4.jpg",
    video: "https://www.youtube.com/embed/eZNIvshGBPo",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1h 05m",
    synopsis: "Anna is a griping emotional action moviet that you can't miss"
  },
      {
    id: "sankat2",
    title: "SANKAT 2",
    poster: "https://upload.wikimedia.org/wikipedia/hi/b/b9/%E0%A4%95%E0%A5%81%E0%A4%9B_%E0%A4%A4%E0%A5%8B_%E0%A4%B9%E0%A5%88.jpg",
    video: "https://drive.google.com/file/d/1XYpU_XPn-GWQBXBIG52UMq2uHRgCP_lD/preview",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 15m",
    synopsis: "what happens next when A group of college students face a tragedic semister when they enter a weird professor's house "
  },
        {
    id: "the1field",
    title: "THE FIELD",
    poster: "https://stat5.bollywoodhungama.in/wp-content/uploads/2022/10/Crakk-2.jpg1_-306x393.jpg",
    video: "https://www.youtube.com/embed/-D63zpPOlB0",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 15m",
    synopsis: "A man journeys from the slums of Mumbai to the world of underground extreme sports, as he attempts to make his mark on the outlaw competition Maidaan and discover what happened to his brother"
  },
       {
    id: "the1field22",
    title: "THE FIELD 2",
    poster: "https://stat5.bollywoodhungama.in/wp-content/uploads/2022/10/Crakk-2.jpg1_-306x393.jpg",
    video: "https://www.youtube.com/embed/P15TKnlrj7c",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 15m",
    synopsis: "A man journeys from the slums of Mumbai to the world of underground extreme sports, as he attempts to make his mark on the outlaw competition Maidaan and discover what happened to his brother"
  },
    {
    id: "high11",
    title: "HIGH",
    poster: "https://i.ibb.co/8nBd8jMb/Untitled-1-Recovered-Recovered-Recovered.jpg",
    video: "https://www.youtube.com/embed/TUCxNR97Grs",
    type: "free",
    year: "2026",
    country: "USA",
    duration: "1h 05m",
    synopsis: " This is a tense, vertigo-inducing survival thriller where best friends Becky and Hunter get trapped 2,000 feet up on an abandoned radio tower in the Mojave Desert. After the ladder breaks, they must endure extreme dehydration, vultures, and dwindling supplies to surviv "
  },  
   {
    id: "high12",
    title: "HIGH 2",
    poster: "https://i.ibb.co/8nBd8jMb/Untitled-1-Recovered-Recovered-Recovered.jpg",
    video: "https://www.youtube.com/embed/1pFTyO1zLHk",
    type: "premium",
    year: "2026",
    country: "USA",
    duration: "1h 05m",
    synopsis: " This is a tense, vertigo-inducing survival thriller where best friends Becky and Hunter get trapped 2,000 feet up on an abandoned radio tower in the Mojave Desert. After the ladder breaks, they must endure extreme dehydration, vultures, and dwindling supplies to surviv "
  },  
    
  {
    id: "kanor1",
    title: "KANOR",
    poster: "https://i.ibb.co/Zphm4pNY/KANOR.jpg",
    video: "https://www.youtube.com/embed/p31wdNO5ibQ",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1h 25m",
    synopsis: "Sameer Mehra (Emraan Hashmi), an ad executive, takes shelter at a remote mountain home during a snowstorm. He is forced to participate in a psychological game of mock trial conducted by retired legal professionals—including Lateef Zaidi (Amitabh Bachchan)—who scrutinize his past crimes. "
  }, 
    {
    id: "kanor2",
    title: "KANOR 2",
    poster: "https://i.ibb.co/Zphm4pNY/KANOR.jpg",
    video: "https://www.youtube.com/embed/kZJHntZJKoI",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 25m",
    synopsis: "What happens next executive  takes shelter at a remote mountain home during a snowstorm and He is forced to participate in a psychological game of mock trial conducted by retired legal professionals—including Lateef Zaidi (Amitabh Bachchan)—who scrutinize his past crimes. "
  }, 
  {
    id: "bob1",
    title: "BOB",
    poster: "https://i.ibb.co/wZLWXscX/Untitled-1.jpg",
    video: "https://drive.google.com/file/d/15TOiFNFoEWGAVoGp_ruUIa9NQ6TX5jE-/preview",
    type: "free",
    year: "2026",
    country: "China",
    duration: "1h 12m",
    synopsis: "One ordinary day, Bob follows his instincts and trails two suspicious-looking men into an alley. When he realizes they are robbing a bank, Bei jumps into action and foils their plans. The resulting publicity brings Bei the shock that his parents were both professional spies. Drawn into a dangerous game of cat and mouse, Bei travels to Turkey to stop a group of evil drug lords."
  },   
    {
    id: "bob2",
    title: "BOB 2",
    poster: "https://i.ibb.co/wZLWXscX/Untitled-1.jpg",
    video: "https://drive.google.com/file/d/1J-xjvKCz4OmyXi9UUj6vpgwbea3zulnE/preview",
    type: "premium",
    year: "2026",
    country: "China",
    duration: "1h 12m",
    synopsis: "One ordinary day, Bob follows his instincts and trails two suspicious-looking men into an alley. When he realizes they are robbing a bank, Bei jumps into action and foils their plans. The resulting publicity brings Bei the shock that his parents were both professional spies. Drawn into a dangerous game of cat and mouse, Bei travels to Turkey to stop a group of evil drug lords."
  },  
      {
    id: "pickup",
    title: "THE PICK UP",
    poster: "https://upload.wikimedia.org/wikipedia/en/d/d8/The_Pickup_2025_poster.jpg",
    video: "https://drive.google.com/file/d/16HV04cwCCsGbkhrJIATzHb_CKIw4bU6f/view",
    type: "premium",
    year: "2026",
    country: "USA",
    duration: "1h 12m",
    synopsis: "A routine cash pickup takes a wild turn when two mismatched armored truck drivers get ambushed by ruthless criminals. As chaos unfolds around them, the unlikely duo must navigate high-risk danger, clashing personalities, and one very bad day that keeps getting worse."
  },  
    
          {
    id: "vault1",
    title: "THE VAULT",
    poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzmPDqOkNsLCDfyHpD_Oq4qGFdnVbkTyVEviWy95hoAERvf9_DFoXxy3oreah_jrMoKHIN&s=10",
    video: "https://drive.google.com/file/d/1svKcGMOXcy2b9NQXYLqLF9Xs0jdNARq5/preview",
    type: "premium",
    year: "2025",
    country: "USA",
    duration: "1h 10m",
    synopsis: "a high-stakes heist thriller about a genius engineering graduate, Thom (Freddie Highmore), who joins a crew led by Walter (Liam Cunningham) to rob the famously impenetrable Bank of Spain"
  },  
            {
    id: "vault2",
    title: "THE VAULT 2",
    poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkYkw0RY3VkZlFjS_7gPL8UL1ucoL1PfYPcA&s",
    video: "https://drive.google.com/file/d/1roGhWKYNuGhti1FFb1aQq7Ov0332ZQhS/preview",
    type: "premium",
    year: "2025",
    country: "USA",
    duration: "1h 20m",
    synopsis: "a high-stakes heist thriller about a genius engineering graduate, Thom (Freddie Highmore), who joins a crew led by Walter (Liam Cunningham) to rob the famously impenetrable Bank of Spain"
  },  
              {
    id: "thousand",
    title: "TEN THOUSAND YEARS BACK",
    poster: "https://image.tmdb.org/t/p/original/5XNthY4hzdKD2QxnlXbzIFYbtw6.jpg",
    video: "https://drive.google.com/file/d/1ZvJewP1LQxzjuxfcjbZ1zzO2V8Imthb-/preview",
    type: "premium",
    year: "2024",
    country: "Taiwan",
    duration: "1h 20m",
    synopsis: "A handsome Prince from the Qin dynasty travels into the future, and meets a bossy girl. the two madly fall in love"
  },  
       {
    id: "400",
    title: "400 BULLETS",
    poster: "https://a.ltrbxd.com/resized/film-poster/7/0/6/9/7/8/706978-400-bullets-0-230-0-345-crop.jpg?v=26211e223b",
    video: "https://www.youtube.com/embed/JCh54UGPqFA",
    type: "free",
    year: "2026",
    country: "USA",
    duration: "1h 30m",
    synopsis: "Two soldiers in Afghanistan face off against a group of rogue special ops and a cell of heavily armed Taliban"
  },  
 
              {
    id: "cabin",
    title: "CABIN IN THE WOODS",
    poster: "https://posterspy.com/wp-content/uploads/2022/11/cabin-posterspy-Ygris.jpg",
    video: "https://drive.google.com/file/d/1n-Er3F4oPUmt0lWh8d4on--rltB45K3m/preview",
    type: "premium",
    year: "2022",
    country: "USA",
    duration: "1h 40m",
    synopsis: "When five college friends (Kristen Connolly, Chris Hemsworth, Anna Hutchison, Fran Kranz, Jesse Williams) arrive at a remote forest cabin for a little vacation, little do they expect the horrors that await them. One by one, the youths fall victim to backwoods zombies, but there is another factor at play. Two scientists (Richard Jenkins, Bradley Whitford) are manipulating the ghoulish goings-on, but even as the body count rises, there is yet more at work than meets the eye."
  },
    {
    id: "chautal1",
    title: "CHAUTALA",
    poster: "https://st1.bollywoodlife.com/wp-content/uploads/2024/07/1-37.png?impolicy=Medium_Widthonly&w=400&h=711",
    video: "https://www.youtube.com/embed/9OK326dtdMA",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 10m",
    synopsis: "Hindi thriller following four friends—Dev, Devi, Gaurav, and Aditya—whose carefree lives are ruined when they encounter a corrupt, ruthless police officer, SHO Chautala. After an incident involving a local shopkeeper, the friends are blackmailed and framed, forcing them to fight against the system. ."
  },
      {
    id: "chautal2",
    title: "CHAUTALA",
    poster: "https://st1.bollywoodlife.com/wp-content/uploads/2024/07/1-37.png?impolicy=Medium_Widthonly&w=400&h=711",
    video: "https://www.youtube.com/embed/v7bnBboesXM",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 35m",
    synopsis: "Hindi thriller following four friends—Dev, Devi, Gaurav, and Aditya—whose carefree lives are ruined when they encounter a corrupt, ruthless police officer, SHO Chautala. After an incident involving a local shopkeeper, the friends are blackmailed and framed, forcing them to fight against the system. ."
  },
    {
    id: "chattan11",
    title: "CHATTAN",
    poster: "https://bollyspice.com/wp-content/uploads/2018/07/Satyameva-Jayate.jpeg",
    video: "https://drive.google.com/file/d/1AdYRASlD0LJQEAF-Wy1-5CZ692cVcWsP/view",
    type: "free",
    year: "2025",
    country: "India",
    duration: "1h 15m",
    synopsis: "Kabir Ahlawat, a quiet, reclusive pawn shop owner in Goa with a dark past as an undercover agent. When his young, neglected neighbor, Naomi, is kidnapped by a drug-and-organ-trafficking mafia, Kabir unleashes a violent, one-man army revenge spree to save her."
  },
      {
    id: "chattan1221",
    title: "CHATTAN 2",
    poster: "https://bollyspice.com/wp-content/uploads/2018/07/Satyameva-Jayate.jpeg",
    video: "https://drive.google.com/file/d/1P0ci6zuE9pwJUOgEkGkcDmKVSR8lGhMb/view",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1h 15m",
    synopsis: "Kabir Ahlawat, a quiet, reclusive pawn shop owner in Goa with a dark past as an undercover agent. When his young, neglected neighbor, Naomi, is kidnapped by a drug-and-organ-trafficking mafia, Kabir unleashes a violent, one-man army revenge spree to save her."
  },
      {
    id: "deadocea",
    title: "DEADLY OCEAN",
    poster: "https://i.ibb.co/V05qK36q/Untitled-1.jpg",
    video: "https://drive.google.com/file/d/1-gZeHxzUV4T0dcHVDTbyw4HalyVi5aWR/preview",
    type: "premium",
    year: "2025",
    country: "USA",
    duration: "1h 30m",
    synopsis: "A plane full of VIP travellers is stuck with deadly creatures of the past "
  },  
   {
    id: "dirty12",
    title: "DIRTY DOZEN",
    poster: "https://i.ibb.co/zkk7HZp/Untitled-1.jpg",
    video: "https://drive.google.com/file/d/1pleS1NBtZuZZJwk1gAnWUKsGu2PHiKSi/view",
    type: "premium",
    year: "2025",
    country: "USA",
    duration: "1h 30m",
    synopsis: "As D-Day approaches, Colonel Breed hands the roguish Major Reisman an important assignment: He must train a team of soldiers to parachute across enemy lines and assassinate German personnel at a French château. The soldiers, recruited from murderers, rapists and criminals on death row, are promised commuted sentences. In spite of their history, the 12 men prove a spirited and courageous unit. Led by Major Reisman, they will exact revenge "
  },   
    {
    id: "horizonend",
    title: "HORIZON END",
    poster: "https://i.ibb.co/wHvHXyW/IMG-20250912-WA0007.jpg",
    video: "https://drive.google.com/file/d/1x7p-CP7sXYp-x1hrVFa6EPAGQMt52NIh/preview",
    type: "premium",
    year: "2025",
    country: "USA",
    duration: "1h 30m",
    synopsis: "Crusoe, a 19th-century Virginia slave trader is shipwrecked on a remote island while en route to Africa. Alone except for a dog, he learns to survive, but his isolation leads to a profound psychological journey and a reassessment of his pro-slavery views after encountering native islanders and befriending a man he saves. "
  },   
   {
    id: "unstoppable",
    title: "UNSTOPABLE ROBOT",
    poster: "https://m.media-amazon.com/images/M/MV5BNDdhMWExMTItOTNiNy00MDgxLWIyMDktNjYxNWU3ZGFjM2IyXkEyXkFqcGc@._V1_.jpg",
    video: "https://www.youtube.com/embed/3TXDJLd6w2Q",
    type: "free",
    year: "2019",
    country: "China",
    duration: "1h 30m",
    synopsis: "When robots take over the city of Hong Kong, one ultmate Robot with a sense of understanding must come forward to fight the battle"
  },  
         {
    id: "jamu",
    title: "JAM",
    poster: "https://www.punjabnewsexpress.com/images/article/article206579.jpg",
    video: "https://www.youtube.com/embed/R0c3hy6Euok",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 55m",
    synopsis: " Hindi-language emotional thriller directed by the late Rajesh Pillai, featuring an ensemble cast led by Manoj Bajpayee, Jimmy Sheirgill, Prosenjit Chatterjee, and Divya Dutta. It is a remake of the 2011 Malayalam film of the same name and is inspired by a real-life incident in Chennai where a heart was transported for a transplant."
  },
   {
    id: "walter",
    title: "WALTER",
    poster: "https://i.ibb.co/Q7w7cJsS/images-q-tbn-ANd9-Gc-Qqxd-Iu-S98-YGfp-OAGUrjv-H1-X-CLVYjztn-O5-CQ-s.jpg",
    video: "https://drive.google.com/file/d/1rTcpGphGbRHDgXWQRB0niK54dRfzM0st/preview",
    type: "premium",
    year: "2022",
    country: "USA",
    duration: "1h 40m",
    synopsis: "Walter is an imposing but gentle man who works as a night security guard at a supermarket. A team of five amateur burglars, led by the determined Victor, plan a perfect robbery to steal from the store's jeweler. They deliberately trigger the alarm to lure the security guard out, expecting an easy takeover."
  }, 
       {
    id: "mine",
    title: "MINE",
    poster: "https://m.media-amazon.com/images/M/MV5BMzYxNDFiZmQtYjNmZi00MzE1LWE3ODQtOTdlYjhhM2Y2ZmE2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    video: "https://drive.google.com/file/d/1BipH5Qsg-k8Ah_DP1P0iVU9HE-6KfQyp/view",
    type: "premium",
    year: "2022",
    country: "USA",
    duration: "1h 40m",
    synopsis: "Mine is a psychological thriller starring Armie Hammer as a U.S. Marine sniper stranded in the desert after a botched mission. After stepping on a landmine, he must stay still for 52 hours to survive, battling the elements, hostile forces, and his own psychological demons while waiting for rescue. "
  }, 
          {
    id: "brant23",
    title: "BRANT",
    poster: "https://play-lh.googleusercontent.com/8PmJGVmFtEYVrnjcEvHr2Zl0bMYtjufSxmTBXb87NN7VF16lBr4bD4mUFV5Ae0uQ52-yLp1pdBF7NuOUtm4",
    video: "https://drive.google.com/file/d/1BipH5Qsg-k8Ah_DP1P0iVU9HE-6KfQyp/view",
    type: "premium",
    year: "2023",
    country: "USA",
    duration: "1h 40m",
    synopsis: "When Jason Stantham appears, what do you expect? Super action movie"
  }, 
        {
    id: "brant2",
    title: "BRANT PART 2",
    poster: "https://play-lh.googleusercontent.com/8PmJGVmFtEYVrnjcEvHr2Zl0bMYtjufSxmTBXb87NN7VF16lBr4bD4mUFV5Ae0uQ52-yLp1pdBF7NuOUtm4",
    video: "https://drive.google.com/file/d/1wURAFpDI9N9MAA-ITigYhQP_dIjQzGme/view",
    type: "premium",
    year: "2023",
    country: "USA",
    duration: "1h 10m",
    synopsis: "When Jason Stantham appears, what do you expect? Super action blockbuster movie"
  },
       {
    id: "doradoel",
    title: "EL DORADO",
    poster: "https://i.ibb.co/DHTJcz03/images-q-tbn-ANd9-Gc-Qt4-T0-Rx-OL6-Ubqv-U4-H-mm1vnb-TZYz-Az-TP9-O3-Q-s.jpg",
    video: "https://drive.google.com/file/d/1GmrHegKf0ctSZviQx76ssT_jCJhuAETx/preview",
    type: "premium",
    year: "2023",
    country: "USA",
    duration: "1h 10m",
    synopsis: "gunfighter Cole Thornton refuses a job to help a ruthless landowner force the McDonald family off their ranch, knowing his friend, Sheriff J.P. Harrah, is tasked with protecting them. Months later, Thornton learns Harrah has become an alcoholic, leaving the town vulnerable to the landowner's hired thugs"
  },
           {
    id: "risen",
    title: "RISEN",
    poster: "https://i.ibb.co/WNM90L7t/p11952567-v-v10-aa.jpg",
    video: "https://drive.google.com/file/d/1N724u2-1qdf3bMj7-ogbAyMtg1zAtDCU/preview",
    type: "premium",
    year: "2023",
    country: "USA",
    duration: "1h 10m",
    synopsis: "Roman military tribune Clavius remains set in his ways after serving 25 years in the army. He arrives at a crossroad when he's tasked to investigate the mystery of what happened to Jesus following the Crucifixion. Accompanied by trusted aide Lucius, his quest to disprove rumors of a risen Messiah makes him question his own beliefs and spirituality. As his journey takes him to places never dreamed of, Clavius discovers the truth that he's been seeking"
  },
             {
    id: "wwohelpmates",
    title: "HELPMATES",
    poster: "https://i.ibb.co/8LLdzQky/images-9.jpg",
    video: "https://drive.google.com/file/d/1r_PP1d7TAdqhmIeJtyz9jJ9vtdDUfO6x/preview",
    type: "free",
    year: "2019",
    country: "USA",
    duration: "1h 30m",
    synopsis: "A special forces soldier, known for his marksmanship, must battle a group of foreign mercenaries hired to slay him by a drug lord"
  },
   {
    id: "wwowo",
    title: "WOLF WORRIOR",
    poster: "https://i.ibb.co/j9bnDgPG/images-5.jpg",
    video: "https://drive.google.com/file/d/1wURAFpDI9N9MAA-ITigYhQP_dIjQzGme/view",
    type: "free",
    year: "2019",
    country: "China",
    duration: "1h 30m",
    synopsis: "A special forces soldier, known for his marksmanship, must battle a group of foreign mercenaries hired to slay him by a drug lord"
  },
          {
    id: "faithcabin",
    title: "FAITH CABIN",
    poster: "https://m.media-amazon.com/images/M/MV5BN2I0NjlkYjgtMWU5Mi00NGYwLThjNTYtMzM1MGI2ZTQ3OTIyXkEyXkFqcGc@._V1_.jpg",
    video: "https://www.youtube.com/embed/7EV1XVz7dA4",
    type: "free",
    year: "2025",
    country: "USA",
    duration: "1h 20m",
    synopsis: "After suffering a family tragedy, Mack Phillips spirals into a deep depression that causes him to question his innermost beliefs. Facing a crisis of faith, he receives a mysterious letter urging him to an abandoned shack in the Oregon wilderness. Despite his doubts, Mack journeys to the shack and encounters an enigmatic trio of strangers led by a woman named Papa. Through this meeting, Mack finds important truths that will transform his understanding of his tragedy and change his life forever"
  },
            {
    id: "faithcabin2",
    title: "FAITH CABIN 2",
    poster: "https://m.media-amazon.com/images/M/MV5BN2I0NjlkYjgtMWU5Mi00NGYwLThjNTYtMzM1MGI2ZTQ3OTIyXkEyXkFqcGc@._V1_.jpg",
    video: "https://www.youtube.com/embed/F25D62Y-Q44",
    type: "premium",
    year: "2025",
    country: "USA",
    duration: "1h 20m",
    synopsis: "After suffering a family tragedy, Mack Phillips spirals into a deep depression that causes him to question his innermost beliefs. Facing a crisis of faith, he receives a mysterious letter urging him to an abandoned shack in the Oregon wilderness. Despite his doubts, Mack journeys to the shack and encounters an enigmatic trio of strangers led by a woman named Papa. Through this meeting, Mack finds important truths that will transform his understanding of his tragedy and change his life forever"
  },
  {
    id: "warship11",
    title: "WAR SHIP",
    poster: "https://m.media-amazon.com/images/M/MV5BYmQzNWM2NTEtNGU2Yi00MmVlLWE5MWItMGE1M2ZlNzI0Y2Y5XkEyXkFqcGc@._V1_.jpg",
    video: "https://www.youtube.com/embed/x38i6jZnuWk",
    type: "free",
    year: "2025",
    country: "USA",
    duration: "1h 10m",
    synopsis: "another beautiful movie to take away your stress"
  },
  {
    id: "warship12",
    title: "WAR SHIP 2",
    poster: "https://m.media-amazon.com/images/M/MV5BYmQzNWM2NTEtNGU2Yi00MmVlLWE5MWItMGE1M2ZlNzI0Y2Y5XkEyXkFqcGc@._V1_.jpg",
    video: "https://www.youtube.com/embed/RLb5iXT3Udo",
    type: "premium",
    year: "2025",
    country: "USA",
    duration: "1h 10m",
    synopsis: "another beautiful movie to take away your stress"
  },
  {
    id: "amanni",
    title: "AMANI",
    poster: "https://static.titlovi.com/img/0228/228698-tt0234000.jpg",
    video: "https://www.youtube.com/embed/D2vaZ6yOfg4",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 10m",
    synopsis: "Laba film eno olabe omukwano gwa brother bweguba. Oluvanyuma lwokwekalakasa okwali ku kyalo, omwafiira abavubuka amakumi ataano, Amani yabula, wabula Mwanyina anasobola okumuzuula?."
  },
   {
    id: "amannni",
    title: "AMANI 2",
    poster: "https://static.titlovi.com/img/0228/228698-tt0234000.jpg",
    video: "https://www.youtube.com/embed/aayEWSxngbg",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 10m",
    synopsis: "Laba film eno olabe omukwano gwa brother bweguba. Oluvanyuma lwokwekalakasa okwali ku kyalo, omwafiira abavubuka amakumi ataano, Amani yabula, wabula Mwanyina anasobola okumuzuula?."
  },
     {
    id: "shoony",
    title: "SHOONY",
    poster: "https://i.ibb.co/DD367QqD/pooooo.jpg",
    video: "https://www.youtube.com/embed/n-meJRIBMQQ",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1h 10m",
    synopsis: "Dhritiman Chaterji and Catherine McNally give birth to their first daughter, Michelle  who can neither hear nor see. Not knowing how to care for a deaf and blind child, they isolate their daughter from the outside world and as a result, she is ill-behaved and emotionally distraught. Paul even considers putting Michelle in a mental hospital until an eccentric teacher with a questionable past offers to help."
  },
       {
    id: "shoonnnyyy",
    title: "SHOONY 2",
    poster: "https://i.ibb.co/DD367QqD/pooooo.jpg",
    video: "https://www.youtube.com/embed/eLPtLBbi4C8",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1h 10m",
    synopsis: "Dhritiman Chaterji and Catherine McNally give birth to their first daughter, Michelle  who can neither hear nor see. Not knowing how to care for a deaf and blind child, they isolate their daughter from the outside world and as a result, she is ill-behaved and emotionally distraught. Paul even considers putting Michelle in a mental hospital until an eccentric teacher with a questionable past offers to help."
  },
       {
    id: "greaterwall",
    title: "THE GREAT WALL",
    poster: "https://m.media-amazon.com/images/M/MV5BMjA3MjAzOTQxNF5BMl5BanBnXkFtZTgwOTc5OTY1OTE@._V1_.jpg",
    video: "https://drive.google.com/file/d/1PFWXmSzfR2K21QZyqo3cvxDg3WyvSach/preview",
    type: "premium",
    year: "2024",
    country: "China",
    duration: "1h 40m",
    synopsis: "When a mercenary warrior is imprisoned within the Great Wall, he discovers the mystery behind one of the greatest wonders of the world. As wave after wave of marauding beasts besiege the massive structure, his quest for fortune turns into a journey toward heroism as he joins a huge army of elite warriors to confront the unimaginable and seemingly unstoppable force."
  },
         {
    id: "greaterwalls",
    title: "THE GREAT WALL 2",
    poster: "https://m.media-amazon.com/images/M/MV5BMjA3MjAzOTQxNF5BMl5BanBnXkFtZTgwOTc5OTY1OTE@._V1_.jpg",
    video: "https://drive.google.com/file/d/1YgT9geArNCQvxDq20xgUv3PtOtRarMBB/preview",
    type: "premium",
    year: "2024",
    country: "China",
    duration: "1h 40m",
    synopsis: "When a mercenary warrior is imprisoned within the Great Wall, he discovers the mystery behind one of the greatest wonders of the world. As wave after wave of marauding beasts besiege the massive structure, his quest for fortune turns into a journey toward heroism as he joins a huge army of elite warriors to confront the unimaginable and seemingly unstoppable force."
  },
     {
    id: "poolhorror",
    title: "POOL",
    poster: "https://m.media-amazon.com/images/I/71GP9nsSFsL._AC_UF894,1000_QL80_.jpg",
    video: "https://drive.google.com/file/d/12W095GJfn1rh1OKpS8XKFbUZQ5ujtJHY/preview",
    type: "premium",
    year: "2024",
    country: "Thailand",
    duration: "1h 40m",
    synopsis: "Deyi, is left alone to clear up a 6-meter deep deserted pool after shooting a film. He is really tired and falls asleep on an inflatable raft. When he wakes up again the water level has sunk so low that he cannot climb out of the pool on his own."
  },
           {
    id: "misota",
    title: "RISING BOARS",
    poster: "https://m.media-amazon.com/images/M/MV5BMGU4ZTU2N2YtYTM2NC00YTRiLWFkODktYWMyY2Q5NmM4NzUxXkEyXkFqcGc@._V1_.jpg",
    video: "https://drive.google.com/file/d/1Zh2xXKVQMku8O8ppRd6pMk2QVVK93sXO/preview",
    type: "premium",
    year: "2024",
    country: "Thailand",
    duration: "1h 40m",
    synopsis: "The mutated, ginormous boa and a horde of smaller, aggressive, venomous snakes escape from the breeding base. The snakes head to a nearby flight attendant aviation college, which is preparing for a graduation ceremony and competition."
  },
       {
    id: "calledman",
    title: "MAN CALLED HERO",
    poster: "https://pic0.iqiyipic.com/image/20250728/00/ed/v_165631021_m_601_en_m1_260_360.jpg",
    video: "https://drive.google.com/file/d/1f2eYbmrIMuXCnv7cFholzmKNhJ84ydLF/preview",
    type: "premium",
    year: "2024",
    country: "China",
    duration: "1h 40m",
    synopsis: "A martial arts expert flees to New York after carrying out a violent vendetta against his parents murderers. Sixteen years later, the man must repay a debt of honour to the people whom he has wronged."
  },
    {
    id: "wolf200",
    title: "200 WOLF",
    poster: "https://i.ibb.co/tPqBwKvq/werewolf.jpg",
    video: "https://drive.google.com/file/d/1Rkszg7K3q04q9ULpppQ6TFjmRIE_Qn_u/preview",
    type: "premium",
    year: "2024",
    country: "USA",
    duration: "1h 30m",
    synopsis: "Heroic Freddy has everything it takes to lead a pack... except the appearance. But his wayward wish to transform from a poodle to a werewolf will finally come true with the help of a mischievous moon sprite that reached Earth"
  },
   {
    id: "wobear",
    title: "PANDA BEAR",
    poster: "https://m.media-amazon.com/images/M/MV5BNGI3YWFkMWEtZTZjNS00NWI1LThiYWEtZDBlZDg4NWRjMzcxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    video: "https://drive.google.com/file/d/1e3Ro2fUxWrEbsLVXjnrj7-C4EQtEOmoU/preview",
    type: "premium",
    year: "2025",
    country: "USA",
    duration: "1h 50m",
    synopsis: "Mpanga is a young panda who grows up in an idyllic village in the heart of China. But when her best friend, Jielong the dragoness, is kidnapped to be offered as a gift to a capricious young lion king, Pang leaves for Africa to save her friend"
  },
     {
    id: "litomermaid",
    title: "LITTLE MERMAID",
    poster: "https://i.ibb.co/ds0HC7ZH/image-3b188446.jpg",
    video: "https://drive.google.com/file/d/1bQLNf9gI4aHTbfohmAARUsiyYZS0Z-vk/preview",
    type: "premium",
    year: "2024",
    country: "USA",
    duration: "1h 50m",
    synopsis: "rebellious 16 year-old mermaid Ariel is fascinated with life on land. On one of her visits to the surface, which are forbidden by her controlling father, King Triton, she falls for a human prince. Determined to be with her new love, Ariel makes a dangerous deal with the sea witch Ursula to become human for three days. But when plans go awry for the star-crossed lovers, the king must make the ultimate sacrifice for his daughter"
  },
      {
    id: "lito2mermaid",
    title: "LITTLE MERMAID 2",
    poster: "https://i.ibb.co/ds0HC7ZH/image-3b188446.jpg",
    video: "https://drive.google.com/file/d/18iDi6gFCHnpDnaWjdtObuK5V8HwjzWjA/preview",
    type: "premium",
    year: "2024",
    country: "USA",
    duration: "1h 10m",
    synopsis: "rebellious 16 year-old mermaid Ariel is fascinated with life on land. On one of her visits to the surface, which are forbidden by her controlling father, King Triton, she falls for a human prince. Determined to be with her new love, Ariel makes a dangerous deal with the sea witch Ursula to become human for three days. But when plans go awry for the star-crossed lovers, the king must make the ultimate sacrifice for his daughter"
  },
        {
    id: "jorneybeijing1",
    title: "JOURNEY TO BEIJING",
    poster: "https://m.media-amazon.com/images/M/MV5BNzhhMmQ2YTUtMzFlZi00OWNmLWJmYjMtZjYyODE1YTAxMGZmXkEyXkFqcGc@._V1_.jpg",
    video: "https://drive.google.com/file/d/1ZOOo0ozWvk7wYR8NZQwZP-_B-zabKuLK/preview",
    type: "premium",
    year: "2024",
    country: "China",
    duration: "1h 10m",
    synopsis: "Witness the brave boy who begins the journey to seek his father"
  },
        {
    id: "jorneybeiji22ng1",
    title: "JOURNEY TO BEIJING 2",
    poster: "https://m.media-amazon.com/images/M/MV5BNzhhMmQ2YTUtMzFlZi00OWNmLWJmYjMtZjYyODE1YTAxMGZmXkEyXkFqcGc@._V1_.jpg",
    video: "https://drive.google.com/file/d/1L_AWefNfMmECY_vtZdxycpb7BvQ6naYb/preview",
    type: "premium",
    year: "2024",
    country: "China",
    duration: "1h 10m",
    synopsis: "Witness the brave boy who begins the journey to seek his father"
  },
    {
    id: "jokiii",
    title: "JOKHIM",
    poster: "https://i.pinimg.com/736x/2e/9f/45/2e9f4590cc318a0cab0fab544ce46c21.jpg",
    video: "https://drive.google.com/file/d/19mAxVZTkrUYYlOB--dqfl07SVtaPJeje/view",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "2h 10m",
    synopsis: "A gripping tale of power, revenge, and destiny with super action."
  },
  {
    id: "joki2ii",
    title: "JOKHIM 2",
    poster: "https://i.pinimg.com/736x/2e/9f/45/2e9f4590cc318a0cab0fab544ce46c21.jpg",
    video: "https://drive.google.com/file/d/1K5WonMkrcyfAP2vgsT8cgMeHHncWZwoR/view",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1h 10m",
    synopsis: "A gripping tale of power, revenge, and destiny with super action."
  },
 {
    id: "Kabhi",
    title: "Kabhi Khushi kabhie gham",
    poster: "https://i.ebayimg.com/images/g/1CcAAOSwVztf21HK/s-l1200.jpg",
    video: "https://www.youtube.com/embed/v87G_3O6TGc",
    type: "free",
    year: "2025",
    country: "India",
    duration: "1h 10m",
    synopsis: "Rahul, the adoptive son of business magnate Yash Raichand, feels eternal gratitude to his father for rescuing him from a life of poverty. Yet, when Yash forbids his love for poor Anjali, Rahul marries her and moves to London with new wife and sister-in-law, Pooja breaking the heart of his mother. Ten years later, Rahul's younger brother comes to London intent on brokering peace between father and son."
  },
   {
    id: "Kabhi2",
    title: "Kabhi Khushi kabhie gham 2",
    poster: "https://i.ebayimg.com/images/g/1CcAAOSwVztf21HK/s-l1200.jpg",
    video: "https://www.youtube.com/embed/f9oQblpb8Es",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1h 10m",
    synopsis: "Rahul, the adoptive son of business magnate Yash Raichand, feels eternal gratitude to his father for rescuing him from a life of poverty. Yet, when Yash forbids his love for poor Anjali, Rahul marries her and moves to London with new wife and sister-in-law, Pooja breaking the heart of his mother. Ten years later, Rahul's younger brother comes to London intent on brokering peace between father and son."
  },
    {
    id: "Kabhi33",
    title: "Kabhi Khushi kabhie gham 3",
    poster: "https://i.ebayimg.com/images/g/1CcAAOSwVztf21HK/s-l1200.jpg",
    video: "https://drive.google.com/file/d/1JgDzesiK6zdXODUDcR73jLJ5-hjFYx3R/preview",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1h 10m",
    synopsis: "Rahul, the adoptive son of business magnate Yash Raichand, feels eternal gratitude to his father for rescuing him from a life of poverty. Yet, when Yash forbids his love for poor Anjali, Rahul marries her and moves to London with new wife and sister-in-law, Pooja breaking the heart of his mother. Ten years later, Rahul's younger brother comes to London intent on brokering peace between father and son."
  },
    {
    id: "slaxxjeans",
    title: "KILLER JEANS",
    poster: "https://upload.wikimedia.org/wikipedia/en/thumb/8/80/Slaxx.jpg/250px-Slaxx.jpg",
    video: "https://www.youtube.com/embed/WtXTEOyfIDs",
    type: "premium",
    year: "2025",
    country: "USA",
    duration: "1h 30m",
    synopsis: "Libby McClean, a teenager who works as a salesgirl, must stop a pair of demonic jeans from killing the staff of a clothing store."
  },
  {
    id: "koyla1",
    title: "FIRE",
    poster: "https://cdn.cinematerial.com/p/136x/ttnsrduu/koyla-key-art-sm.jpg?v=1572983976",
    video: "https://drive.google.com/file/d/11kx2CItNZIkmSGSRVQEQg8_zXJA_hIDL/view",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1hr 15m",
    synopsis: "Silenced by a piece of smouldering coal in childhood, Shanker endures a life of slavery until love compels him to seek his voice, freedom, and long-overdue revenge."
  }
];
