const MOVIES = [
   {
    id: "josniper",
    title: "JOHN SNIPER",
    poster: "https://i.ibb.co/ynnpd3s4/urwjkjjd.jpg",
    video: "https://www.youtube.com/embed/EgchGwvEUEY",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1h 05m",
    synopsis: "John, an assassin, is filled with remorse after killing a family and decides to mend his ways. However, when his wife is kidnapped, he is forced to return to the criminal world one last time."
  },
   {
    id: "josnipe22r",
    title: "JOHN SNIPER 2",
    poster: "https://i.ibb.co/Q7vBC05R/nbvvf.jpg",
    video: "https://www.youtube.com/embed/I-oTe4htS6A",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1h 05m",
    synopsis: "John, an assassin, is filled with remorse after killing a family and decides to mend his ways. However, when his wife is kidnapped, he is forced to return to the criminal world one last time."
  },
  {
  
    id: "thesoft",
    title: "The SOFT and the SOLID",
    poster: "https://i.ibb.co/XfPD63kq/Untitled-1.jpg",
    video: "https://www.youtube.com/embed/I5qARzHbjGU",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 45m",
    synopsis: "Bangkok-based Johnny engages in a treachery that his employer, Ramona, witnesses. She blackmails him into killing a girl, Tanya, but suddenly something unexpected happens."
  },
    {
    id: "underdtree",
    title: "UNDER THE TREE",
    poster: "https://i.ibb.co/DPQGhfgn/Untitled-1.jpg",
    video: "https://www.youtube.com/embed/dazxm7NXbqQ",
    type: "free",
    year: "2026",
    country: "Japan",
    duration: "1h 15m",
    synopsis: "A mysterious drama unfolding beneath an ancient tree."
  },

      {
    id: "sankat1",
    title: "SANKAT",
    poster: "https://upload.wikimedia.org/wikipedia/hi/b/b9/%E0%A4%95%E0%A5%81%E0%A4%9B_%E0%A4%A4%E0%A5%8B_%E0%A4%B9%E0%A5%88.jpg",
    video: "https://drive.google.com/file/d/1A4UJn5OgPowpBPpJlZH6_g1Uk-UGgJrr/preview",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1h 05m",
    synopsis: "A group of college students face a tragedic semister when they enter a weird professor's house "
  },  
    {
    id: "high11",
    title: "HIGH",
    poster: "https://i.ibb.co/8nBd8jMb/Untitled-1-Recovered-Recovered-Recovered.jpg",
    video: "https://www.youtube.com/embed/TUCxNR97Grs",
    type: "free",
    year: "2026",
    country: "USA",
    duration: "1h 05m",
    synopsis: " This is a tense, vertigo-inducing survival thriller where best friends Becky and Hunter get trapped 2,000 feet up on an abandoned radio tower in the Mojave Desert. After the ladder breaks, they must endure extreme dehydration, vultures, and dwindling supplies to surviv "
  },  
   {
    id: "high12",
    title: "HIGH 2",
    poster: "https://i.ibb.co/8nBd8jMb/Untitled-1-Recovered-Recovered-Recovered.jpg",
    video: "https://www.youtube.com/embed/1pFTyO1zLHk",
    type: "premium",
    year: "2026",
    country: "USA",
    duration: "1h 05m",
    synopsis: " This is a tense, vertigo-inducing survival thriller where best friends Becky and Hunter get trapped 2,000 feet up on an abandoned radio tower in the Mojave Desert. After the ladder breaks, they must endure extreme dehydration, vultures, and dwindling supplies to surviv "
  },  
       {
    id: "sankat2",
    title: "SANKAT 2",
    poster: "https://upload.wikimedia.org/wikipedia/hi/b/b9/%E0%A4%95%E0%A5%81%E0%A4%9B_%E0%A4%A4%E0%A5%8B_%E0%A4%B9%E0%A5%88.jpg",
    video: "https://drive.google.com/file/d/1XYpU_XPn-GWQBXBIG52UMq2uHRgCP_lD/preview",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 15m",
    synopsis: "what happens next when A group of college students face a tragedic semister when they enter a weird professor's house "
  },
  {
    id: "kanor1",
    title: "KANOR",
    poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMJaDNTnLw5P20536cEoRL77HFeQ4dAlm2zQ&s",
    video: "https://www.youtube.com/embed/p31wdNO5ibQ",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1h 25m",
    synopsis: "Sameer Mehra (Emraan Hashmi), an ad executive, takes shelter at a remote mountain home during a snowstorm. He is forced to participate in a psychological game of mock trial conducted by retired legal professionals—including Lateef Zaidi (Amitabh Bachchan)—who scrutinize his past crimes. "
  }, 
    {
    id: "kanor2",
    title: "KANOR",
    poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMJaDNTnLw5P20536cEoRL77HFeQ4dAlm2zQ&s",
    video: "https://www.youtube.com/embed/kZJHntZJKoI",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 25m",
    synopsis: "What happens next executive  takes shelter at a remote mountain home during a snowstorm and He is forced to participate in a psychological game of mock trial conducted by retired legal professionals—including Lateef Zaidi (Amitabh Bachchan)—who scrutinize his past crimes. "
  }, 
  {
    id: "bob1",
    title: "BOB",
    poster: "https://i.ibb.co/wZLWXscX/Untitled-1.jpg",
    video: "https://drive.google.com/file/d/15TOiFNFoEWGAVoGp_ruUIa9NQ6TX5jE-/preview",
    type: "free",
    year: "2026",
    country: "China",
    duration: "1h 12m",
    synopsis: "One ordinary day, Bob follows his instincts and trails two suspicious-looking men into an alley. When he realizes they are robbing a bank, Bei jumps into action and foils their plans. The resulting publicity brings Bei the shock that his parents were both professional spies. Drawn into a dangerous game of cat and mouse, Bei travels to Turkey to stop a group of evil drug lords."
  },   
    {
    id: "bob2",
    title: "BOB 2",
    poster: "https://i.ibb.co/wZLWXscX/Untitled-1.jpg",
    video: "https://drive.google.com/file/d/1J-xjvKCz4OmyXi9UUj6vpgwbea3zulnE/preview",
    type: "premium",
    year: "2026",
    country: "China",
    duration: "1h 12m",
    synopsis: "One ordinary day, Bob follows his instincts and trails two suspicious-looking men into an alley. When he realizes they are robbing a bank, Bei jumps into action and foils their plans. The resulting publicity brings Bei the shock that his parents were both professional spies. Drawn into a dangerous game of cat and mouse, Bei travels to Turkey to stop a group of evil drug lords."
  },  
      {
    id: "pickup",
    title: "THE PICK UP",
    poster: "https://upload.wikimedia.org/wikipedia/en/d/d8/The_Pickup_2025_poster.jpg",
    video: "https://drive.google.com/file/d/16HV04cwCCsGbkhrJIATzHb_CKIw4bU6f/view",
    type: "premium",
    year: "2026",
    country: "USA",
    duration: "1h 12m",
    synopsis: "A routine cash pickup takes a wild turn when two mismatched armored truck drivers get ambushed by ruthless criminals. As chaos unfolds around them, the unlikely duo must navigate high-risk danger, clashing personalities, and one very bad day that keeps getting worse."
  },  
        {
    id: "rwanda",
    title: "HOTEL RWANDA",
    poster: "https://m.media-amazon.com/images/I/61jbFFhqOvL.jpg",
    video: "https://drive.google.com/file/d/1BYv48hR77jxOHvZWjuHKlc7OH5lIN1kr/preview",
    type: "free",
    year: "2026",
    country: "Rwanda",
    duration: "1h 12m",
    synopsis: "Hutu Paul Rusesabagina manages the Hôtel des Mille Collines and lives a happy life with his Tutsi wife and their three children, but when Hutu military forces initiate a campaign of ethnic cleansing against the Tutsi minority, Paul is compelled to allow refugees to take shelter in his hotel. As the U.N. pulls out, Paul must struggle alone to protect the Tutsi refugees in the face of the escalating violence later known as the Rwandan genocide."
  },  
          {
    id: "vault1",
    title: "THE VAULT",
    poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzmPDqOkNsLCDfyHpD_Oq4qGFdnVbkTyVEviWy95hoAERvf9_DFoXxy3oreah_jrMoKHIN&s=10",
    video: "https://drive.google.com/file/d/1svKcGMOXcy2b9NQXYLqLF9Xs0jdNARq5/preview",
    type: "premium",
    year: "2025",
    country: "USA",
    duration: "1h 10m",
    synopsis: "a high-stakes heist thriller about a genius engineering graduate, Thom (Freddie Highmore), who joins a crew led by Walter (Liam Cunningham) to rob the famously impenetrable Bank of Spain"
  },  
            {
    id: "vault2",
    title: "THE VAULT 2",
    poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkYkw0RY3VkZlFjS_7gPL8UL1ucoL1PfYPcA&s",
    video: "https://drive.google.com/file/d/1roGhWKYNuGhti1FFb1aQq7Ov0332ZQhS/preview",
    type: "premium",
    year: "2025",
    country: "USA",
    duration: "1h 20m",
    synopsis: "a high-stakes heist thriller about a genius engineering graduate, Thom (Freddie Highmore), who joins a crew led by Walter (Liam Cunningham) to rob the famously impenetrable Bank of Spain"
  },  
              {
    id: "thousand",
    title: "TEN THOUSAND YEARS BACK",
    poster: "https://image.tmdb.org/t/p/original/5XNthY4hzdKD2QxnlXbzIFYbtw6.jpg",
    video: "https://drive.google.com/file/d/1ZvJewP1LQxzjuxfcjbZ1zzO2V8Imthb-/preview",
    type: "premium",
    year: "2024",
    country: "Taiwan",
    duration: "1h 20m",
    synopsis: "A handsome Prince from the Qin dynasty travels into the future, and meets a bossy girl. the two madly fall in love"
  },  
             {
    id: "400",
    title: "400 BULLETS",
    poster: "https://a.ltrbxd.com/resized/film-poster/7/0/6/9/7/8/706978-400-bullets-0-230-0-345-crop.jpg?v=26211e223b",
    video: "https://www.youtube.com/embed/JCh54UGPqFA",
    type: "free",
    year: "2026",
    country: "USA",
    duration: "1h 30m",
    synopsis: "Two soldiers in Afghanistan face off against a group of rogue special ops and a cell of heavily armed Taliban"
  },  
 
              {
    id: "cabin",
    title: "CABIN IN THE WOODS",
    poster: "https://posterspy.com/wp-content/uploads/2022/11/cabin-posterspy-Ygris.jpg",
    video: "https://drive.google.com/file/d/1n-Er3F4oPUmt0lWh8d4on--rltB45K3m/preview",
    type: "premium",
    year: "2022",
    country: "USA",
    duration: "1h 40m",
    synopsis: "When five college friends (Kristen Connolly, Chris Hemsworth, Anna Hutchison, Fran Kranz, Jesse Williams) arrive at a remote forest cabin for a little vacation, little do they expect the horrors that await them. One by one, the youths fall victim to backwoods zombies, but there is another factor at play. Two scientists (Richard Jenkins, Bradley Whitford) are manipulating the ghoulish goings-on, but even as the body count rises, there is yet more at work than meets the eye."
  },
    {
    id: "chautal1",
    title: "CHAUTALA",
    poster: "https://st1.bollywoodlife.com/wp-content/uploads/2024/07/1-37.png?impolicy=Medium_Widthonly&w=400&h=711",
    video: "https://www.youtube.com/embed/9OK326dtdMA",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 10m",
    synopsis: "Hindi thriller following four friends—Dev, Devi, Gaurav, and Aditya—whose carefree lives are ruined when they encounter a corrupt, ruthless police officer, SHO Chautala. After an incident involving a local shopkeeper, the friends are blackmailed and framed, forcing them to fight against the system. ."
  },
      {
    id: "chautal2",
    title: "CHAUTALA",
    poster: "https://st1.bollywoodlife.com/wp-content/uploads/2024/07/1-37.png?impolicy=Medium_Widthonly&w=400&h=711",
    video: "https://www.youtube.com/embed/v7bnBboesXM",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 35m",
    synopsis: "Hindi thriller following four friends—Dev, Devi, Gaurav, and Aditya—whose carefree lives are ruined when they encounter a corrupt, ruthless police officer, SHO Chautala. After an incident involving a local shopkeeper, the friends are blackmailed and framed, forcing them to fight against the system. ."
  },
    {
    id: "chattan11",
    title: "CHATTAN",
    poster: "https://bollyspice.com/wp-content/uploads/2018/07/Satyameva-Jayate.jpeg",
    video: "https://drive.google.com/file/d/1AdYRASlD0LJQEAF-Wy1-5CZ692cVcWsP/view",
    type: "free",
    year: "2025",
    country: "India",
    duration: "1h 15m",
    synopsis: "Kabir Ahlawat, a quiet, reclusive pawn shop owner in Goa with a dark past as an undercover agent. When his young, neglected neighbor, Naomi, is kidnapped by a drug-and-organ-trafficking mafia, Kabir unleashes a violent, one-man army revenge spree to save her."
  },
      {
    id: "chattan1221",
    title: "CHATTAN 2",
    poster: "https://bollyspice.com/wp-content/uploads/2018/07/Satyameva-Jayate.jpeg",
    video: "https://drive.google.com/file/d/1P0ci6zuE9pwJUOgEkGkcDmKVSR8lGhMb/view",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1h 15m",
    synopsis: "Kabir Ahlawat, a quiet, reclusive pawn shop owner in Goa with a dark past as an undercover agent. When his young, neglected neighbor, Naomi, is kidnapped by a drug-and-organ-trafficking mafia, Kabir unleashes a violent, one-man army revenge spree to save her."
  },
     {
    id: "unstoppable",
    title: "UNSTOPABLE ROBOT",
    poster: "https://m.media-amazon.com/images/M/MV5BNDdhMWExMTItOTNiNy00MDgxLWIyMDktNjYxNWU3ZGFjM2IyXkEyXkFqcGc@._V1_.jpg",
    video: "https://www.youtube.com/embed/3TXDJLd6w2Q",
    type: "free",
    year: "2019",
    country: "China",
    duration: "1h 30m",
    synopsis: "When robots take over the city of Hong Kong, one ultmate Robot with a sense of understanding must come forward to fight the battle"
  },  
       {
    id: "cure1",
    title: "THE CURE",
    poster: "https://m.media-amazon.com/images/M/MV5BNjg1ZDdlMGItYzM3NS00NGQwLWE4ZWQtYTA1YjY1MjQ2YzViXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    video: "https://player.vimeo.com/video/746868048",
    type: "free",
    year: "2019",
    country: "USA",
    duration: "30m",
    synopsis: "Noah, a mercenary in a post-apocalyptic world where a virus kills hosts within 24 hours. When a permanent cure is stolen, Noah must retrieve it to save his infected daughter, facing intense, high-octane gunfights, vehicular carnage, and explosions against a terrorist organization"
  },  
         {
    id: "cure2",
    title: "THE CURE 2",
    poster: "https://m.media-amazon.com/images/M/MV5BNjg1ZDdlMGItYzM3NS00NGQwLWE4ZWQtYTA1YjY1MjQ2YzViXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    video: "https://drive.google.com/file/d/1b0fMqvvrR8qtQLC5wVT_BReqx4swlv_T/preview",
    type: "premium",
    year: "2019",
    country: "USA",
    duration: "40m",
    synopsis: "Noah, a mercenary in a post-apocalyptic world where a virus kills hosts within 24 hours. When a permanent cure is stolen, Noah must retrieve it to save his infected daughter, facing intense, high-octane gunfights, vehicular carnage, and explosions against a terrorist organization"
  },  
            {
    id: "jamu",
    title: "JAM",
    poster: "https://www.punjabnewsexpress.com/images/article/article206579.jpg",
    video: "https://www.youtube.com/embed/R0c3hy6Euok",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 55m",
    synopsis: " Hindi-language emotional thriller directed by the late Rajesh Pillai, featuring an ensemble cast led by Manoj Bajpayee, Jimmy Sheirgill, Prosenjit Chatterjee, and Divya Dutta. It is a remake of the 2011 Malayalam film of the same name and is inspired by a real-life incident in Chennai where a heart was transported for a transplant."
  },
  {
    id: "titanic",
    title: "TITANIC",
    poster: "https://play-lh.googleusercontent.com/8PmJGVmFtEYVrnjcEvHr2Zl0bMYtjufSxmTBXb87NN7VF16lBr4bD4mUFV5Ae0uQ52-yLp1pdBF7NuOUtm4",
    video: "https://vimeo.com/862818999",
    type: "premium",
    year: "2020",
    country: "USA",
    duration: "1h 20m",
    synopsis: "James Camerons Titanic is an epic romance and disaster film following Rose DeWitt Bukater, a 17-year-old aristocrat, who falls for Jack Dawson , a poor artist, aboard the ill-fated 1912 maiden voyage of the RMS Titanic. Their forbidden love story unfolds against the backdrop of the sinking ship"
  }, 
  {
    id: "titanic2",
    title: "TITANIC 2",
    poster: "https://play-lh.googleusercontent.com/8PmJGVmFtEYVrnjcEvHr2Zl0bMYtjufSxmTBXb87NN7VF16lBr4bD4mUFV5Ae0uQ52-yLp1pdBF7NuOUtm4",
    video: "https://vimeo.com/863044892",
    type: "premium",
    year: "2020",
    country: "USA",
    duration: "1h 30m",
    synopsis: "James Camerons Titanic is an epic romance and disaster film following Rose DeWitt Bukater, a 17-year-old aristocrat, who falls for Jack Dawson , a poor artist, aboard the ill-fated 1912 maiden voyage of the RMS Titanic. Their forbidden love story unfolds against the backdrop of the sinking ship"
  },  
    {
    id: "tayitanic3",
    title: "TITANIC 3",
    poster: "https://play-lh.googleusercontent.com/8PmJGVmFtEYVrnjcEvHr2Zl0bMYtjufSxmTBXb87NN7VF16lBr4bD4mUFV5Ae0uQ52-yLp1pdBF7NuOUtm4",
    video: "https://vimeo.com/863605809",
    type: "premium",
    year: "2020",
    country: "USA",
    duration: "1h 30m",
    synopsis: "James Camerons Titanic is an epic romance and disaster film following Rose DeWitt Bukater, a 17-year-old aristocrat, who falls for Jack Dawson , a poor artist, aboard the ill-fated 1912 maiden voyage of the RMS Titanic. Their forbidden love story unfolds against the backdrop of the sinking ship"
  }, 
      {
    id: "brant23",
    title: "BRANT",
    poster: "https://play-lh.googleusercontent.com/8PmJGVmFtEYVrnjcEvHr2Zl0bMYtjufSxmTBXb87NN7VF16lBr4bD4mUFV5Ae0uQ52-yLp1pdBF7NuOUtm4",
    video: "https://drive.google.com/file/d/1BipH5Qsg-k8Ah_DP1P0iVU9HE-6KfQyp/view",
    type: "premium",
    year: "2023",
    country: "USA",
    duration: "1h 40m",
    synopsis: "When Jason Stantham appears, what do you expect? Super action movie"
  }, 
        {
    id: "brant2",
    title: "BRANT PART 2",
    poster: "https://play-lh.googleusercontent.com/8PmJGVmFtEYVrnjcEvHr2Zl0bMYtjufSxmTBXb87NN7VF16lBr4bD4mUFV5Ae0uQ52-yLp1pdBF7NuOUtm4",
    video: "https://drive.google.com/file/d/1wURAFpDI9N9MAA-ITigYhQP_dIjQzGme/view",
    type: "premium",
    year: "2023",
    country: "USA",
    duration: "1h 10m",
    synopsis: "When Jason Stantham appears, what do you expect? Super action blockbuster movie"
  },
             {
    id: "wwowo",
    title: "WOLF WORRIOR",
    poster: "https://i.ibb.co/j9bnDgPG/images-5.jpg",
    video: "https://drive.google.com/file/d/1wURAFpDI9N9MAA-ITigYhQP_dIjQzGme/view",
    type: "free",
    year: "2019",
    country: "China",
    duration: "1h 30m",
    synopsis: "A special forces soldier, known for his marksmanship, must battle a group of foreign mercenaries hired to slay him by a drug lord"
  },
          {
    id: "faithcabin",
    title: "FAITH CABIN",
    poster: "https://m.media-amazon.com/images/M/MV5BN2I0NjlkYjgtMWU5Mi00NGYwLThjNTYtMzM1MGI2ZTQ3OTIyXkEyXkFqcGc@._V1_.jpg",
    video: "https://www.youtube.com/embed/7EV1XVz7dA4",
    type: "free",
    year: "2025",
    country: "USA",
    duration: "1h 20m",
    synopsis: "After suffering a family tragedy, Mack Phillips spirals into a deep depression that causes him to question his innermost beliefs. Facing a crisis of faith, he receives a mysterious letter urging him to an abandoned shack in the Oregon wilderness. Despite his doubts, Mack journeys to the shack and encounters an enigmatic trio of strangers led by a woman named Papa. Through this meeting, Mack finds important truths that will transform his understanding of his tragedy and change his life forever"
  },
            {
    id: "faithcabin2",
    title: "FAITH CABIN 2",
    poster: "https://m.media-amazon.com/images/M/MV5BN2I0NjlkYjgtMWU5Mi00NGYwLThjNTYtMzM1MGI2ZTQ3OTIyXkEyXkFqcGc@._V1_.jpg",
    video: "https://www.youtube.com/embed/F25D62Y-Q44",
    type: "premium",
    year: "2025",
    country: "USA",
    duration: "1h 20m",
    synopsis: "After suffering a family tragedy, Mack Phillips spirals into a deep depression that causes him to question his innermost beliefs. Facing a crisis of faith, he receives a mysterious letter urging him to an abandoned shack in the Oregon wilderness. Despite his doubts, Mack journeys to the shack and encounters an enigmatic trio of strangers led by a woman named Papa. Through this meeting, Mack finds important truths that will transform his understanding of his tragedy and change his life forever"
  },
  {
    id: "warship11",
    title: "WAR SHIP",
    poster: "https://m.media-amazon.com/images/M/MV5BYmQzNWM2NTEtNGU2Yi00MmVlLWE5MWItMGE1M2ZlNzI0Y2Y5XkEyXkFqcGc@._V1_.jpg",
    video: "https://www.youtube.com/embed/x38i6jZnuWk",
    type: "free",
    year: "2025",
    country: "USA",
    duration: "1h 10m",
    synopsis: "another beautiful movie to take away your stress"
  },
  {
    id: "warship12",
    title: "WAR SHIP 2",
    poster: "https://m.media-amazon.com/images/M/MV5BYmQzNWM2NTEtNGU2Yi00MmVlLWE5MWItMGE1M2ZlNzI0Y2Y5XkEyXkFqcGc@._V1_.jpg",
    video: "https://www.youtube.com/embed/RLb5iXT3Udo",
    type: "premium",
    year: "2025",
    country: "USA",
    duration: "1h 10m",
    synopsis: "another beautiful movie to take away your stress"
  },
  {
    id: "amanni",
    title: "AMANI",
    poster: "https://static.titlovi.com/img/0228/228698-tt0234000.jpg",
    video: "https://www.youtube.com/embed/D2vaZ6yOfg4",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 10m",
    synopsis: "Laba film eno olabe omukwano gwa brother bweguba. Oluvanyuma lwokwekalakasa okwali ku kyalo, omwafiira abavubuka amakumi ataano, Amani yabula, wabula Mwanyina anasobola okumuzuula?."
  },
   {
    id: "amannni",
    title: "AMANI 2",
    poster: "https://static.titlovi.com/img/0228/228698-tt0234000.jpg",
    video: "https://www.youtube.com/embed/aayEWSxngbg",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "1h 10m",
    synopsis: "Laba film eno olabe omukwano gwa brother bweguba. Oluvanyuma lwokwekalakasa okwali ku kyalo, omwafiira abavubuka amakumi ataano, Amani yabula, wabula Mwanyina anasobola okumuzuula?."
  },
     {
    id: "shoony",
    title: "SHOONY",
    poster: "https://i.ibb.co/DD367QqD/pooooo.jpg",
    video: "https://www.youtube.com/embed/n-meJRIBMQQ",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1h 10m",
    synopsis: "Dhritiman Chaterji and Catherine McNally give birth to their first daughter, Michelle  who can neither hear nor see. Not knowing how to care for a deaf and blind child, they isolate their daughter from the outside world and as a result, she is ill-behaved and emotionally distraught. Paul even considers putting Michelle in a mental hospital until an eccentric teacher with a questionable past offers to help."
  },
       {
    id: "shoonnnyyy",
    title: "SHOONY 2",
    poster: "https://i.ibb.co/DD367QqD/pooooo.jpg",
    video: "https://www.youtube.com/embed/eLPtLBbi4C8",
    type: "free",
    year: "2026",
    country: "India",
    duration: "1h 10m",
    synopsis: "Dhritiman Chaterji and Catherine McNally give birth to their first daughter, Michelle  who can neither hear nor see. Not knowing how to care for a deaf and blind child, they isolate their daughter from the outside world and as a result, she is ill-behaved and emotionally distraught. Paul even considers putting Michelle in a mental hospital until an eccentric teacher with a questionable past offers to help."
  },
       {
    id: "greaterwall",
    title: "THE GREAT WALL",
    poster: "https://m.media-amazon.com/images/M/MV5BMjA3MjAzOTQxNF5BMl5BanBnXkFtZTgwOTc5OTY1OTE@._V1_.jpg",
    video: "https://drive.google.com/file/d/1PFWXmSzfR2K21QZyqo3cvxDg3WyvSach/preview",
    type: "premium",
    year: "2024",
    country: "China",
    duration: "1h 40m",
    synopsis: "When a mercenary warrior is imprisoned within the Great Wall, he discovers the mystery behind one of the greatest wonders of the world. As wave after wave of marauding beasts besiege the massive structure, his quest for fortune turns into a journey toward heroism as he joins a huge army of elite warriors to confront the unimaginable and seemingly unstoppable force."
  },
         {
    id: "greaterwalls",
    title: "THE GREAT WALL 2",
    poster: "https://m.media-amazon.com/images/M/MV5BMjA3MjAzOTQxNF5BMl5BanBnXkFtZTgwOTc5OTY1OTE@._V1_.jpg",
    video: "https://drive.google.com/file/d/1YgT9geArNCQvxDq20xgUv3PtOtRarMBB/preview",
    type: "premium",
    year: "2024",
    country: "China",
    duration: "1h 40m",
    synopsis: "When a mercenary warrior is imprisoned within the Great Wall, he discovers the mystery behind one of the greatest wonders of the world. As wave after wave of marauding beasts besiege the massive structure, his quest for fortune turns into a journey toward heroism as he joins a huge army of elite warriors to confront the unimaginable and seemingly unstoppable force."
  },
           {
    id: "mugaya",
    title: "MUGAYA",
    poster: "https://i.ibb.co/4ZJTjPrg/Sausage-Party-Foodtopia-poster.jpg",
    video: "https://vimeo.com/862223837",
    type: "premium",
    year: "2024",
    country: "China",
    duration: "1h 40m",
    synopsis: "Eno entyuni ekulaga nti sigwe wekka alina ebizibu, ensi yona elina enaku."
  },
         {
    id: "poolhorror",
    title: "POOL",
    poster: "https://m.media-amazon.com/images/I/71GP9nsSFsL._AC_UF894,1000_QL80_.jpg",
    video: "https://drive.google.com/file/d/12W095GJfn1rh1OKpS8XKFbUZQ5ujtJHY/preview",
    type: "premium",
    year: "2024",
    country: "Thailand",
    duration: "1h 40m",
    synopsis: "Deyi, is left alone to clear up a 6-meter deep deserted pool after shooting a film. He is really tired and falls asleep on an inflatable raft. When he wakes up again the water level has sunk so low that he cannot climb out of the pool on his own."
  },
           {
    id: "misota",
    title: "RISING BOARS",
    poster: "https://m.media-amazon.com/images/M/MV5BMGU4ZTU2N2YtYTM2NC00YTRiLWFkODktYWMyY2Q5NmM4NzUxXkEyXkFqcGc@._V1_.jpg",
    video: "https://drive.google.com/file/d/1Zh2xXKVQMku8O8ppRd6pMk2QVVK93sXO/preview",
    type: "premium",
    year: "2024",
    country: "Thailand",
    duration: "1h 40m",
    synopsis: "The mutated, ginormous boa and a horde of smaller, aggressive, venomous snakes escape from the breeding base. The snakes head to a nearby flight attendant aviation college, which is preparing for a graduation ceremony and competition."
  },
       {
    id: "calledman",
    title: "MAN CALLED HERO",
    poster: "https://pic0.iqiyipic.com/image/20250728/00/ed/v_165631021_m_601_en_m1_260_360.jpg",
    video: "https://drive.google.com/file/d/1f2eYbmrIMuXCnv7cFholzmKNhJ84ydLF/preview",
    type: "premium",
    year: "2024",
    country: "China",
    duration: "1h 40m",
    synopsis: "A martial arts expert flees to New York after carrying out a violent vendetta against his parents murderers. Sixteen years later, the man must repay a debt of honour to the people whom he has wronged."
  },
   {
    id: "midnightsunn",
    title: "MIDNIGHT SUN",
    poster: "https://i.pinimg.com/736x/96/5c/c8/965cc8bdbd8562d1c96259bc7715d177.jpg",
    video: "https://vimeo.com/786472139",
    type: "premium",
    year: "2024",
    country: "USA",
    duration: "1h 30m",
    synopsis: "a romantic drama starring Bella Thorne as Katie Price, a 17-year-old with a rare, fatal, sunlight-sensitive disease XP. Confined to her home during the day, she meets her long-time crush, Charlie Patrick Schwarzenegger, at night, sparking a fleeting summer romance while trying to hide her condition"
  },
   {
    id: "wolf200",
    title: "200 WOLF",
    poster: "https://i.ibb.co/tPqBwKvq/werewolf.jpg",
    video: "https://drive.google.com/file/d/1Rkszg7K3q04q9ULpppQ6TFjmRIE_Qn_u/preview",
    type: "premium",
    year: "2024",
    country: "USA",
    duration: "1h 30m",
    synopsis: "Heroic Freddy has everything it takes to lead a pack... except the appearance. But his wayward wish to transform from a poodle to a werewolf will finally come true with the help of a mischievous moon sprite that reached Earth"
  },
   {
    id: "wobear",
    title: "PANDA BEAR",
    poster: "https://m.media-amazon.com/images/M/MV5BNGI3YWFkMWEtZTZjNS00NWI1LThiYWEtZDBlZDg4NWRjMzcxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    video: "https://drive.google.com/file/d/1e3Ro2fUxWrEbsLVXjnrj7-C4EQtEOmoU/preview",
    type: "premium",
    year: "2025",
    country: "USA",
    duration: "1h 50m",
    synopsis: "Mpanga is a young panda who grows up in an idyllic village in the heart of China. But when her best friend, Jielong the dragoness, is kidnapped to be offered as a gift to a capricious young lion king, Pang leaves for Africa to save her friend"
  },
     {
    id: "litomermaid",
    title: "LITTLE MERMAID",
    poster: "https://m.media-amazon.com/images/M/MV5BNGI3YWFkMWEtZTZjNS00NWI1LThiYWEtZDBlZDg4NWRjMzcxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    video: "https://drive.google.com/file/d/1bQLNf9gI4aHTbfohmAARUsiyYZS0Z-vk/preview",
    type: "premium",
    year: "2024",
    country: "USA",
    duration: "1h 50m",
    synopsis: "rebellious 16 year-old mermaid Ariel is fascinated with life on land. On one of her visits to the surface, which are forbidden by her controlling father, King Triton, she falls for a human prince. Determined to be with her new love, Ariel makes a dangerous deal with the sea witch Ursula to become human for three days. But when plans go awry for the star-crossed lovers, the king must make the ultimate sacrifice for his daughter"
  },
      {
    id: "lito2mermaid",
    title: "LITTLE MERMAID 2",
    poster: "https://m.media-amazon.com/images/M/MV5BNGI3YWFkMWEtZTZjNS00NWI1LThiYWEtZDBlZDg4NWRjMzcxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    video: "https://drive.google.com/file/d/18iDi6gFCHnpDnaWjdtObuK5V8HwjzWjA/preview",
    type: "premium",
    year: "2024",
    country: "USA",
    duration: "1h 10m",
    synopsis: "rebellious 16 year-old mermaid Ariel is fascinated with life on land. On one of her visits to the surface, which are forbidden by her controlling father, King Triton, she falls for a human prince. Determined to be with her new love, Ariel makes a dangerous deal with the sea witch Ursula to become human for three days. But when plans go awry for the star-crossed lovers, the king must make the ultimate sacrifice for his daughter"
  },
        {
    id: "jorneybeijing1",
    title: "JOURNEY TO BEIJING",
    poster: "https://m.media-amazon.com/images/M/MV5BNzhhMmQ2YTUtMzFlZi00OWNmLWJmYjMtZjYyODE1YTAxMGZmXkEyXkFqcGc@._V1_.jpg",
    video: "https://drive.google.com/file/d/1ZOOo0ozWvk7wYR8NZQwZP-_B-zabKuLK/preview",
    type: "premium",
    year: "2024",
    country: "China",
    duration: "1h 10m",
    synopsis: "Witness the brave boy who begins the journey to seek his father"
  },
        {
    id: "jorneybeiji22ng1",
    title: "JOURNEY TO BEIJING 2",
    poster: "https://m.media-amazon.com/images/M/MV5BNzhhMmQ2YTUtMzFlZi00OWNmLWJmYjMtZjYyODE1YTAxMGZmXkEyXkFqcGc@._V1_.jpg",
    video: "https://drive.google.com/file/d/1L_AWefNfMmECY_vtZdxycpb7BvQ6naYb/preview",
    type: "premium",
    year: "2024",
    country: "China",
    duration: "1h 10m",
    synopsis: "Witness the brave boy who begins the journey to seek his father"
  },
    {
    id: "jokiii",
    title: "JOKHIM",
    poster: "https://i.pinimg.com/736x/2e/9f/45/2e9f4590cc318a0cab0fab544ce46c21.jpg",
    video: "https://drive.google.com/file/d/19mAxVZTkrUYYlOB--dqfl07SVtaPJeje/view",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "2h 10m",
    synopsis: "A gripping tale of power, revenge, and destiny with super action."
  },
  {
    id: "joki2ii",
    title: "JOKHIM 2",
    poster: "https://i.pinimg.com/736x/2e/9f/45/2e9f4590cc318a0cab0fab544ce46c21.jpg",
    video: "https://drive.google.com/file/d/1K5WonMkrcyfAP2vgsT8cgMeHHncWZwoR/view",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1h 10m",
    synopsis: "A gripping tale of power, revenge, and destiny with super action."
  },
 {
    id: "Kabhi",
    title: "Kabhi Khushi kabhie gham",
    poster: "https://i.ebayimg.com/images/g/1CcAAOSwVztf21HK/s-l1200.jpg",
    video: "https://www.youtube.com/embed/v87G_3O6TGc",
    type: "free",
    year: "2025",
    country: "India",
    duration: "1h 10m",
    synopsis: "Rahul, the adoptive son of business magnate Yash Raichand, feels eternal gratitude to his father for rescuing him from a life of poverty. Yet, when Yash forbids his love for poor Anjali, Rahul marries her and moves to London with new wife and sister-in-law, Pooja breaking the heart of his mother. Ten years later, Rahul's younger brother comes to London intent on brokering peace between father and son."
  },
   {
    id: "Kabhi2",
    title: "Kabhi Khushi kabhie gham 2",
    poster: "https://i.ebayimg.com/images/g/1CcAAOSwVztf21HK/s-l1200.jpg",
    video: "https://www.youtube.com/embed/f9oQblpb8Es",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1h 10m",
    synopsis: "Rahul, the adoptive son of business magnate Yash Raichand, feels eternal gratitude to his father for rescuing him from a life of poverty. Yet, when Yash forbids his love for poor Anjali, Rahul marries her and moves to London with new wife and sister-in-law, Pooja breaking the heart of his mother. Ten years later, Rahul's younger brother comes to London intent on brokering peace between father and son."
  },
    {
    id: "Kabhi33",
    title: "Kabhi Khushi kabhie gham 3",
    poster: "https://i.ebayimg.com/images/g/1CcAAOSwVztf21HK/s-l1200.jpg",
    video: "https://drive.google.com/file/d/1JgDzesiK6zdXODUDcR73jLJ5-hjFYx3R/preview",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1h 10m",
    synopsis: "Rahul, the adoptive son of business magnate Yash Raichand, feels eternal gratitude to his father for rescuing him from a life of poverty. Yet, when Yash forbids his love for poor Anjali, Rahul marries her and moves to London with new wife and sister-in-law, Pooja breaking the heart of his mother. Ten years later, Rahul's younger brother comes to London intent on brokering peace between father and son."
  },
    {
    id: "slaxxjeans",
    title: "KILLER JEANS",
    poster: "https://upload.wikimedia.org/wikipedia/en/thumb/8/80/Slaxx.jpg/250px-Slaxx.jpg",
    video: "https://www.youtube.com/embed/WtXTEOyfIDs",
    type: "premium",
    year: "2025",
    country: "USA",
    duration: "1h 30m",
    synopsis: "Libby McClean, a teenager who works as a salesgirl, must stop a pair of demonic jeans from killing the staff of a clothing store."
  },
      {
    id: "redsky",
    title: "BLOOD RED SKY",
    poster: "https://m.media-amazon.com/images/M/MV5BMDE2YWFjNTUtZjkxOC00NDRhLTlkNDYtYmI2ZGRlYjE4MDJkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    video: "https://vimeo.com/881233399",
    type: "premium",
    year: "2024",
    country: "USA",
    duration: "1h 30m",
    synopsis: "When a group of terrorists hijacks an overnight transatlantic flight, a mysteriously ill woman must unleash a monstrous secret to protect her young son"
  },
        {
    id: "redbloodsky",
    title: "BLOOD RED SKY 2",
    poster: "https://m.media-amazon.com/images/M/MV5BMDE2YWFjNTUtZjkxOC00NDRhLTlkNDYtYmI2ZGRlYjE4MDJkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    video: "https://vimeo.com/881361105",
    type: "premium",
    year: "2024",
    country: "USA",
    duration: "1h 30m",
    synopsis: "When a group of terrorists hijacks an overnight transatlantic flight, a mysteriously ill woman must unleash a monstrous secret to protect her young son"
  },
     {
    id: "kpopdh",
    title: "KPOP Demon Hunters",
    poster: "https://i.ibb.co/chjNSDcM/KPop-Demon-Hunters.jpg",
    video: "https://drive.google.com/file/d/18vHBEBMZaRAwLuE1ScDzMufOHXD-0fa1/preview",
    type: "premium",
    year: "2025",
    country: "Korea",
    duration: "1h 30m",
    synopsis: "When K-pop superstars Rumi, Mira and Zoey aren't selling out stadiums or topping the Billboard charts, they're moonlighting as demon hunters to protect their fans from ever-present supernatural danger.."
  },
   {
    id: "fride",
    title: "FRIDAY",
    poster: "https://cdn.displate.com/artwork/857x1200/2020-12-20/ec224f724feb219872318818a60c6cf5_85d90ac479f5086a1c6d5b4c2d3e8864.jpg",
    video: "https://drive.google.com/file/d/1GmrHegKf0ctSZviQx76ssT_jCJhuAETx/preview",
    type: "premium",
    year: "2026",
    country: "USA",
    duration: "1h 30m",
    synopsis: "It's Friday and Craig Jones has just gotten fired for stealing cardboard boxes. To make matters worse, rent is due, he hates his overbearing girlfriend, Joi, and his best friend, Smokey, owes the local drug dealer money -- and that's all before lunch. As the hours drag on, Jones and Smokey experience the gamut of urban life, complete with crackheads, shoot-outs and overly sexual pastors, concentrated into one single, unbelievable Friday."
  },
   {
    id: "vvivarium",
    title: "Vivarium",
    poster: "https://i.ibb.co/DH09z844/Vivarium-film-theatrical-poster.jpg",
    video: "https://drive.google.com/file/d/1E4AJcMcDi2031tdjEtoOMRfmFV_qjT3Q/preview",
    type: "premium",
    year: "2024",
    country: "USA",
    duration: "1h 30m",
    synopsis: "sci-fi horror film where a young couple, Gemma and Tom, become trapped in a surreal, suburban labyrinth called Yonder. Forced to raise a rapidly growing, mysterious child in exchange for survival, they endure immense psychological torment as they attempt to escape the identical, inescapable houses. ."
  },
   {
    id: "emerso",
    title: "EMERSON HEIGHTS",
    poster: "https://m.media-amazon.com/images/M/MV5BZmM4YmY2ZDItZjM0My00NzViLWEyYjgtMWQ5NzM2ZTVlNTdhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    video: "https://vimeo.com/862163345",
    type: "premium",
    year: "2020",
    country: "USA",
    duration: "1h 30m",
    synopsis: "Emerson Heights is 2020 a romantic drama about Cody, an aspiring LA actor who falls for NYC-based Briley, attempting a long-distance relationship. As Cody hits stardom with a new film, their bond faces tests from fame, a seductive co-star, and pressure, forcing them to balance passion with love."
  },
   {
    id: "appo",
    title: "APOCALYPTO",
    poster: "https://i.ibb.co/xKjbFNdX/images-7.jpg",
    video: "https://drive.google.com/file/d/19kEnvObyU5YRvAQkN8IDk6CuTlvNeoJ3/preview",
    type: "premium",
    year: "2020",
    country: "USA",
    duration: "1h 30m",
    synopsis: "Set in the waning days of the Maya civilization, Apocalypto follows Jaguar Paw, a peaceful tribesman whose village is brutally raided by Mayan warriors seeking slaves and sacrifices. After hiding his pregnant wife and son in a pit, he is captured and must escape his captors and return to his family before a predicted downfall. ."
  },
 {
    id: "closerange",
    title: "CLOSE RANGE",
    poster: "https://upload.wikimedia.org/wikipedia/en/2/2a/CloseRange.Adkins.png",
    video: "https://drive.google.com/file/d/1UnXD5uFvtFkwT8zwRTEduuGxr9Ih5jVd/preview",
    type: "premium",
    year: "2020",
    country: "USA",
    duration: "1h 40m",
    synopsis: "action thriller starring Scott Adkins as Colton MacReady, a rogue soldier who rescues his niece from a Mexican drug cartel. After stealing a flash drive during the rescue, Colton and his family are besieged at their remote ranch by the cartel and a corrupt sheriff. The film focuses on intense, non-stop, close-quarters combat.  ."
  },
 {
    id: "emunduakimbo",
    title: "GUNS AKIMBO",
    poster: "https://m.media-amazon.com/images/M/MV5BYjI2MTRjMmEtYTE1Yy00Zjk2LTk1NTQtYzA4MmI2YmQyYzAyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    video: "https://vimeo.com/764859386",
    type: "premium",
    year: "2022",
    country: "USA",
    duration: "1h 40m",
    synopsis: "Miles is a video game developer who inadvertently becomes the next participant in a real-life death match that streams online. While Miles soon excels at running away from everything, that won't help him outlast Nix, a killer at the top of her game.."
  },
 {
    id: "legendhuo",
    title: "FIST OF LEGENDARY HUO",
    poster: "https://i.ibb.co/Z6QWxHkj/images-8.jpg",
    video: "https://www.youtube.com/embed/0yPM8KCMmqA",
    type: "premium",
    year: "2020",
    country: "China",
    duration: "1h 20m",
    synopsis: "A martial artist goes on a completly impossible task of revenge."
  },
 {
    id: "dylanmovie",
    title: "DYLAN",
    poster: "https://i.ibb.co/1GWpZYkh/Untitled-1.jpg",
    video: "https://www.youtube.com/embed/PAjBGKM7zxg",
    type: "premium",
    year: "2024",
    country: "USA",
    duration: "1h 20m",
    synopsis: "They all think he is a psycho"
  },
 {
    id: "chakra1",
    title: "CHAKRA",
    poster: "https://i.ibb.co/1GWpZYkh/Untitled-1.jpg",
    video: "https://vimeo.com/775159625",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1h 20m",
    synopsis: "action-thriller focusing on cybercrime, where an army officer, Major Chandru assists police officer Gayathri  in investigating a series of 50 robberies on Independence Day. The plot hinges on finding a masked hacker who stole a prestigious medal belonging to Chandru's father, leading to a battle against a mastermind. "
  },
 {
    id: "chakra22",
    title: "CHAKRA 2",
    poster: "https://i.ibb.co/1GWpZYkh/Untitled-1.jpg",
    video: "https://vimeo.com/775164855",
    type: "premium",
    year: "2025",
    country: "India",
    duration: "1h 20m",
    synopsis: "action-thriller focusing on cybercrime, where an army officer, Major Chandru assists police officer Gayathri  in investigating a series of 50 robberies on Independence Day. The plot hinges on finding a masked hacker who stole a prestigious medal belonging to Chandru's father, leading to a battle against a mastermind. "
  },
 {
    id: "driveangry",
    title: "DRIVE ANGRY",
    poster: "https://i.ibb.co/1GWpZYkh/Untitled-1.jpg",
    video: "https://drive.google.com/file/d/1VabUNOHw8JLmhgtkmE-ibSmWfqfEcDxq/view",
    type: "premium",
    year: "2024",
    country: "USA",
    duration: "1h 40m",
    synopsis: "Thrown into hell for his crimes, brutal felon John Milton escapes from the fiery pit after cultists murder his daughter and take her baby. Intent on rescuing the child, Milton joins forces with a waitress, who gives him her ex-lover's fire-red muscle car. In it, the two pursue the cult leader, who plans to sacrifice the infant and unleash hell on Earth. However, the hunters become the hunted when Satan sends his merciless henchman to drag Milton back"
  },
   {
    id: "wenifell",
    title: "When I Fell",
    poster: "https://i.ibb.co/cKvZZNT7/DGH.jpg",
    video: "https://www.youtube.com/embed/dmekuoSzha8",
    type: "premium",
    year: "2026",
    country: "USA",
    duration: "1h 30m",
    synopsis: "A gripping Story of powerful love."
  },
   {
    id: "kanor",
    title: "KANOR",
    poster: "https://i.ibb.co/Zphm4pNY/KANOR.jpg",
    video: "https://www.youtube.com/embed/p31wdNO5ibQ",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "2h 10m",
    synopsis: "A gripping tale of power, revenge, and destiny."
  },
   {
    id: "kanor",
    title: "KANOR",
    poster: "https://i.ibb.co/Zphm4pNY/KANOR.jpg",
    video: "https://www.youtube.com/embed/p31wdNO5ibQ",
    type: "premium",
    year: "2026",
    country: "India",
    duration: "2h 10m",
    synopsis: "A gripping tale of power, revenge, and destiny."
  }
];
