const SERIES = [
  
  {
    id: "tianlan",
    title: "LEGEND OF TIANLAN",
    poster: "https://horrornews.net/wp-content/uploads/2018/03/Legend-of-the-Naga-Pearls-2017-movie-Yang-Lei-6.jpg",
    genre: "Fantasy",
    added: 1,
    type: "free",
    country: "China",
    year: "2026",
    synopsis: "A legendary journey of power and destiny between exorcists.",
    cast: ["Zifeng Li", "Yang Rong", "Yang Xuwen"],
    episodes: [
      { title: "Episode 1", video: "https://www.youtube.com/embed/RlNqNyrRm_k" },
      { title: "Episode 2", video: "https://www.youtube.com/embed/egF1sy2FPYs" },
      { title: "Episode 3", video: "https://www.youtube.com/embed/UPrxaom2THM" },
      { title: "Episode 4", video: "https://www.youtube.com/embed/squJI3jzkV4" },
      { title: "Episode 5", video: "https://www.youtube.com/embed/LBrZEOj0w5o" },
      { title: "Episode 6", video: "https://www.youtube.com/embed/EjXi1_0BnzE" },
      { title: "Episode 7", video: "https://www.youtube.com/embed/mQAUHdtDbms" },
      { title: "Episode 8", video: "https://www.youtube.com/embed/KdKOBolUC_U" },
      { title: "Episode 9", video: "https://www.youtube.com/embed/fWngGIZ8ZLk" },
      { title: "Episode 10", video: "https://www.youtube.com/embed/D0Op9g37vJs" },
      { title: "Episode 11", video: "https://www.youtube.com/embed/ZKyROMmbIkI" }
]
  },
{
    id: "affairs",
    title: "AFFAIRS",
    poster: "https://pic5.iqiyipic.com/image/20250704/40/e6/v_183159476_m_601_374_0.jpg",
    genre: "love story",
    added: 2,
    type: "free",
    country: "China",
    year: "2026",
    synopsis: "The plot follows Shen Yuanzhi, who is forced to marry Fan Xingxu, a man seeking vengeance against her after she takes the blame for her lover's crime.",
    cast: ["Terry Guo", "Fang Jin", "Qiu Hong Kai"],
    episodes: [
      { title: "Episode 1", video: "https://www.youtube.com/embed/OeTA1dwPLKs" }

    ]
  },
{
    id: "hotblooded",
    title: "HOT BLOODED",
    poster: "https://i.ibb.co/MxzB0DLC/Untitled-1.jpg",
    genre: "Action",
    added: 3,
    type: "premium",
    country: "China",
    year: "2026",
    synopsis: "It follows the naive Guo Jing and the clever Huang Rong as they traverse a dangerous jianghu (martial arts world) during the late Song Dynasty, battling invaders and navigating complex personal loyalties.",
    cast: ["Yiwei Zhou", "Meng Ziyi", "Peter Ho"],
    episodes: [
  { title: "Episode 1", video: "https://drive.google.com/file/d/1Irwrf-euIJEtmW5sqdjHWpy2xqdGshOe/preview" },
{ title: "Episode 2", video: "https://drive.google.com/file/d/1LAEU9x8W3AtGx7FL5nPQ8O4uovgzjgdX/preview" },
{ title: "Episode 3", video: "https://drive.google.com/file/d/1SeURoe8lTGnvEcIT152QBARIIEYALIYn/preview" },
{ title: "Episode 4", video: "https://drive.google.com/file/d/1Pcvq3QWDfV2bc4QdG-zyKOESGYAeDllq/preview" },
{ title: "Episode 5", video: "https://drive.google.com/file/d/1CvQSgtE0ceZdlS8inNXO2bIgeu5aWlTz/preview" },
{ title: "Episode 6", video: "https://drive.google.com/file/d/1W10S256gnVrJMAPE33rldU9OkksRfnd-/preview" },
{ title: "Episode 7", video: "https://drive.google.com/file/d/1OYIe8Dfyp2GGtFULt1Ad0PC0WaIq_3-Z/preview" },
{ title: "Episode 8", video: "https://drive.google.com/file/d/1ZZa-MeIn78gEajUBM6f0nfnzFdL28TuN/preview" },
{ title: "Episode 9", video: "https://drive.google.com/file/d/1HaMR1Utz4IdpDffVYQDDFm89mlKAv60T/preview" },
{ title: "Episode 10", video: "https://drive.google.com/file/d/1n17ohs6WeIPB_PpayWPiuA1uhx-orZpy/preview" },
{ title: "Episode 11", video: "https://drive.google.com/file/d/1j3ejskhv6Hz51_OLGVo4ecF5ZCbc1ozT/preview" },
{ title: "Episode 12", video: "https://drive.google.com/file/d/1SOcAooskpIK2538MA9GL7OaEGr2pcGnO/preview" },
{ title: "Episode 13", video: "https://drive.google.com/file/d/1-hbW7mYDo6rQKXnMeupETRjoxrd-9m84/preview" },
{ title: "Episode 14", video: "https://drive.google.com/file/d/1KF72-NDNMw7n5FdyMkNNAkEQ8iNxSDQN/preview" },
{ title: "Episode 15", video: "https://drive.google.com/file/d/1rUrbve1W8Qn4zs1g-2WhvXUxNKCcQP7z/preview" },
{ title: "Episode 16", video: "https://drive.google.com/file/d/1JtNw4CzLBzLTa6AIenyuFgheFZR5mw-P/preview" },
{ title: "Episode 17", video: "https://drive.google.com/file/d/1aBPZ_QnAl-bhBVOVzv0eUKifBbhw7ImT/preview" }
      ]
  },
{
    id: "marimar",
    title: "MARIMAR",
    poster: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/oTw4YlgUEwqIp0zBxeyvNOMhLrn.jpg",
    genre: "drama",
    added: 4,
    type: "premium",
    country: "Pilippine",
    year: "2026",
    synopsis: "Marimar is a naive, poor young woman living in a beach hut with her grandparents. She falls in love with and marries Sergio Santibañez, whose wealthy family, especially his stepmother Angélica, humiliates her and drives them apart. After suffering tragic losses, Marimar transforms into the sophisticated Bella Aldama to seek revenge",
    cast: ["Thalía", "Chantal Andere", "Tito Guízar"],
    episodes: [
   { title: "Episode 1", video: "https://www.youtube.com/embed/NUz_6hcABnY" },
  { title: "Episode 2", video: "https://www.youtube.com/embed/UcfIN1DHfLs" },
  { title: "Episode 3", video: "https://www.youtube.com/embed/UtYFWoU_klw" },
  { title: "Episode 4", video: "https://www.youtube.com/embed/db9D8yUzses" },
  { title: "Episode 5", video: "https://www.youtube.com/embed/9Fd-zbhgOUM" },
  { title: "Episode 6", video: "https://www.youtube.com/embed/KjCCe-YSWrI" },
  { title: "Episode 7", video: "https://www.youtube.com/embed/jzAtePeQkTY" },
  { title: "Episode 8", video: "https://www.youtube.com/embed/28cCahat4qs" },
  { title: "Episode 9", video: "https://www.youtube.com/embed/NpUnrpVbQJU" },
  { title: "Episode 10", video: "https://www.youtube.com/embed/aaQjedH7a24" },
  { title: "Episode 11", video: "https://www.youtube.com/embed/wR4ItNRrtwQ" },
  { title: "Episode 12", video: "https://www.youtube.com/embed/a4EPXOuLcN4" },
  { title: "Episode 13", video: "https://www.youtube.com/embed/R9U18cXOtxI" },
  { title: "Episode 14", video: "https://www.youtube.com/embed/SHcDDozXpzk" },
  { title: "Episode 15", video: "https://www.youtube.com/embed/bcGn9W7Lyvk" },
  { title: "Episode 16", video: "https://www.youtube.com/embed/veDLuzVQjhA" },
  { title: "Episode 17", video: "https://www.youtube.com/embed/ZAFZr39JU7g" },
  { title: "Episode 18", video: "https://www.youtube.com/embed/G8LzjrRLMBc" },
  { title: "Episode 19", video: "https://www.youtube.com/embed/Eun8gufKszw" },
  { title: "Episode 20", video: "https://www.youtube.com/embed/vrgxy7pCkC8" }
      ]
  },
{
    id: "ashur",
    title: "SPARTACUS HOUSE OF ASHUR",
    poster: "https://i.ibb.co/RTD780Ry/MV5-BZWQ1-NDUw-Yj-Et-YTYz-YS00-YTc3-LTgz-OTEt-ZTM0-ZDhh-MGM3-ODAw-Xk-Ey-Xk-Fqc-Gc-V1.jpg",
    genre: "Action",
    added: 5,
    type: "premium",
    country: "USA",
    year: "2026",
    synopsis: "a 2025 Starz miniseries exploring an alternate timeline where the treacherous Ashur (Nick E. Tarabay) survives his death on Mount Vesuvius",
    cast: ["Nick E. Tarabay", "Claudia Black", "India Shaw"],
    episodes: [
   { title: "Episode 1", video: "https://drive.google.com/file/d/1h3ZX-xolsi2sbS3GZc4UqNOhZLBeMMK2/preview" },
  { title: "Episode 2", video: "https://drive.google.com/file/d/1eNw09UOxdxksgrv70rH_0L3JrGx4x34R/preview" },
  { title: "Episode 3", video: "https://drive.google.com/file/d/1trUrYKA1d_42Yz4LpWXSbuTuwcVxT6Z1/preview" },
  { title: "Episode 4", video: "https://drive.google.com/file/d/1ny14W-WqThR0Gkm97V1X7ZCvdhJQ7dbs/preview" },
  { title: "Episode 5", video: "https://drive.google.com/file/d/1eVDBuaemkfDIe34V0vjIPvetrw9AUmgg/preview" },
  { title: "Episode 6", video: "https://drive.google.com/file/d/1eQo-qvWuD6OLeqdaVR7FdTBW9u_QMg6C/preview" },
  { title: "Episode 7", video: "https://drive.google.com/file/d/1MVDAjXAQ1IeG-cj--rXQE9ISDUQc-jxz/preview" }
]
  },
{
    id: "manvsbaby",
    title: "MAN vs BABY",
    poster: "https://www.moviemeter.nl/series/images/cover/33000/33739.jpg?cb=1766010505",
    genre: "Comedy",
    added: 6,
    type: "premium",
    country: "USA",
    year: "2025",
    synopsis: "comedy miniseries starring Rowan Atkinson as Trevor Bingley, a follow-up to the 2022 series Man vs. Bee",
    cast: ["Rowan Atkinson", "Alanah Bloor", "Susannah"],
    episodes: [
   { title: "Episode 1", video: "https://drive.google.com/file/d/1h3ZX-xolsi2sbS3GZc4UqNOhZLBeMMK2/preview" },
  { title: "Episode 2", video: "https://drive.google.com/file/d/1eNw09UOxdxksgrv70rH_0L3JrGx4x34R/preview" },
  { title: "Episode 3", video: "https://drive.google.com/file/d/1trUrYKA1d_42Yz4LpWXSbuTuwcVxT6Z1/preview" },
  { title: "Episode 4", video: "https://drive.google.com/file/d/1ny14W-WqThR0Gkm97V1X7ZCvdhJQ7dbs/preview" },
  { title: "Episode 5", video: "https://drive.google.com/file/d/1eVDBuaemkfDIe34V0vjIPvetrw9AUmgg/preview" },
  { title: "Episode 6", video: "https://drive.google.com/file/d/1eQo-qvWuD6OLeqdaVR7FdTBW9u_QMg6C/preview" },
  { title: "Episode 7", video: "https://drive.google.com/file/d/1MVDAjXAQ1IeG-cj--rXQE9ISDUQc-jxz/preview" }
      ]
  },
{
    id: "sandblades",
    title: "SAND BLADES",
    poster: "https://i.pinimg.com/originals/3c/55/18/3c5518448f60e7449fe2a5da6b63b052.png",
    genre: "Action",
    added: 7,
    type: "premium",
    country: "Chine",
    year: "2025",
    synopsis: "Fu Hong Xue, who leaves the western regions to investigate the murder of his adopted father, the leader of the Divine Knife sect, killed 20 years prior at Plum Nunnery",
    cast: ["Yu Qingbin", "Chai Biyun", "Johnny Zhang"],
    episodes: [
    { title: "Episode 1", video: "https://www.youtube.com/embed/P0ApFqgi_sE" },
  { title: "Episode 2", video: "https://www.youtube.com/embed/yQnwwj6RiAg" },
  { title: "Episode 3", video: "https://www.youtube.com/embed/meP7FLmQ-KM" },
  { title: "Episode 4", video: "https://www.youtube.com/embed/_ekTrZkQo0Q" },
  { title: "Episode 5", video: "https://www.youtube.com/embed/etUcPUb0jRs" },
  { title: "Episode 6", video: "https://www.youtube.com/embed/Tqw9pqINRVw" },
  { title: "Episode 7", video: "https://www.youtube.com/embed/uUmVT76uYt8" },
  { title: "Episode 8", video: "https://www.youtube.com/embed/AR9TPS4ABYo" },
  { title: "Episode 9", video: "https://www.youtube.com/embed/FhskZxbby7k" },
  { title: "Episode 10", video: "https://www.youtube.com/embed/Q2GQN_XHewE" },
  { title: "Episode 11", video: "https://www.youtube.com/embed/ruQHxmkdTMQ" },
  { title: "Episode 12", video: "https://www.youtube.com/embed/NkaOlMiTazc" },
  { title: "Episode 13", video: "https://www.youtube.com/embed/QEFc7S8atyg" },
  { title: "Episode 14", video: "https://www.youtube.com/embed/yAknNqEaL2Q" },
  { title: "Episode 14", video: "https://www.youtube.com/embed/vbZOdVGSIZ8" },
  { title: "Episode 15", video: "https://www.youtube.com/embed/qf1cKU3HZzI" },
  { title: "Episode 16", video: "https://www.youtube.com/embed/zBvoUsB168E" },
  { title: "Episode 17", video: "https://www.youtube.com/embed/MbtVY4DSyXw" },
  { title: "Episode 18", video: "https://www.youtube.com/embed/GEhxbbNf0Vw" },
  { title: "Episode 19", video: "https://www.youtube.com/embed/K4OeZSIKUCg" },
  { title: "Episode 20", video: "https://www.youtube.com/embed/BUZW993-8eM" },
  { title: "Episode 21", video: "https://www.youtube.com/embed/y63d1Ir0Rxs" },
  { title: "Episode 22", video: "https://www.youtube.com/embed/mZCLZYPIFwk" },
  { title: "Episode 23", video: "https://www.youtube.com/embed/SlnV39aezwA" },
  { title: "Episode 24", video: "https://www.youtube.com/embed/AE4-pNj6Y8Q" },
  { title: "Episode 25", video: "https://www.youtube.com/embed/bsM80yLyxPQ" },
  { title: "Episode 26", video: "https://www.youtube.com/embed/pSIrl-ljQF8" },
  { title: "Episode 27", video: "https://www.youtube.com/embed/uKyswP0gRr4" },
  { title: "Episode 28", video: "https://drive.google.com/file/d/1Y75jXtaGuXe-AYhXmO7pgcerHW6zGp8E/preview" },
  { title: "Episode 29", video: "https://www.youtube.com/embed/_qXLItFCJ0o" },
  { title: "Episode 30", video: "https://www.youtube.com/embed/xzQuwhxqjr8" },
  { title: "Episode 31", video: "https://www.youtube.com/embed/PlB1-_tpQyA" },
  { title: "Episode 32", video: "https://www.youtube.com/embed/5ZRqHC3aC3E" },
  { title: "Episode 33", video: "https://www.youtube.com/embed/UwFkvhsX8wg" },
  { title: "Episode 34", video: "https://www.youtube.com/embed/AvRsJvCPTKU" },
  { title: "Episode 35", video: "https://www.youtube.com/embed/EfElemYhxTo" },
  { title: "Episode 36", video: "https://www.youtube.com/embed/LoqdTI8RdIE" },
  { title: "Episode 37", video: "https://www.youtube.com/embed/hS3yGNC8o5c" },
  { title: "Episode 38", video: "https://drive.google.com/file/d/1Fvm9uifxocWXt3al60st6wmt3TM0P3uw/preview" },
  { title: "Episode 39", video: "https://drive.google.com/file/d/1nfqrd3ZYEpouyNXYOmV4CM5ajkFTzQ_-/preview" },
  { title: "Episode 40", video: "https://drive.google.com/file/d/1i3PvXjAEeKkdwtdxSjIt7WaAl0Qw8XPC/preview" },
  { title: "Episode 41", video: "https://drive.google.com/file/d/1e4vhGGHgkNpvSkO5FxIFHfYvZWuC01bY/preview" },
  { title: "Episode 42", video: "https://www.youtube.com/embed/zvsnlXNZ5k0" },
  { title: "Episode 43", video: "https://www.youtube.com/embed/cFT0RrNa3Ic" },
  { title: "Episode 44", video: "https://www.youtube.com/embed/R9cwxQ3h1sI" },
  { title: "Episode 45", video: "https://www.youtube.com/embed/pSdmaPMh4cE" }
      ]
  },
{
    id: "grandmaster",
    title: "GRAND MASTERS",
    poster: "https://img.tvb.com/mytvs/poster/1442/144157_v1_o.jpg",
    genre: "Action",
    added: 8,
    type: "premium",
    country: "Chine",
    year: "2025",
    synopsis: "Chinese wuxia drama focusing on the ultimate martial arts contest to control the Nine Yin True Sutra, featuring iconic masters like Huang Yaoshi and Ouyang Feng",
    cast: ["Ming Dao", "Meng Ziyi", "Gao Weiguang"],
    episodes: [
   { title: "Episode 1", video: "https://drive.google.com/file/d/16GGstLtVVDV-u6xr5L5jb-wtZJzqCHII/preview" },
  { title: "Episode 2", video: "https://drive.google.com/file/d/1xyr96Iz2dR6gzQzC7VYACwJqQQOJXtln/preview" },
  { title: "Episode 3", video: "https://drive.google.com/file/d/10b8NqRlFZIqAj0L3ht5onUnraWHNH21j/preview" },
  { title: "Episode 4", video: "https://drive.google.com/file/d/1tDeFttzZQQfwtJN_nOryUiG337B5iOoT/preview" },
  { title: "Episode 5", video: "https://drive.google.com/file/d/1sAn4JO_8QDT-PguEZpV2YCuf9hUVVyc0/preview" },
  { title: "Episode 6", video: "https://drive.google.com/file/d/1gvS-1jktnkJ1jl1wtu3NL8JMf5xP1vAa/preview" }
      ]
  },
{
    id: "strangelove",
    title: "Strange Love S1",
    poster: "https://img.india-forums.com/images/600x0/137436-still-image-of-arnav-and-khushi.jpg",
    genre: "Drama",
    added: 9,
    type: "premium",
    country: "India",
    year: "2025",
    synopsis: "A ruthless, arrogant, and extremely wealthy business tycoon (known as ASR) who runs AR Designs. He is an atheist, does not believe in love or marriage, and is deeply protective of his sister, Anjali and A simple, spirited, and traditional girl from Lucknow. She is deeply rooted in her values, believes in God and love, and often finds herself in chaotic situations",
    cast: ["Barun Sobti", "Sanaya Irani","Utkarsha Naik","Dalljiet Kaur", "Aabhaas Mehta"],
    episodes: [
  { title: "Episode 1", video: "https://drive.google.com/file/d/1uR00TmaloKKRHgu6ZA1eZIC-JOnjRsAS/preview" },
{ title: "Episode 2", video: "https://drive.google.com/file/d/1H6XjpPT53texj8bsmRORcvMScXqQfUf-/preview" },
{ title: "Episode 3", video: "https://drive.google.com/file/d/1edEoRhKn_g4x9Hu2xkWUNVMEnDtmFqkg/preview" },
{ title: "Episode 4", video: "https://drive.google.com/file/d/1NzbCJuq5HWolFW1xAqNFVNEcvZV8D0oR/preview" },
{ title: "Episode 5", video: "https://drive.google.com/file/d/1kBCUssAxgNGSO2l55EAiWauInv8N0zHi/preview" },
{ title: "Episode 6", video: "https://drive.google.com/file/d/1eo3tKkHU4bBm7yTYwo_mRv5vARUwEDAV/preview" },
{ title: "Episode 7", video: "https://drive.google.com/file/d/19EaQnZS_miwXTelkjWSYAM-4bmtnRkD0/preview" },
{ title: "Episode 8", video: "https://drive.google.com/file/d/1KArFWGdTe0TAssxE1PwseGfWqmWD-uwb/preview" },
{ title: "Episode 9", video: "https://drive.google.com/file/d/1Vn5rE-szSPqiDOR_Hj7uWYU_bTB17m4G/preview" },
{ title: "Episode 10", video: "https://drive.google.com/file/d/1wEkaI0SpcZJ8NxdWfZaunFC81gzgv50I/preview" },
{ title: "Episode 11", video: "https://drive.google.com/file/d/1NzfUL799hYjqaYStt2OyNGxi9ofaQKGY/preview" },
{ title: "Episode 12", video: "https://drive.google.com/file/d/1rr0pA4edLTHMpVFRTDc9Sj3R0OBxGoCT/preview" },
{ title: "Episode 13", video: "https://drive.google.com/file/d/1gCXDejhhJ7wslXXkp-qj5mwaJQ-WHfAy/preview" },
{ title: "Episode 14", video: "https://drive.google.com/file/d/1SfeQMIJFcqVHAwJp1JUN21x2Htt7ZbBD/preview" },
{ title: "Episode 15", video: "https://drive.google.com/file/d/1TFKgEt-_7imCuLgAtBdTJ25KIoXRGlU6/preview" },
{ title: "Episode 16", video: "https://drive.google.com/file/d/1nVLcn2FCMkZCn-7ZuWGKc0vHkW_BlaqV/preview" },
{ title: "Episode 17", video: "https://drive.google.com/file/d/17bgGWXu2TZ1PcjWOwmETE-Iz4xL38PuI/preview" },
{ title: "Episode 18", video: "https://drive.google.com/file/d/1zh9yCz_kE7h-H4MvUrEeYsdTp5s62FbP/preview" },
{ title: "Episode 19", video: "https://drive.google.com/file/d/1ILr5VGQ9-ULmimtJ10Ul0as2eAV-VCjA/preview" },
{ title: "Episode 20", video: "https://drive.google.com/file/d/1kg-QSoeevLEHPjJAKAey_BKmmRfG_AjO/preview" },
{ title: "Episode 21", video: "https://drive.google.com/file/d/12DQuS_SeLH0ibg29GGwPmT5zPmIilh-a/preview" },
{ title: "Episode 22", video: "https://drive.google.com/file/d/1Ehe_Faq-95pb4gh17DmcEnRXK0mVGZbQ/preview" },
{ title: "Episode 23", video: "https://drive.google.com/file/d/1lxF-s7u65kaUT3u3QTand92j6RS6Uv4Q/preview" },
{ title: "Episode 24", video: "https://drive.google.com/file/d/1tlyUkRebCbxcFtZg6whAAkv_ddCtWAom/preview" },
{ title: "Episode 25", video: "https://drive.google.com/file/d/1nRAsFrE1kaWJttn4QC-rRt_ZGmVtQm5T/preview" },
{ title: "Episode 26", video: "https://drive.google.com/file/d/1C5duRTY3ZyNJmlV2hwc6rl-UWjD3QE4v/preview" },
{ title: "Episode 27", video: "https://drive.google.com/file/d/1vQXQpQPoCG9AgA8Ebl8iLZltkw0zeiVo/preview" },
{ title: "Episode 28", video: "https://drive.google.com/file/d/1H9vV38zWkNupRQdbg3UpnwMfNkHEEFvF/preview" },
{ title: "Episode 29", video: "https://drive.google.com/file/d/1L13Yk3SsJv8q1Y0uPKFbxUY-H4nAd97z/preview" },
{ title: "Episode 30", video: "https://drive.google.com/file/d/1PAf38XJcP9DHD52hpWgurrtqlKEb8rak/preview" },
{ title: "Episode 31", video: "https://drive.google.com/file/d/1RBezaNQ0owxV9zcooNYVuwgNTEi6fNYf/preview" },
{ title: "Episode 32", video: "https://drive.google.com/file/d/1nPhk9gmX9rLhvfSO3BaxBq5U1BM1PINf/preview" },
{ title: "Episode 33", video: "https://drive.google.com/file/d/14AcPFS9x3IAXUkLq1x0K4Y-0EhMzklRF/preview" },
{ title: "Episode 34", video: "https://drive.google.com/file/d/1NMB242lypt-zlthhEU37OFDKXbtwb9UZ/preview" },
{ title: "Episode 35", video: "https://drive.google.com/file/d/11QDj_8AXG2lgz03eSwBY53NirpTmVepW/preview" },
{ title: "Episode 36", video: "https://drive.google.com/file/d/1c-xcDo9bW4MOAvA6jvK3SmxFDueZhpLt/preview" },
{ title: "Episode 37", video: "https://drive.google.com/file/d/1c-xcDo9bW4MOAvA6jvK3SmxFDueZhpLt/preview" },
{ title: "Episode 38", video: "https://drive.google.com/file/d/1BEL4-5cYfd0_kmAiJ_CkJ7hsoXDfjbPn/preview" },
{ title: "Episode 39", video: "https://drive.google.com/file/d/1VfFzuLhpydxvyXmzjMVIHD1i1hFBTRX3/preview" },
{ title: "Episode 40", video: "https://drive.google.com/file/d/1tlNRX110GhZhAEYvhZujzIy7XLadjJDs/preview" },
{ title: "Episode 41", video: "https://drive.google.com/file/d/1kAj0h5sUGTJTJVEzhKx4YjOk-3MQ38RJ/preview" },
{ title: "Episode 42", video: "https://drive.google.com/file/d/1M8glTaGX8WwiznNELprchgaLTbC3VlwJ/preview" },
{ title: "Episode 43", video: "https://drive.google.com/file/d/1cjg-ooIQPoQKEhLkdvUi1wqmcfgZ25aY/preview" },
{ title: "Episode 44", video: "https://drive.google.com/file/d/1UI7wkBnsd5PUyK9BJYBByOlK9LLuhQF4/preview" },
{ title: "Episode 45", video: "https://drive.google.com/file/d/1fU6OJ24kkA4iCb0J_w9W-ByqOvAp3Q0N/preview" },
{ title: "Episode 46", video: "https://drive.google.com/file/d/1i_M9uZc2qUcvOnZymabkERdAW6y5n0B2/preview" },
{ title: "Episode 47", video: "https://drive.google.com/file/d/1s6yApFpcHPNBy8Q_KbLCbgDsf0wcixuB/preview" },
{ title: "Episode 48", video: "https://drive.google.com/file/d/14axOR_mbrUhqd1UEUjAVBpFFwuUA1QL0/preview" },
{ title: "Episode 49", video: "https://drive.google.com/file/d/1bXOUtRWsl6YM6f2lYcytR3Hmwl1N9VV9/preview" },
{ title: "Episode 50", video: "https://drive.google.com/file/d/1c4a29Wr_O5Mza2ntJOo9UVcKw_6qZmla/preview" },
{ title: "Episode 51", video: "https://drive.google.com/file/d/1K-Hz_bdCjajWyPENKVlheFBJQ5daIX5w/preview" },
{ title: "Episode 52", video: "https://drive.google.com/file/d/1d-qjGuZPsLx8Flz60GVtnnXrdcU_WzIQ/preview" },
{ title: "Episode 53", video: "https://drive.google.com/file/d/1n4ULCsJ6tBxPRCF80R8zeGh7zv3lDHJg/preview" },
{ title: "Episode 54", video: "https://drive.google.com/file/d/112Bjvbx6PP7MNBlWq6tCthCYEF4FzxLp/preview" },
{ title: "Episode 55", video: "https://drive.google.com/file/d/1OmBXFTd-iZNTFVXWSjoINR9Ynokg0xgl/preview" },
{ title: "Episode 56", video: "https://drive.google.com/file/d/1YNFbsUM7sjoqnrhXg45eXhuFPjJHi2Iq/preview" },
{ title: "Episode 57", video: "https://drive.google.com/file/d/1qiUtJyHM3Axcwo1-GgTqbQp_XlkR50Zr/preview" },
{ title: "Episode 58", video: "https://drive.google.com/file/d/12YdVY92JV2XbmW66vbJ0wuocDZdfRSTA/preview" },
{ title: "Episode 59", video: "https://drive.google.com/file/d/1v8lb9xA7gOtWlCYeDITC7oTyzDSUydkW/preview" },
{ title: "Episode 60", video: "https://drive.google.com/file/d/10VIf3FCs5L2PoqENYcgTIjSDsUppGYFC/preview" },
{ title: "Episode 61", video: "https://drive.google.com/file/d/1jzZ3WJIawXaDyfffRQ0Xm760nRVl79rX/preview" },
{ title: "Episode 62", video: "https://drive.google.com/file/d/1Idr9AcySpRsxgAt0Xl-6MaxxYZV8i8ya/preview" },
{ title: "Episode 63", video: "https://drive.google.com/file/d/1plsuu3JZ0v1q4SNN0WmaKF61tz6Px2bK/preview" },
{ title: "Episode 64", video: "https://drive.google.com/file/d/16efxZfzarK2arGbjklSxZccVDMjPmgtX/preview" },
{ title: "Episode 65", video: "https://drive.google.com/file/d/1jsFb4TtSEL-g308Lq4t87FCmOki_mOhZ/preview" },
{ title: "Episode 66", video: "https://drive.google.com/file/d/15NyiT_gzaxYFcJaIIVtXg7QP2kxb7CK3/preview" },
{ title: "Episode 67", video: "https://drive.google.com/file/d/1A_j3KxbFv97xzhfDc8ZQYRyS8lAyEsTd/preview" },
{ title: "Episode 68", video: "https://drive.google.com/file/d/1tlUa6z6j6JBEzWCNgqWIQNiQ_g-EnH_e/preview" },
{ title: "Episode 69", video: "https://drive.google.com/file/d/1VCRP4KDJ6JvXogx7jvw392OukLsv9iev/view" },
{ title: "Episode 70", video: "https://drive.google.com/file/d/1hu9EQ8N4vLD3UACJ5fflqqrTvGbyWghT/preview" },
{ title: "Episode 71", video: "https://drive.google.com/file/d/11gMBOOzhaPf6Aqn68d5rNTw5BT-Gv_yE/preview" },
{ title: "Episode 72", video: "https://drive.google.com/file/d/1MMpqMIfnu2oyELuRc_zihZyjUoL_Hjo0/preview" },
{ title: "Episode 73", video: "https://drive.google.com/file/d/1kyqo8frP5kGFTDqwwzU8qU31uDnqYbgI/preview" },
{ title: "Episode 74", video: "https://drive.google.com/file/d/1U_12GGjYIYnT6ytKQ4MQecp8qugDjpi_/preview" },
{ title: "Episode 75", video: "https://drive.google.com/file/d/1Bb6NVqtxT5ucHXznN5k4tRUtvOrtXOHH/preview" },
{ title: "Episode 76", video: "https://drive.google.com/file/d/1B5eD0nKqStiFGib7I8ZSFVhmqgIZeioz/preview" },
{ title: "Episode 77", video: "https://drive.google.com/file/d/18z2jY9-Ub9tqhpBiadIOLBgXdd1uBdfq/preview" },
{ title: "Episode 78", video: "https://drive.google.com/file/d/14pyI-BSww29nG8AaYSnQhZ3jfGRxXl2-/preview" },
{ title: "Episode 79", video: "https://drive.google.com/file/d/1McG5LjfrLphHz-Ei-zjgmWrvk0pPbpIe/preview" },
{ title: "Episode 80", video: "https://drive.google.com/file/d/1UJKM7eVD_bC3wYoVzSUmwW24bT-nrCOK/preview" },
{ title: "Episode 81", video: "https://drive.google.com/file/d/1HME1vU7XlkjpQ3T2rQS69DWC8y35q-CC/preview" },
{ title: "Episode 82", video: "https://drive.google.com/file/d/1rhDDPZ7qon6lcLd1ikO9h7IYI8sQWmu_/preview" },
{ title: "Episode 83", video: "https://drive.google.com/file/d/19yNDxGN3FNRgKLqwmB9IYwS77MscSd1p/preview" },
{ title: "Episode 84", video: "https://drive.google.com/file/d/17zR15mmBtkZR3CvmN2NN8drco_x_37N6/preview" },
{ title: "Episode 85", video: "https://drive.google.com/file/d/1qzpY_OnbHBNt927jRE93XO7L_92aRqFg/preview" },
{ title: "Episode 86", video: "https://drive.google.com/file/d/1rvFQqEzIybmjH4m9B3f9BXjvggxeT-fW/preview" },
{ title: "Episode 87", video: "https://drive.google.com/file/d/19ToGUWFiM5W6gCbCXZ7MR_30uwEMirRU/preview" },
{ title: "Episode 88", video: "https://drive.google.com/file/d/1P46_goyMgE-6H0N9PpRaDpc2rJRKY7lm/preview" },
{ title: "Episode 89", video: "https://drive.google.com/file/d/14Npz5FfB6Y8zVlVUgFOJ_dbJybIAwoYx/preview" },
{ title: "Episode 90", video: "https://drive.google.com/file/d/1kgslk6Oc-2SKDXUC5YYNjbVgys3boEzN/view" },
{ title: "Episode 91", video: "https://drive.google.com/file/d/1u_0-MvBb64B3sRQCqIHt9dJE18x3wxwN/preview" },
{ title: "Episode 92", video: "https://drive.google.com/file/d/1Nftg4yyOsITdlzZCdxpxCBR3YiYA3e2L/preview" },
{ title: "Episode 93", video: "https://drive.google.com/file/d/1V7ytpeTcjcLsiaC0_ErFRT9ah5mR4wsW/preview" },
{ title: "Episode 94", video: "https://drive.google.com/file/d/1C7umfTuwCRPenBrSIOKAE0l_S3kklkpn/preview" },
{ title: "Episode 95", video: "https://drive.google.com/file/d/1HS1RZVXWT2QhwzYtskZjPrmyDzNGxj3j/preview" },
{ title: "Episode 96", video: "https://drive.google.com/file/d/18nP5qo9QhJwOrefOnFJbDPf8cJmyKj87/preview" },
{ title: "Episode 97", video: "https://drive.google.com/file/d/1SBjScTtHxMk2YTkNnv9rGtyY3M1FnIVg/preview" },
{ title: "Episode 98", video: "https://drive.google.com/file/d/1ScJPGo6D5APlQimoulgixgBLE06O3tNx/preview" },
{ title: "Episode 99", video: "https://drive.google.com/file/d/1Z6Tc-8lmU3ypip5FMvfJHpVBNSNsWOCV/preview" },
{ title: "Episode 100", video: "https://drive.google.com/file/d/11kEmB0d_bYLQgMJEZIJq5-iWMbVzKmfS/preview" }
      ]
  },
{
    id: "strangelove2",
    title: "Strange Love S2",
    poster: "https://img.wattpad.com/cover/158287218-256-k953330.jpg",
    genre: "Drama",
    added: 10,
    type: "premium",
    country: "India",
    year: "2025",
    synopsis: "A ruthless, arrogant, and extremely wealthy business tycoon (known as ASR) who runs AR Designs. He is an atheist, does not believe in love or marriage, and is deeply protective of his sister, Anjali and A simple, spirited, and traditional girl from Lucknow. She is deeply rooted in her values, believes in God and love, and often finds herself in chaotic situations",
    cast: ["Barun Sobti", "Sanaya Irani","Utkarsha Naik","Dalljiet Kaur", "Aabhaas Mehta"],
    episodes: [
{ title: "Episode 1", video: "https://drive.google.com/file/d/1hBa9X8kVA2ov2VR3iEDnFm4zBYrdJiwo/preview" },
{ title: "Episode 2", video: "https://drive.google.com/file/d/1uaaoXUSlxyt_Qeskl3LqnxXiwESSuBJ_/preview" },
{ title: "Episode 3", video: "https://drive.google.com/file/d/1Jw2khbCqgqk8fu5A3aE2KKXUio4P0Iv5/preview" },
{ title: "Episode 4", video: "https://drive.google.com/file/d/1A_6NtmLIOmqW9WRlg8A1wYBzI3qpIE8W/preview" },
{ title: "Episode 5", video: "https://drive.google.com/file/d/1iJO-R-RtRAzi7AMq59OTifJlX5t5FKy7/preview" },
{ title: "Episode 6", video: "https://drive.google.com/file/d/1cIaND__ayRleDy1KlB1cz3arRqbuBrM2/preview" },
{ title: "Episode 7", video: "https://drive.google.com/file/d/1LRn_hNP5oM-ECQPE5V8Hi_T7bh1zzWKu/preview" },
{ title: "Episode 8", video: "https://drive.google.com/file/d/1_7xwRU0uTRLAq22pQYjGc0XysSw_5JlE/preview" },
{ title: "Episode 9", video: "https://drive.google.com/file/d/1qmxq19Ss31nJArzR8FowecIwp9BZGn3k/preview" },
{ title: "Episode 10", video: "https://drive.google.com/file/d/1Q7jiRf6iLg_EvXWWlLuasxiTpHiGEaCu/preview" },
{ title: "Episode 11", video: "https://drive.google.com/file/d/17NSqMQsjIfGidcI2EPAf4XTVx7XCypAX/preview" },
{ title: "Episode 12", video: "https://drive.google.com/file/d/1LNHnXAyTyF6p0_pno885ye63YpElkKVc/preview" },
{ title: "Episode 13", video: "https://drive.google.com/file/d/1G2ag7nGkF9_MlZbTNQBa6NcnJ-3tsT0I/preview" },
{ title: "Episode 14", video: "https://drive.google.com/file/d/1ngM0e3OFEBKymzMrCvyi5ze9HFMcf5qC/preview" },
{ title: "Episode 15", video: "https://drive.google.com/file/d/17VUQRuH8SruaudMjtliHo9i1WRtoKeBw/preview" },
{ title: "Episode 16", video: "https://drive.google.com/file/d/1iLd6-eAwkR-7HxBulVpdXCHuj7b3YJVG/preview" },
{ title: "Episode 17", video: "https://drive.google.com/file/d/1Zm_Ji_D1wmp7YcmC8tQZNh0z6FpwvRp_/preview" },
{ title: "Episode 18", video: "https://drive.google.com/file/d/1Nt9x6HUy-ytVFof97At5bEycvIVVEbKC/preview" },
{ title: "Episode 19", video: "https://drive.google.com/file/d/1-xtblHWae1X5MICvwGb7nXQFf3UO0YU1/preview" },
{ title: "Episode 20", video: "https://drive.google.com/file/d/1Z2VBgaA_YQjVxbVebvTA7WC94omfEILH/preview" },
{ title: "Episode 21", video: "https://drive.google.com/file/d/1LZtVGkoi9jvNo2fodoRG1MaDtNGpKNzX/preview" },
{ title: "Episode 22", video: "https://drive.google.com/file/d/16UIqJwFHREY1iHL5RfobYuxVfVcFPXIC/preview" },
{ title: "Episode 23", video: "https://drive.google.com/file/d/179hNOMTuhsy-DKpKNnwLu-Pp425l11nV/preview" },
{ title: "Episode 24", video: "https://drive.google.com/file/d/1ThwuHHyGLzRFhW6GDrIQNSQOm5epvIMa/preview" },
{ title: "Episode 25", video: "https://drive.google.com/file/d/175euiF-X9PzSYh1mYX6168PdBGtWZ3or/preview" },
{ title: "Episode 26", video: "https://drive.google.com/file/d/1uYqXPF97Sj6WWWjen5P8x5vOeikeTcO1/preview" },
{ title: "Episode 27", video: "https://drive.google.com/file/d/1QhNztlT4p-ybZVU6weeVRCh9I6O0aLE1/preview" },
{ title: "Episode 28", video: "https://drive.google.com/file/d/1QdEzr4lpumJN2cvJtnLTDiULjOk9aVnH/preview" },
{ title: "Episode 29", video: "https://drive.google.com/file/d/1xaFo4IjOGR9-7NAShmfN8ueAi1RHBapg/preview" },
{ title: "Episode 30", video: "https://drive.google.com/file/d/1YhyIwvidjspSNw8vkMHNVCk1dAvUMin5/preview" },
{ title: "Episode 31", video: "https://drive.google.com/file/d/1YyNWcoWZ-CJWFDAxPAISc5y1HU4H9_k5/preview" },
{ title: "Episode 32", video: "https://drive.google.com/file/d/1a6o6Kq3Yir8WwhLqdGOPC8iyqeUDTo7u/preview" },
{ title: "Episode 33", video: "https://drive.google.com/file/d/1NZKPalSVUunPiHn3h_vBqA488Npn05tZ/preview" },
{ title: "Episode 34", video: "https://drive.google.com/file/d/1z4_ee6-ZfG6FgMZrGZdKwi5-xVY7mQE6/preview" },
{ title: "Episode 35", video: "https://drive.google.com/file/d/1KbK7NcJwk3rufA3attvU2iFxqf6Avjzg/preview" },
{ title: "Episode 36", video: "https://drive.google.com/file/d/1R9r3-EfrsGhbBfLCPkNGuo180aq6BDV-/preview" },
{ title: "Episode 37", video: "https://geo.dailymotion.com/player.html?video=k434jcYAr6bKXPDedLa" },
{ title: "Episode 38", video: "https://geo.dailymotion.com/player.html?video=k6HW7EbNT2R2VRDeini" },
{ title: "Episode 39", video: "https://dai.ly/k2gLMs7bbxzFxbDe74M" },
{ title: "Episode 40", video: "https://geo.dailymotion.com/player.html?video=k5JBIJWTl8Ey9SDe9wU" },
{ title: "Episode 41", video: "https://geo.dailymotion.com/player.html?video=k20anL1HlSSoBxDeFig" },
{ title: "Episode 42", video: "https://geo.dailymotion.com/player.html?video=k5edk3ZObYB3HQDf1yM" },
{ title: "Episode 43", video: "https://geo.dailymotion.com/player.html?video=k60hLQZAOMdDKIDfz9c" },
{ title: "Episode 44", video: "https://drive.google.com/file/d/1GgyxIHN9I5aOwYd0vPtQHIHS7S13GjVL/preview" },
{ title: "Episode 45", video: "https://drive.google.com/file/d/1arcIGaU_PEgLpVe5KhWUnYd_CylaaoHF/preview" },
{ title: "Episode 46", video: "https://geo.dailymotion.com/player.html?video=k32pqUgU0x1tdlDhdoi" },
{ title: "Episode 47", video: "https://geo.dailymotion.com/player.html?video=k5k84mGbdyAW9RDhzg8" },
{ title: "Episode 48", video: "https://drive.google.com/file/d/1WkGWh3u7IqXCXsXMgyQvcL-ykdMJGu5H/preview" },
{ title: "Episode 49", video: "https://drive.google.com/file/d/17nVw2Z7hnaPwXhBK_cAomZUd6GmaMD6S/preview" },
{ title: "Episode 50", video: "https://drive.google.com/file/d/1JVYMKy7X0Em8IV48119hNIWJEzVQ6-6N/preview" },
{ title: "Episode 51", video: "https://drive.google.com/file/d/1JtJ7kGpmKrOPDqjdIa_FwFkr0SenKbIa/preview" },
{ title: "Episode 52", video: "https://drive.google.com/file/d/1aTdLEzbW3UL8J0jnQ8Vgn2sM1otmxESP/preview" },
{ title: "Episode 53", video: "https://drive.google.com/file/d/1zu9z0mm_YiqxiE0cWf8Q4El46pmRVN16/preview" },
{ title: "Episode 54", video: "https://drive.google.com/file/d/18TewjxYuCaA0x3X7MncLVB3p4nAICrDw/preview" },
{ title: "Episode 55", video: "https://drive.google.com/file/d/10sUAsJPtKBK4Uqht4CB0_ezzT8DyNN1R/preview" },
{ title: "Episode 56", video: "https://drive.google.com/file/d/1STBrl9daG0miFP-TpDIB04pil-uo6GKW/preview" },
{ title: "Episode 57", video: "https://drive.google.com/file/d/16jM8NY5x25rwMJ0hRv-o9VEHJkg42BwZ/preview" },
{ title: "Episode 58", video: "https://drive.google.com/file/d/1EEG64Zp_ZnEkl6L6NCNWISLJvJIbm7hI/preview" },
{ title: "Episode 59", video: "https://drive.google.com/file/d/1zmptSAm-FeGCN3t4iCQUaZuWWTX7ug9K/preview" },
{ title: "Episode 60", video: "https://drive.google.com/file/d/1HQoPtEoPXAn7LhhGrHAp0JvVqDiznqMy/preview" },
{ title: "Episode 61", video: "https://drive.google.com/file/d/1OCA8shc7pddTxKcUkLXd8GoMxQLVFwLp/preview" },
{ title: "Episode 62", video: "https://drive.google.com/file/d/15cHzpbxTmK3S1IAG3U26TLdS5YqXEX2p/preview" },
{ title: "Episode 63", video: "https://drive.google.com/file/d/1g4_dZcohynGCOOJtt9YTAkB4Tp0PdtnP/preview" },
{ title: "Episode 64", video: "https://drive.google.com/file/d/12KhA_c1TCaD3_W9wIrpMwuZGaty9X_jA/preview" },
{ title: "Episode 65", video: "https://drive.google.com/file/d/1UwFWfqM0ihH3eS3KY56BOkuYfSi0ihfV/preview" },
{ title: "Episode 66", video: "https://drive.google.com/file/d/1PJivpOVtOQw6-WdkwKcRq88rELSYrlEL/preview" },
{ title: "Episode 67", video: "https://drive.google.com/file/d/1l9_8wKKOrt7W8kChrWfE6NlzOhR8E82p/preview" },
{ title: "Episode 68", video: "https://drive.google.com/file/d/1HbS1Gl3ozAH8bluAhjE74OKnSs-ccl8L/preview" },
{ title: "Episode 69", video: "https://drive.google.com/file/d/1NZr3Ls30kbt5-iwkJXb59qBa3y1SEyuV/preview" },
{ title: "Episode 70", video: "https://drive.google.com/file/d/10KwQvOcbjZxnv1RSjNO2ct7-GME-pUz9/preview" },
{ title: "Episode 71", video: "https://drive.google.com/file/d/193o-xX1KngieRTXe58dNXVC4grl8wtPF/preview" },
{ title: "Episode 72", video: "https://drive.google.com/file/d/1o17sagIjPMCD0Dgd63JoQHt7N52pCQHi/preview" },
{ title: "Episode 73", video: "https://drive.google.com/file/d/1u4sYKePyqDk6unsglhNKgNxXY1-CTrxv/preview" },
{ title: "Episode 74", video: "https://drive.google.com/file/d/1Y6QA6YZ6_Sv3-OktVewnZXH1yVj5pfAS/preview" },
{ title: "Episode 75", video: "https://drive.google.com/file/d/1jc0nYEIo_LVoykS8Ay4uw8MuBmM94Sgo/preview" },
{ title: "Episode 76", video: "https://drive.google.com/file/d/1zoz8mVCKZPRiHj3ali12WsEXKkqjOFqu/view" },
{ title: "Episode 77", video: "https://drive.google.com/file/d/1s52W2u94iUOQ1Tiu1A_cEtbYRtQ3cfq4/preview" },
{ title: "Episode 78", video: "https://drive.google.com/file/d/1EcOLZXFBh3FfbawcwJEHnfmY8xYJ_QLz/preview" },
{ title: "Episode 79", video: "https://drive.google.com/file/d/1AYnU-SHJO5wf289vGzQP6mCmFinHK8QS/preview" },
{ title: "Episode 80", video: "https://drive.google.com/file/d/14EJtmdI08W4V_wCS4_EF6puTwDKgozMP/preview" },
{ title: "Episode 81", video: "https://drive.google.com/file/d/1YUX7yudY9dIgK5VpQR_ZDsvLwPoQdZVr/preview" },
{ title: "Episode 82", video: "https://drive.google.com/file/d/1GiZDnL4i5qjtNz3D8Zkns-rT55POB-Yf/preview" },
{ title: "Episode 83", video: "https://drive.google.com/file/d/1gvEJAbj4cwfbar_cl5OGAqDO9coKwTEr/preview" },
{ title: "Episode 84", video: "https://drive.google.com/file/d/1k0QmfHtt6HEGbe_PPbMCuS0kjsTyUM8e/preview" },
{ title: "Episode 85", video: "https://drive.google.com/file/d/1eLKTBX9RMM4UTfWLt4TfFhYCfdlNEDg_/preview" },
{ title: "Episode 86", video: "https://drive.google.com/file/d/1JmdcjbJd22V84esDVrURIS9FmwZ2zZVC/preview" },
{ title: "Episode 87", video: "https://drive.google.com/file/d/1D2K-sRwIU15j_TQky-XKTEmspWGYKHrZ/preview" },
{ title: "Episode 88", video: "https://drive.google.com/file/d/1mvZySrtYzVdhCSqGuyNGl8K3aspJYIhP/preview" },
{ title: "Episode 89", video: "https://drive.google.com/file/d/18pXleuLxOdbx-YUVpyLwfQz-tvsCkGjw/preview" },
{ title: "Episode 90", video: "https://drive.google.com/file/d/131TLnoPJthYDt2MSjjzJDhpRPjO0BKmo/preview" },
{ title: "Episode 91", video: "https://drive.google.com/file/d/1MxVwEEMf-XNB2JbbcR2QEd34J5r0e3_N/preview" },
{ title: "Episode 92", video: "https://drive.google.com/file/d/1JlbsD69v-I177UdywYmyTr-GGvRMZ868/preview" },
      ]
  },
{
    id: "strangelove3",
    title: "Strange Love S3",
    poster: "https://img.wattpad.com/cover/397751915-256-k182918.jpg",
    genre: "Drama",
    added: 11,
    type: "premium",
    country: "India",
    year: "2026",
    synopsis: "A ruthless, arrogant, and extremely wealthy business tycoon (known as ASR) who runs AR Designs. He is an atheist, does not believe in love or marriage, and is deeply protective of his sister, Anjali and A simple, spirited, and traditional girl from Lucknow. She is deeply rooted in her values, believes in God and love, and often finds herself in chaotic situations",
    cast: ["Barun Sobti", "Sanaya Irani","Utkarsha Naik","Dalljiet Kaur", "Aabhaas Mehta"],
    episodes: [
{ title: "Episode 1", video: "https://drive.google.com/file/d/1UlHzDD7sE96fSH56JOTyM-aDafKqakl1/preview" },
{ title: "Episode 2", video: "https://drive.google.com/file/d/1OJBU4lf4Py7ilcr1r10nDfpa7nvoa_kq/preview" },
{ title: "Episode 3", video: "https://drive.google.com/file/d/1bAX7rurxZmx3xob7yAosz0n68s3k0xRX/preview" },
{ title: "Episode 4", video: "https://drive.google.com/file/d/1GPlysC4A_EuRIt55MxNJmmK1m6Xo061R/preview" },
{ title: "Episode 5", video: "https://drive.google.com/file/d/1FwZQYzs_nI4lkIL24zeyCBfhpFForM5q/preview" },
{ title: "Episode 6", video: "https://drive.google.com/file/d/1vj01ljhTTiv4X1eyzG-EGK6A4I2-P9qy/preview" },
{ title: "Episode 7", video: "https://drive.google.com/file/d/1x-DgBHv6SnQ_e55fYfxn0iXMyJWhUHwS/preview" },
{ title: "Episode 8", video: "https://drive.google.com/file/d/1dgsXQlIkWZpnUpIjXM15f8frACJQaMkN/preview" },
{ title: "Episode 9", video: "https://drive.google.com/file/d/1UDWSF8imMVGqZEufWllEc2F7exLkcdIS/preview" },
{ title: "Episode 10", video: "https://drive.google.com/file/d/1A8RxdvmJ1Eif6hEJVKDDRM-AtBHsoAD5/preview" },
{ title: "Episode 11", video: "https://drive.google.com/file/d/18A2a8OD-CDOJPUg9eQmbEs-R-vDEe_Zs/preview" },
{ title: "Episode 12", video: "https://drive.google.com/file/d/1jtpMxm0_lzoyPv8-7uspdIev3gLj5nt-/preview" },
{ title: "Episode 13", video: "https://drive.google.com/file/d/1wk0n0JTqZykDV3QV33FAHyATJOQGuxpF/preview" },
{ title: "Episode 14", video: "https://drive.google.com/file/d/1jcNbZJnfli9w3lN3hcjGUWqbE_uI_dgd/preview" },
{ title: "Episode 15", video: "https://drive.google.com/file/d/1n60GleLYAZZCaSrrK2MNEiaxirXQiDbJ/preview" },
{ title: "Episode 16", video: "https://drive.google.com/file/d/1gk82PRaQvSu6DLWnuBWS39g47OwqDYgk/preview" },
{ title: "Episode 17", video: "https://drive.google.com/file/d/1009F4iRrlaM_Cfi_TC_Q08LIkWEFcUBg/preview" },
{ title: "Episode 18", video: "https://drive.google.com/file/d/10NfUkpfdAUw6hmNjO34YeZAXkuYcPHCD/preview" },
{ title: "Episode 19", video: "https://drive.google.com/file/d/1gPp4zpdhg-DNKFGn9U3RI32KQ2gaqRk4/preview" },
{ title: "Episode 20", video: "https://drive.google.com/file/d/1PwNovMf0WbrgXP18NdpOqhIiZ-glWyIB/preview" },
{ title: "Episode 21", video: "https://drive.google.com/file/d/1AS3cUR700zoQkDSBj0TPk5jgQnG49j2Y/preview" },
{ title: "Episode 22", video: "https://drive.google.com/file/d/1sPIgfTjocE2vydC1EQuMpwORosB7wCZp/preview" },
{ title: "Episode 23", video: "https://drive.google.com/file/d/1QCAAhQlqF3IquoU6PH-QoHjPiZtYje2w/preview" },
{ title: "Episode 24", video: "https://drive.google.com/file/d/1RqM1T7RR1ZTVSuqvMoWdt1JKU-ZUGjTn/preview" },
{ title: "Episode 25", video: "https://drive.google.com/file/d/10leeuROrWR-THiOmCXvmao5ycS_cEtL-/preview" },
{ title: "Episode 26", video: "https://drive.google.com/file/d/18XrU0VyYiGof1uruvsxYu9uqHDcMccmC/preview" },
{ title: "Episode 27", video: "https://drive.google.com/file/d/18IwQ7HYbNFKC1q_nm2bDzBFdcgA6HCQs/preview" },
{ title: "Episode 28", video: "https://drive.google.com/file/d/12EwuxSvGvmXTZE-sFIVUZS894d5_1D5f/preview" },
{ title: "Episode 29", video: "https://drive.google.com/file/d/1JQJyto6dFOpy-iEsN9eqtcV8QyXn0Pao/preview" },
{ title: "Episode 30", video: "https://drive.google.com/file/d/15umkYaRZNKhvFndg1oyvhs3wmLfnWWme/preview" },
{ title: "Episode 31", video: "https://drive.google.com/file/d/1tCx2tMo0cjnMRKicgDUvCJf76B9Y2wRn/preview" },
{ title: "Episode 32", video: "https://drive.google.com/file/d/1Mgetc363XxJtt8i8Wa8WCV2gxbElifQq/preview" },
{ title: "Episode 33", video: "https://drive.google.com/file/d/1KN1Bc5y3FgyaE8vwYb7-oIcu5ZHEHdNo/preview" },
{ title: "Episode 34", video: "https://drive.google.com/file/d/1Q4XCgthmImJcw_UgyZzcyaDcB2e7rUwe/preview" },
{ title: "Episode 35", video: "https://drive.google.com/file/d/1oNM5hc_wor0k8156S06gN0fXPSiB2ui6/preview" },
{ title: "Episode 36", video: "https://drive.google.com/file/d/1lxvRx-ByU3-6L0jwxlPcTs6v2-SxtWmU/preview" },
{ title: "Episode 37", video: "https://drive.google.com/file/d/1NWnHXQF5SyJPsLZIxN1bhVHKsE7SqpvQ/preview" },
{ title: "Episode 38", video: "https://drive.google.com/file/d/1E8EGapS-lf4CRstVb-unG4pcrHjLy41a/preview" },
{ title: "Episode 39", video: "https://drive.google.com/file/d/1IUEOVoRkZT91P5zSh1y4iq5vyJ4B42l2/preview" },
{ title: "Episode 40", video: "https://drive.google.com/file/d/1yL9hjYM5fX40KMEju9AkWiproBSuw3fU/preview" },
{ title: "Episode 41", video: "https://drive.google.com/file/d/1QT9D1x9ripgpRfstrncPgJ-jLw0gErMn/preview" },
{ title: "Episode 42", video: "https://drive.google.com/file/d/1YsOcEV-Cj5sFnMXbPd2o1l4Ax0H5aVzM/preview" },
{ title: "Episode 43", video: "https://drive.google.com/file/d/1LnDbpoTpI_j0E8PlNMvcH6NJkq-FBDqQ/preview" },
{ title: "Episode 44", video: "https://drive.google.com/file/d/1Ax1QzBFSuJDzn4eSAO-mvf_cqpH194W9/preview" },
{ title: "Episode 45", video: "https://drive.google.com/file/d/15XDpnkN48fIe-NTywUtMUlUGQu1gL5Dj/preview" },
{ title: "Episode 46", video: "https://drive.google.com/file/d/1nBOInz1xqeXx8GgXoBWZ0sC5SrxDdxwk/preview" },
{ title: "Episode 47", video: "https://drive.google.com/file/d/15g_NwYuuxE4ZPkob9bLLg_mYX5M3jvbf/preview" },
{ title: "Episode 48", video: "https://drive.google.com/file/d/1a_vI2ijaynwHygQ5S54Jsu0hBtR_Laf_/preview" },
{ title: "Episode 49", video: "https://drive.google.com/file/d/17WEfWK5-6qJo02S4kG8YaaA_S8W6dHz8/preview" },
{ title: "Episode 50", video: "https://drive.google.com/file/d/1vgnJx-aV-0zDmUpdUb2XxXrXMXpRaQGF/preview" },
{ title: "Episode 51", video: "https://drive.google.com/file/d/1YXJYx03aI3xYlYiiZ20kvRVjMZTo3jWK/preview" },
{ title: "Episode 52", video: "https://drive.google.com/file/d/1H9YfF9MZis7n9zaQ9PY44-KuefI7u2a2/preview" },
{ title: "Episode 53", video: "https://drive.google.com/file/d/1PXDu7sjrR3M6jJTkSw7FnHZGI-MHoDj1/preview" },
{ title: "Episode 54", video: "https://drive.google.com/file/d/16ocQAFBSnfQe7A_Pbkpi_PQoFedUICkP/preview" },
{ title: "Episode 55", video: "https://drive.google.com/file/d/10rkXV4gWoBPPRxsA4rLfHT5H4E609o08/preview" },
{ title: "Episode 56", video: "https://drive.google.com/file/d/1_0jn8oYVtzsYdsU6zE0oKJKpfxoBIZql/preview" },
{ title: "Episode 57", video: "https://drive.google.com/file/d/1feiks_j5OsBmPcsxxApb-22Z8Ym79qFu/preview" },
{ title: "Episode 58", video: "https://drive.google.com/file/d/1-1CYiMS2uQzOtcDNbaMwZJRHgH0_9OFK/preview" },
{ title: "Episode 59", video: "https://drive.google.com/file/d/1N9QJqWFmbYo0oQLYqq5EZ695E2FlseG6/preview" },
{ title: "Episode 60", video: "https://drive.google.com/file/d/1SyDEUjrE5AIaUNoyWBbTNzrUxrEpLmRx/preview" },
{ title: "Episode 61", video: "https://drive.google.com/file/d/17mvtfj6bzRB31hf7Dt2J_Zhvaghl5oDj/preview" },
{ title: "Episode 62", video: "https://drive.google.com/file/d/1Zy7wa_T9-iH1ZjO1BQJny3ugYbhdPWWR/preview" },
{ title: "Episode 63", video: "https://drive.google.com/file/d/1NH9zbmZ4qCvyqi5L2tE-ugIPtnlthxIA/preview" },
{ title: "Episode 64", video: "https://drive.google.com/file/d/16k_Ao19w_QcyHTMuohLcDJnMleMuEEs1/preview" },
{ title: "Episode 65", video: "https://drive.google.com/file/d/16p-2LOzqapPaGAeptsbN-VxCIMaEGwOo/preview" },
{ title: "Episode 66", video: "https://drive.google.com/file/d/1LeJ1KrEMxqbu5Q5NcEa96UY2RMLHSopd/preview" },
{ title: "Episode 67", video: "https://drive.google.com/file/d/1LeVOjnTjbL10jK9uQf6ntbIxdH2psI67/preview" },
{ title: "Episode 68", video: "https://drive.google.com/file/d/1NJHRGrlkjsqMMfvTfxU31yzsphy_YZSJ/preview" },
{ title: "Episode 69", video: "https://drive.google.com/file/d/1OrG9fcTGXhHwCmgaJsbbFBEuGvbcXZyW/preview" },
{ title: "Episode 70", video: "https://drive.google.com/file/d/1PxwdiAeAsHIl3OnNplnhi2aB46-eiUht/preview" },
{ title: "Episode 71", video: "https://drive.google.com/file/d/1DdDaNV3zP0uB-t1pUsToyp0DBww5eF0Z/preview" },
{ title: "Episode 72", video: "https://drive.google.com/file/d/1SbBz2_ovlcmBkAuSKG44lk4U4zyzzFfA/preview" },
{ title: "Episode 73", video: "https://drive.google.com/file/d/1SR_t5m_-Gj5f75skibnVyZuQHrCjANaM/preview" },
{ title: "Episode 74", video: "https://drive.google.com/file/d/1HZsVUjviQF2hoYMQsQBYAAt4FxnwezLd/preview" },
{ title: "Episode 75", video: "https://drive.google.com/file/d/1UaPwc-mLV51B3sCRfOgaLdGMmt3Ij-DN/preview" },
{ title: "Episode 76", video: "https://drive.google.com/file/d/1WqSFzTYevGEk97pmh129rSPeMqbANTX4/preview" },
{ title: "Episode 77", video: "https://drive.google.com/file/d/1YfL1zzbYtpETIfxnIs2uZFiyKipzASpE/preview" },
{ title: "Episode 78 – Strange Love (End)", video: "https://drive.google.com/file/d/1tuf5RilGbn2erz_UUOMh2yUBw9dTCZ0y/preview" }
      ]
  },
{
    id: "secretsofshenje",
    title: "SECRETS OF SHENJIE",
    poster: "https://m.media-amazon.com/images/M/MV5BNzdkOWYzNzQtZjQ4NC00NDEyLTg2NWItNzQxMzAxM2M5ZjhiXkEyXkFqcGc@._V1_.jpg",
    genre: "Action",
    added: 12,
    type: "premium",
    country: "Chine",
    year: "2024",
    synopsis: "Ten years prior, Ling Xuan saved Ying Shi's sister, initiating a pact where Ying Shi would train in the Shadow Pavilion to become her assistant",
    cast: ["Hu Yiyao", "Lin Zehui"],
    episodes: [
{ title: "Episode 1", video: "https://drive.google.com/file/d/1ESWn8KaINs2k8ofWV4yY70uLdnKtLH3I/preview" },
{ title: "Episode 2", video: "https://drive.google.com/file/d/1C0tlRQ4ZB6-0XBZzgarZ-Midcbf5xVkD/preview" },
{ title: "Episode 3", video: "https://drive.google.com/file/d/1RdVKPNJNM8q8yu4ARz_a1gUYKa7T8tIx/preview" },
{ title: "Episode 4", video: "https://drive.google.com/file/d/1ztJTO-C5auHicXCrSphIDNmzgEXfuEMm/preview" },
{ title: "Episode 5", video: "https://drive.google.com/file/d/1XG1xgzeisKfAsICi-7CxK6p5RVhzeqgM/preview" },
{ title: "Episode 6", video: "https://drive.google.com/file/d/1Og616_LGd1uta8nVECZ4YMnsWxw7UOka/preview" },
{ title: "Episode 7", video: "https://drive.google.com/file/d/11cEISKAPl1QZc5TMjLOxk_0BGjH-nZB6/preview" },
{ title: "Episode 8", video: "https://drive.google.com/file/d/1h7JUs2ubl0_QyrzVe9U6yMmOdpaRYcDu/preview" },
{ title: "Episode 9", video: "https://drive.google.com/file/d/1GVNT5ijNVpqOFFMZNGuSvz5mJ51SrBnz/preview" },
{ title: "Episode 10", video: "https://drive.google.com/file/d/1PJWSRPfdxMJEovc8wJd2FiO3Jit3rzXq/preview" },
{ title: "Episode 11", video: "https://drive.google.com/file/d/1PyuZNp0h23Zp39D8Ce-jO84epPBGZvNq/preview" },
{ title: "Episode 12", video: "https://drive.google.com/file/d/1FvLwoSPfnfqd-tKtxEAd29Ez7L8SOota/preview" },
{ title: "Episode 13", video: "https://drive.google.com/file/d/1x3YC7Py1FZxybGqDIu6kSmfdJNPVWcOj/preview" },
{ title: "Episode 14", video: "https://drive.google.com/file/d/1AwaWMbzi8a-RlLhz83Cx9Nl_s7wuiOxb/preview" },
{ title: "Episode 15", video: "https://drive.google.com/file/d/15o_veAk2LRGPBIUMbzswBN6foMw3_To6/preview" },
{ title: "Episode 16", video: "https://drive.google.com/file/d/1o9bZxszVgMWVNn9H2fYaeGafAun4mdA-/preview" },
{ title: "Episode 17", video: "https://drive.google.com/file/d/19CUYAEJ-uchv5Uw-2VJtIaeDTjUc5hhQ/preview" },
{ title: "Episode 18", video: "https://drive.google.com/file/d/17xi1gxVbTk5U70ymiTlfrXz_kAPU_59Y/preview" },
{ title: "Episode 19", video: "https://drive.google.com/file/d/1qoQ4dl5gYP7-s0kDS5ZopypEgoc_uPYE/preview" },
{ title: "Episode 20", video: "https://drive.google.com/file/d/1kAmddYx1BArUurx5p5S_Rtp8VsZCrrpw/preview" },
{ title: "Episode 21", video: "https://drive.google.com/file/d/1v_wygTlZMzZSNgNPWkGm-MSk7dOn5SkQ/preview" },
{ title: "Episode 22", video: "https://drive.google.com/file/d/1vYdIwe0EvM3vorNXBoaX785rfLPn1xKT/preview" },
{ title: "Episode 23", video: "https://drive.google.com/file/d/13HvzVkcXx5A13RUouuNYTr3zZA69RUnf/preview" }
      ]
  },
{
    id: "trplets",
    title: "TRIPLETS",
    poster: "https://i.ibb.co/m5m1BphQ/TRIPLETS.jpg",
    genre: "Drama",
    added: 13,
    type: "premium",
    country: "Philippine",
    year: "2024",
    synopsis: "triplets—Erika, Carrie, and Agatha—separated at birth due to a failed surrogacy agreement",
    cast: ["Ejay Falcon", "Jestoni Alarcon"],
    episodes: [
{ title: "Episode 1", video: "https://drive.google.com/file/d/1oP0mll_WFTKajBXFKtxCa2763rUaAJlm/preview" },
{ title: "Episode 2", video: "https://drive.google.com/file/d/1Jry98QG_9GkSsgHJRJ7DzPZ_Sw6FhrP-/preview" },
{ title: "Episode 3", video: "https://drive.google.com/file/d/1iS2NBNpVCJpD8WSZQuMkTexPtUnQlUvf/preview" },
{ title: "Episode 4", video: "https://drive.google.com/file/d/1HyXFq0L9VrpDdGnz3x5wAG9IIXpoNrJM/preview" },
{ title: "Episode 5", video: "https://drive.google.com/file/d/1HKQLmFXtlEYYAmzGOsSQa-63byrsdGVS/preview" },
{ title: "Episode 6", video: "https://drive.google.com/file/d/1DBT8WesJEJFfn-AR6DR63ZuJJ8FfrkM9/preview" },
{ title: "Episode 7", video: "https://drive.google.com/file/d/1BlpPt-wZ2-xvieKW0V6FWZ1y1sbirRcy/preview" },
{ title: "Episode 8", video: "https://drive.google.com/file/d/1z2hUSoP9-JbE9p6X1lzJ_ar4572UZs8L/preview" },
{ title: "Episode 9", video: "https://drive.google.com/file/d/1hjQ23ahTF670_7HPKmsPcq52ISGHPJf_/preview" },
{ title: "Episode 10", video: "https://drive.google.com/file/d/1thiOZT9QEYpEL_ev1egEAcse5hBVeEQL/preview" },
{ title: "Episode 11", video: "https://drive.google.com/file/d/1W9Hne37yYbP0ftdDz2jMTiwdtrxofvkc/preview" },
{ title: "Episode 12", video: "https://drive.google.com/file/d/1mrPNqtVwjTxe3yk0Z-YNcrMjYBvb8BRl/preview" },
{ title: "Episode 13", video: "https://drive.google.com/file/d/10sPA-dtuasbyAmE21Ihvs-8m4SkqChkd/preview" },
{ title: "Episode 14", video: "https://drive.google.com/file/d/1Q55bTOdhhMKPlHFUabFDPiZgiNvDZuns/preview" },
{ title: "Episode 15", video: "https://drive.google.com/file/d/14Wn8dGMmrAAU6wAlGH_tsmPiX5dn4MN2/preview" },
{ title: "Episode 16", video: "https://drive.google.com/file/d/1vWE0_HuPiA0UbwIrX1qFlhTl2CA0ZaiC/preview" },
{ title: "Episode 17", video: "https://drive.google.com/file/d/1t8DXVbwtnDUcPC6Y_HYBvnGm9KZ7vN1Y/preview" },
{ title: "Episode 18", video: "https://drive.google.com/file/d/1QZvkmtFenhn6kNhG7SRi5SyE1vbRyD12/preview" },
{ title: "Episode 19", video: "https://drive.google.com/file/d/1rVV1CJAM269ttVQFWdm_wCG17iy1lbRE/preview" },
{ title: "Episode 20", video: "https://drive.google.com/file/d/1ErKOU9wkNRSS_VdY0cGNtPJY5UXidUo0/preview" },
{ title: "Episode 21", video: "https://drive.google.com/file/d/173JRTtT1oyJqQSWNbvg4v1W41tfewXOZ/preview" },
{ title: "Episode 22", video: "https://drive.google.com/file/d/1b60gbet7pwcsiC6pjBrHLjJSkSh9Gdpu/preview" },
{ title: "Episode 23", video: "https://drive.google.com/file/d/1JoaEqmCRXMwNHp_0ycNfpNTZBt5CsFiH/preview" },
{ title: "Episode 24", video: "https://drive.google.com/file/d/1G5oT4EUkCquvli9mw1W_A3l-feex0xet/preview" },
{ title: "Episode 25", video: "https://drive.google.com/file/d/1_AAT4ud3_hfQxtp7BYMbDuOPyTumG0pk/preview" },
{ title: "Episode 26", video: "https://drive.google.com/file/d/1Vj8g33Bq4ieEd7niCyX1HlRD9HGDZDws/preview" },
{ title: "Episode 27", video: "https://drive.google.com/file/d/1lsQxTN9glkW9vLeidd-6BayE3ex1mf2f/preview" },
{ title: "Episode 28", video: "https://drive.google.com/file/d/1IlTc2tjVKL1aLZLEeva8vkGp2jmAUeCP/preview" },
{ title: "Episode 29", video: "https://drive.google.com/file/d/18CUT8CbpuF8ZIGVMgHuEJbbjT2pplCga/preview" },
{ title: "Episode 30", video: "https://drive.google.com/file/d/1tAB6McfdOn48eMvS2ONj2k8afNeRXwiv/preview" },
{ title: "Episode 31", video: "https://drive.google.com/file/d/1cIAO1V1vxsU7kGoSqI3jOIWLR-T6Mhk9/preview" },
{ title: "Episode 32", video: "https://drive.google.com/file/d/1aes24owEmhXxajfGxxXTpUqMIM5rHZtm/preview" },
{ title: "Episode 33", video: "https://drive.google.com/file/d/1gVOkDUxM8nkfFb7HzX6g0EDYA4hc9tTX/preview" },
{ title: "Episode 34", video: "https://drive.google.com/file/d/1kKhrsowqXOyd7dYnQDfQa1mVaQNj1FYI/preview" },
{ title: "Episode 35", video: "https://drive.google.com/file/d/1QSsuevPCwRz7nCa9vdwmjWljEVir5Ach/preview" },
{ title: "Episode 36", video: "https://drive.google.com/file/d/1IBCVC6TgRiIkzdESLLZJGD3hYy6g8Tob/preview" },
{ title: "Episode 37", video: "https://drive.google.com/file/d/1vgqYjjqQ5GnrVPKwQad1mhK8YmlXH5t-/preview" },
{ title: "Episode 38", video: "https://drive.google.com/file/d/1yombF4IrRoopycRAobmuBERy2_TDzr1v/preview" },
{ title: "Episode 39", video: "https://drive.google.com/file/d/1yombF4IrRoopycRAobmuBERy2_TDzr1v/preview" },
{ title: "Episode 40", video: "https://drive.google.com/file/d/1b-8XLzB9OzjNVGSuci8nnkU1LAtqe0Pw/preview" },
{ title: "Episode 41", video: "https://drive.google.com/file/d/1UvIa6Kn-MU4tt65QoO4KcUbafLV_IFFQ/preview" },
{ title: "Episode 42", video: "https://drive.google.com/file/d/1NwR2WMiyCe6WgGOSaNIpDaA7i3UG9889/preview" },
{ title: "Episode 43", video: "https://drive.google.com/file/d/1S1sv9RxBIcWr0EcvxytTn5T3ZFIG91Yd/preview" },
{ title: "Episode 44", video: "https://drive.google.com/file/d/1CmmD-PNsT2od3isVe6FXbBABqKV5EEMn/preview" }
      ]
  },
{
    id: "zuchan",
    title: "ZUCHAN",
    poster: "https://artworks.thetvdb.com/banners/v4/series/439306/posters/68d7ceabe12b2.jpg",
    genre: "Fantasy",
    added: 14,
    type: "premium",
    country: "Chine",
    year: "2025",
    synopsis: "a fantasy mystery drama following Xu Qi'an (Dylan Wang), a modern-day police academy graduate who transmigrates into a, dangerous,, magic-filled ancient dynasty",
    cast: ["Dylan Wang","Yue Yang","Tian Xiwei", "Yan Zidong"],
    episodes: [
{ title: "Episode 1", video: "https://www.youtube.com/embed/Joy0bF9ViUM" },
{ title: "Episode 2", video: "https://www.youtube.com/embed/7d3JI5AhPjo" },
{ title: "Episode 3", video: "https://www.youtube.com/embed/iV7gBSD_xnA" },
{ title: "Episode 4", video: "https://www.youtube.com/embed/-YLoFHPSJXQ" },
{ title: "Episode 5", video: "https://www.youtube.com/embed/aRJha6fhx6E" },
{ title: "Episode 6", video: "https://www.youtube.com/embed/NWHqfesJs2E" },
{ title: "Episode 7", video: "https://www.youtube.com/embed/zCs31u-0EQw" },
{ title: "Episode 8", video: "https://www.youtube.com/embed/0nwl0cSugkY" },
{ title: "Episode 9", video: "https://www.youtube.com/embed/X6f5TIX1O7w" },
{ title: "Episode 10", video: "https://www.youtube.com/embed/L_3GClEKS0I" },
{ title: "Episode 11", video: "https://www.youtube.com/embed/rfY3Q_0-sgo" },
{ title: "Episode 12", video: "https://www.youtube.com/embed/BRP70nBHhkk" },
{ title: "Episode 13", video: "https://www.youtube.com/embed/EMzUDBOzldA" },
{ title: "Episode 14", video: "https://www.youtube.com/embed/6FmwJNtT9-w" },
{ title: "Episode 15", video: "https://www.youtube.com/embed/j3k9fq7m0HI" },
{ title: "Episode 16", video: "https://www.youtube.com/embed/-8fbh6uoV6I" },
{ title: "Episode 17", video: "https://www.youtube.com/embed/KRjb2lX1Ctc" },
{ title: "Episode 18", video: "https://www.youtube.com/embed/qUX-w4AfCUo" },
{ title: "Episode 19", video: "https://www.youtube.com/embed/Wdrzbb0V0c8" },
{ title: "Episode 20", video: "https://www.youtube.com/embed/6S880KnQI0M" },
{ title: "Episode 21", video: "https://www.youtube.com/embed/CO4KpblUtas" },
{ title: "Episode 22", video: "https://www.youtube.com/embed/OB4K0yP6Bik" }
      ]
  },
{
    id: "beggerssect",
    title: "BEGGARS SECT",
    poster: "https://i.ibb.co/xqK79Mvc/32-Oa-WHp8ip-Rpc-Ky-C0pl-WKUAn89-T.jpg",
    genre: "Action",
    added: 15,
    type: "premium",
    country: "Chine",
    year: "2025",
    synopsis: "The story focuses on their fast friendship, misunderstandings, and ultimate rivalry caused by a generational feud, leading to the famous Duel on Mount Hua",
    cast: ["Peter Ho","Zhou Yiwei","He Yu", "Luo Qiuyun"],
    episodes: [
{ title: "Episode 1", video: "https://drive.google.com/file/d/156tPthFOQu8-VxtnqdluPFRuUOBfKJAZ/preview" },
{ title: "Episode 2", video: "https://drive.google.com/file/d/1EjOOI38Ig0qW1Cy1Y-9RhjZnKHG05vaT/preview" },
{ title: "Episode 3", video: "https://drive.google.com/file/d/1kXMx7fMv23FNS0bsPO94v8meSw3wzU3f/preview" },
{ title: "Episode 4", video: "https://drive.google.com/file/d/1JpJyf97E3LU3_aqPB53yYdpFHlFjo2dF/preview" },
{ title: "Episode 5", video: "https://drive.google.com/file/d/1NG3ywkW_EyF1qek9q-3gLa0ymzhyrRBM/preview" },
{ title: "Episode 6", video: "https://drive.google.com/file/d/1D0cj8qkTomKEZn53gLJKgS67W3CQ_XHn/preview" },
{ title: "Episode 7", video: "https://drive.google.com/file/d/1oGqFDg3MMVJrHmudA83-bzqVHR8MEpRR/preview" },
{ title: "Episode 8", video: "https://drive.google.com/file/d/1rBVR3BviAn8twD-bWOWYHDJvckjNgVbT/preview" } 
      ]
  },
{
    id: "martialrules",
    title: "MARTIAL RULES",
    poster: "https://i.ibb.co/N2h4DQYm/Untitled-1.jpg",
    genre: "Action",
    added: 16,
    type: "premium",
    country: "Chine",
    year: "2025",
    synopsis: "It explores the untold pasts of the Five Greats, featuring a new generation of heroes, and highlights themes of chivalry, honor, and adventure in a reimagined martial world",
    cast: ["Meng Ziyi","Gao Weiguang","Zhou Yiwei", "Chen Duling"],
    episodes: [
{ title: "Episode 1", video: "https://drive.google.com/file/d/1sPxF6vD_CdvauadLCulfnkLcaKxGhvPI/preview" },
{ title: "Episode 2", video: "https://drive.google.com/file/d/1DPnPnqLc2EuhXEG109_UINXNlkDuMBIS/preview" },
{ title: "Episode 3", video: "https://drive.google.com/file/d/1mZyH627qm28Op0s-elokxiKNcbzL_54x/preview" },
{ title: "Episode 4", video: "https://drive.google.com/file/d/1k5DlDulwc7Rd1afNtwe4urp91O_j9dIL/preview" },
{ title: "Episode 5", video: "https://drive.google.com/file/d/12-RDwtnge6N1zq4n4M3IiW6OTb6bjDSl/preview" },
{ title: "Episode 6", video: "https://drive.google.com/file/d/1o7ZFGT-9VBbWO_Q3Jl7goEKGsotq1Kd7/preview" },
{ title: "Episode 7", video: "https://drive.google.com/file/d/1P4SCMfFFHwy1S-Ia26vFH5Y6zjHscNTP/preview" },
{ title: "Episode 8", video: "https://drive.google.com/file/d/1WuG1fQ8s4Kt0mBaBw1UTx8ZWhl6c_CWC/preview" }
      ]
  },
{
    id: "drfan",
    title: "DR. FAN",
    poster: "https://i.ibb.co/fYRz70H2/Untitled-1-Recovered-Recovered.jpg",
    genre: "Drama",
    added: 17,
    type: "premium",
    country: "Chine",
    year: "2025",
    synopsis: "It follows the eccentric, top forensic pathologist Qin Ming (Zhang Ruoyun), detective Lin Tao (Li Xian), and assistant Li Dabao (Jiao Junyan) as they solve bizarre, gruesome murder cases in Longfan",
    cast: ["Zhang Ruoyun","Li Xian","Jiao Junyan", "Haofeng Cheng"],
    episodes: [
{ title: "Episode 1", video: "https://drive.google.com/file/d/124X8HBUdN4eQ7p9QsoiwgPCccfscFjKv/preview" },
{ title: "Episode 2", video: "https://drive.google.com/file/d/1kL_PPzU8htapdo5DqxG6Yg0CLlGGbSwV/preview" },
{ title: "Episode 3", video: "https://drive.google.com/file/d/1w7mxPRTzItJkQBg_FMX6Wl-0Z5P19Yk1/preview" },
{ title: "Episode 4", video: "https://drive.google.com/file/d/1DkRp-njWuZ2swKcn84w2ui862tkd2L4T/preview" },
{ title: "Episode 5", video: "https://drive.google.com/file/d/1afdCgG7WuzSSBuCYN97agVDCnHE8zNmZ/preview" },
{ title: "Episode 6", video: "https://drive.google.com/file/d/1kpN6ur1wL6d_0a5dzmgFkLhECoy4Lr9u/preview" }
      ]
  },
{
    id: "maid",
    title: "MAID",
    poster: "https://i.ibb.co/ZR7c03GS/787774-maid-2021-0-230-0-345-crop.jpg",
    genre: "Drama",
    added: 18,
    type: "premium",
    country: "USA",
    year: "2025",
    synopsis: "The story follows Alex (Margaret Qualley), a young mother who escapes an emotionally abusive relationship with her toddler, Maddy. To provide for her child, she works as a low-paid house cleaner, facing the systemic hurdles of poverty, homelessness, and the complexities of the welfare system",
    cast: ["Margaret","Andie MacDowell","Nick Robinson", "Raymond Ablack"],
    episodes: [
{ title: "Episode 1", video: "https://drive.google.com/file/d/1FhAWijt5WKPTK08hZbi2G9L9M0KFLrrK/preview" },
{ title: "Episode 2", video: "https://drive.google.com/file/d/1SyP0AuYCJ6k93nVH_W7_eWFqdUztvEjU/preview" },
{ title: "Episode 3", video: "https://drive.google.com/file/d/1BjjShC93bYGXE2nwaPMa71hA9MGU0rPF/preview" },
{ title: "Episode 4", video: "https://drive.google.com/file/d/1Cz9mmq86cX7PTaiwl3bJJMqNNePF-49m/preview" },
{ title: "Episode 5", video: "https://drive.google.com/file/d/1cegafw7SKOoFu5FutQCg1dEuB4G5YEJY/preview" },
{ title: "Episode 6", video: "https://drive.google.com/file/d/1ZC-4cqyZK-tol_ER5cvzZautCTgm_jkE/preview" },
{ title: "Episode 7", video: "https://drive.google.com/file/d/1F6Lu5WNfYmqGpJGMp50APX_r-7sgiG2N/preview" },
{ title: "Episode 8", video: "https://drive.google.com/file/d/1X3tuCHVBIiZxbxMD_hnB3m8kOoH4-EVc/preview" },
{ title: "Episode 9", video: "https://drive.google.com/file/d/14uxRZh_SwXk0x3726cLYDAn7iSykXt7Z/preview" },
{ title: "Episode 10", video: "https://drive.google.com/file/d/1oE53PNvf00Sf2wZhaYw4ydPrX1_58j_y/preview" }
      ]
  },
{
    id: "monks",
    title: "MONKS OF JIANGNAN",
    poster: "https://ik.imagekit.io/aeb9cyo5j/JIANGNAN.jpg?updatedAt=1742994078293",
    genre: "Action",
    added: 19,
    type: "premium",
    country: "Chine",
    year: "2025",
    synopsis: " The series follows the legendary Buddhist monk Ji Gong, who lives in Hangzhou’s Lingyin Temple. Known for his unconventional, crazy behavior, he uses his supernatural powers and wisdom to help the poor and vulnerable, while punishing corrupt officials, greedy individuals, and evil spirits",
    cast: ["Li Hua","Gao Ang","Gu Jia", "Liu Shuo"],
    episodes: [
{ title: "Episode 1", video: "https://www.youtube.com/embed/lSjA6Vb3yag" },
{ title: "Episode 2", video: "https://www.youtube.com/embed/QsyjmEVxp-U" },
{ title: "Episode 3", video: "https://www.youtube.com/embed/MChgMwCw45k" },
{ title: "Episode 4", video: "https://www.youtube.com/embed/qqGuz17hwMk" },
{ title: "Episode 5", video: "https://www.youtube.com/embed/7eqbI9ABNls" },
{ title: "Episode 6", video: "https://www.youtube.com/embed/-zSgAwX08-s" },
{ title: "Episode 7", video: "https://www.youtube.com/embed/8c3raE85cFY" },
{ title: "Episode 8", video: "https://www.youtube.com/embed/hkWDWhFabgA" },
{ title: "Episode 9", video: "https://www.youtube.com/embed/1jPo1kZBw0E" },
{ title: "Episode 10", video: "https://www.youtube.com/embed/PsdEsF65ynA" },
{ title: "Episode 11", video: "https://www.youtube.com/embed/_ar1BoxyLFE" },
{ title: "Episode 12", video: "https://www.youtube.com/embed/DG8sEVbCreg" },
{ title: "Episode 13", video: "https://www.youtube.com/embed/rKJIkHZ-5nI" },
{ title: "Episode 14", video: "https://www.youtube.com/embed/MTqYf8QEdx8" }
      ]
  },
{
    id: "theprince",
    title: "THE PRINCE",
    poster: "https://i.ibb.co/v6K5nS2C/x-the-prince.jpg",
    genre: "Drama",
    added: 20,
    type: "premium",
    country: "Chine",
    year: "2025",
    synopsis: " The show consists of 38 episodes and is based on a novel, with the first season offering a satisfying conclusion while leaving room for further development in planned future seasons",
    cast: ["Zhang Ruoyun","Ding Xiao Ying","Hu Jun", "Gao Weiguang"],
    episodes: [
{ title: "Episode 1", video: "https://player.vimeo.com/video/781156369" },
{ title: "Episode 2", video: "https://drive.google.com/file/d/1e8CTyjSqW14B_-qID4lJgCDUGd_JSFhs/preview" },
  { title: "Episode 3", video: "https://drive.google.com/file/d/155OTzTUGOX7XQiX02s_AxEd5Fl4HldJO/preview" },
  { title: "Episode 4", video: "https://drive.google.com/file/d/1ZEPxNzQtjyvkMWcRltki5h4FvHouqJox/preview" },
  { title: "Episode 5", video: "https://drive.google.com/file/d/1ppq240eY5x4l4jM45WTosD2zrKaOC57h/preview" },
  { title: "Episode 6", video: "https://drive.google.com/file/d/1x24Had_RTlHQ9KGkVJzBUqCCRQWiGOI3/preview" },
  { title: "Episode 7", video: "https://drive.google.com/file/d/1jW0ZutMXaWXBrxqUxEwqJKTLDHxxJ9Xo/preview" },
  { title: "Episode 8", video: "https://drive.google.com/file/d/1tdzOYCmMgTYqgducFALXCa1jhuvq9MlU/preview" },
  { title: "Episode 9", video: "https://drive.google.com/file/d/1Oc47wgSXq7B1ck5Q0A_tHTG1V6YsJkO0/preview" },
       { title: "Episode 10", video: "https://player.vimeo.com/video/786191657" },
  { title: "Episode 11", video: "https://player.vimeo.com/video/787157453" },
  { title: "Episode 12", video: "https://player.vimeo.com/video/787452330" },
  { title: "Episode 13", video: "https://player.vimeo.com/video/787448849" },
  { title: "Episode 14", video: "https://drive.google.com/file/d/1kfrGT6kKmZ_MvNjaaHYIoIuxUr7FEaRT/preview" },
  { title: "Episode 15", video: "https://drive.google.com/file/d/15vG-zbDKkUPN-DA3KRpk4TDQAb1ElU-9/preview-3c" },
  { title: "Episode 16", video: "https://drive.google.com/file/d/1PcEdwriG0Vku7XE2T56XeOC-m34h6R5I/preview" },
  { title: "Episode 17", video: "https://drive.google.com/file/d/1oKREouwq0z88BE2bMtDYFsD4iFagG_Jg/preview" },
  { title: "Episode 18", video: "https://drive.google.com/file/d/1pzmB4YQDvQS-8pvqHIr--gvMQqso_pnG/preview" },
  { title: "Episode 19", video: "https://drive.google.com/file/d/1RQQdLPdYZdff2gO-gD08VeMQU6X3l0BO/preview" },
  { title: "Episode 20", video: "https://drive.google.com/file/d/1YdcBQi75WhfCMUBoS9lFmKz-cueKo-h4/preview" },
  { title: "Episode 21", video: "https://drive.google.com/file/d/1ijxgk3ZkW335qcVKG6ewxm-caeJ0CXgp/preview" },
  { title: "Episode 22", video: "https://drive.google.com/file/d/1dCB-_mJ-7UhE0--SuEXz9UMfTasXp_4D/preview" },
  { title: "Episode 23", video: "https://drive.google.com/file/d/1iaTgLkCVlp7u3c1PpGUaSOxH5nKBscAl/preview" },
  { title: "Episode 24", video: "https://drive.google.com/file/d/1kLFy8U640ja1XxtyCq7tVJZNxxefJKZF/preview" },
  { title: "Episode 25", video: "https://drive.google.com/file/d/1sP_qAmN3uu9yKmny-qM4mIUOcvye3Y2m/preview" },
 { title: "Episode 27", video: "https://player.vimeo.com/video/792864974" },
  { title: "Episode 28", video: "https://player.vimeo.com/video/793258479" },
  { title: "Episode 29", video: "https://player.vimeo.com/video/794408130" },
  { title: "Episode 30", video: "https://player.vimeo.com/video/794631616" },
  { title: "Episode 31", video: "https://player.vimeo.com/video/795204370" },
  { title: "Episode 32", video: "https://player.vimeo.com/video/833951973" },
  { title: "Episode 33", video: "https://player.vimeo.com/video/828917959" },
  { title: "Episode 34", video: "https://drive.google.com/file/d/1TJscajZjLO9UP-sDkIqnE02WgAtfpORp/preview" },
  { title: "Episode 35", video: "https://drive.google.com/file/d/1VuLS4D3t-odeIP-5j4ziRsmv9C7pcjmH/preview" },
  { title: "Episode 36", video: "https://player.vimeo.com/video/822422906" },
  { title: "Episode 37", video: "https://player.vimeo.com/video/822423256" },
  { title: "Episode 38", video: "https://player.vimeo.com/video/873618020" }
      ]
  },
{
    id: "mrcalculator",
    title: "MR CALCULATOR",
    poster: "https://i.ibb.co/PMYYvjW/x-mr-calculator.jpg",
    genre: "Drama",
    added: 21,
    type: "premium",
    country: "Chine",
    year: "2025",
    synopsis: " Shuai Jiamo, a socially awkward, numbers-obsessed genius (often portrayed as an autistic savant), uncovers a massive, long-standing accounting error in the tax records of Jinhua County. Along with his friend Feng Baoyu, he attempts to petition to have the unfair silk tax burden removed. Their pursuit of justice exposes deep-seated corruption, bureaucratic incompetence, and the intense power struggles between local and higher officials. The drama focuses on the struggles of common people against the ruling class, highlighting the economic crises that led to the decline of the Ming Dynasty",
    cast: ["Zhang Ruoyun","Wu Gang","Wang Yang", "Stephy Qi"],
    episodes: [
{ title: "Episode 1", video: "https://player.vimeo.com/video/828918585" },
{ title: "Episode 2", video: "https://player.vimeo.com/video/829300875" },
{ title: "Episode 3", video: "https://player.vimeo.com/video/829717850" },
{ title: "Episode 4", video: "https://player.vimeo.com/video/830470650" },
{ title: "Episode 5", video: "https://player.vimeo.com/video/830471125" },
{ title: "Episode 6", video: "https://player.vimeo.com/video/831159358" },
{ title: "Episode 7", video: "https://player.vimeo.com/video/831159358" },
{ title: "Episode 8", video: "https://player.vimeo.com/video/832178254" },
{ title: "Episode 9", video: "https://player.vimeo.com/video/832547553" },
{ title: "Episode 10", video: "https://player.vimeo.com/video/832558727" },
{ title: "Episode 11", video: "https://player.vimeo.com/video/832856200" },
{ title: "Episode 12", video: "https://player.vimeo.com/video/832856709" },
{ title: "Episode 13", video: "https://player.vimeo.com/video/833075745" },
{ title: "Episode 14", video: "https://player.vimeo.com/video/833242662" }
      ]
  },
{
    id: "mercyfornone",
    title: "MERCY FOR NONE",
    poster: "https://i.ibb.co/RpTNvTng/mercy-for-none.jpg",
    genre: "Drama",
    added: 22,
    type: "premium",
    country: "Korea",
    year: "2025",
    synopsis: " After his younger brother is murdered, Gi-jun breaks his 11-year exile, returning to Seoul's underworld to ruthlessly hunt down those responsible",
    cast: ["So Ji-sub","Cha Seung-won","Ahn Gil-kang", "Lee Jun-hyuk"],
    episodes: [
{ title: "Episode 1", video: "https://drive.google.com/file/d/1BVoJes2Nvk1pftfCKDSFB0nVbIiGJr4F/preview" },
{ title: "Episode 2", video: "https://drive.google.com/file/d/1Mg-T0UWZv0-Mx5wYVfQzvtSdevLTLbhA/preview" },
{ title: "Episode 3", video: "https://drive.google.com/file/d/1LFzZuvgwRLDp9OYkFh4sPsCDQALOKy3h/preview" },
{ title: "Episode 4", video: "https://drive.google.com/file/d/13PajaWn8Eou9VdahscnPwy0ZzAxp-Cyb/preview" },
{ title: "Episode 5", video: "https://drive.google.com/file/d/1jwVVARyz_HYftlHrDOhaw6ruIF3FcFw5/preview" },
{ title: "Episode 6", video: "https://drive.google.com/file/d/156yM6gunR1c1D6RmPIlVgoI_0RHeyj3s/preview" },
{ title: "Episode 7", video: "https://drive.google.com/file/d/1U5z_0HVxrWH9W5krdOoHfOtWVGX-AovM/preview" }

    ]
  }
];
