const SERIES = [
  
  {
    id: "tianlan",
    title: "LEGEND OF TIANLAN",
    poster: "https://horrornews.net/wp-content/uploads/2018/03/Legend-of-the-Naga-Pearls-2017-movie-Yang-Lei-6.jpg",
    genre: "Fantasy",
    added: 1,
    type: "free",
    country: "China",
    year: "2026",
    synopsis: "A legendary journey of power and destiny between exorcists.",
    cast: ["Zifeng Li", "Yang Rong", "Yang Xuwen"],
    episodes: [
      { title: "Episode 1", video: "https://www.youtube.com/embed/RlNqNyrRm_k" },
      { title: "Episode 2", video: "https://www.youtube.com/embed/egF1sy2FPYs" },
      { title: "Episode 3", video: "https://www.youtube.com/embed/UPrxaom2THM" },
      { title: "Episode 4", video: "https://www.youtube.com/embed/squJI3jzkV4" },
      { title: "Episode 5", video: "https://www.youtube.com/embed/LBrZEOj0w5o" },
      { title: "Episode 6", video: "https://www.youtube.com/embed/EjXi1_0BnzE" },
      { title: "Episode 7", video: "https://www.youtube.com/embed/mQAUHdtDbms" },
      { title: "Episode 8", video: "https://www.youtube.com/embed/KdKOBolUC_U" },
      { title: "Episode 9", video: "https://www.youtube.com/embed/fWngGIZ8ZLk" },
      { title: "Episode 10", video: "https://www.youtube.com/embed/D0Op9g37vJs" },
      { title: "Episode 11", video: "https://www.youtube.com/embed/ZKyROMmbIkI" }
]
  },
{
    id: "affairs",
    title: "AFFAIRS",
    poster: "https://pic5.iqiyipic.com/image/20250704/40/e6/v_183159476_m_601_374_0.jpg",
    genre: "love story",
    added: 2,
    type: "free",
    country: "China",
    year: "2026",
    synopsis: "The plot follows Shen Yuanzhi, who is forced to marry Fan Xingxu, a man seeking vengeance against her after she takes the blame for her lover's crime.",
    cast: ["Terry Guo", "Fang Jin", "Qiu Hong Kai"],
    episodes: [
      { title: "Episode 1", video: "https://www.youtube.com/embed/OeTA1dwPLKs" }

    ]
  },
{
    id: "hotblooded",
    title: "HOT BLOODED",
    poster: "https://i.ibb.co/MxzB0DLC/Untitled-1.jpg",
    genre: "Action",
    added: 3,
    type: "premium",
    country: "China",
    year: "2026",
    synopsis: "It follows the naive Guo Jing and the clever Huang Rong as they traverse a dangerous jianghu (martial arts world) during the late Song Dynasty, battling invaders and navigating complex personal loyalties.",
    cast: ["Yiwei Zhou", "Meng Ziyi", "Peter Ho"],
    episodes: [
   { title: "Episode 1", video: "https://www.youtube.com/embed/RlNqNyrRm_k" },
  { title: "Episode 2", video: "https://www.youtube.com/embed/egF1sy2FPYs" },
  { title: "Episode 3", video: "https://www.youtube.com/embed/UPrxaom2THM" },
  { title: "Episode 4", video: "https://www.youtube.com/embed/squJI3jzkV4" },
  { title: "Episode 5", video: "https://www.youtube.com/embed/LBrZEOj0w5o" },
  { title: "Episode 6", video: "https://www.youtube.com/embed/EjXi1_0BnzE" },
  { title: "Episode 7", video: "https://www.youtube.com/embed/mQAUHdtDbms" },
  { title: "Episode 8", video: "https://www.youtube.com/embed/KdKOBolUC_U" },
  { title: "Episode 9", video: "https://www.youtube.com/embed/fWngGIZ8ZLk" },
  { title: "Episode 10", video: "https://www.youtube.com/embed/D0Op9g37vJs" },
  { title: "Episode 11", video: "https://www.youtube.com/embed/ZKyROMmbIkI" }
      ]
  },
{
    id: "marimar",
    title: "MARIMAR",
    poster: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/oTw4YlgUEwqIp0zBxeyvNOMhLrn.jpg",
    genre: "drama",
    added: 4,
    type: "premium",
    country: "Pilippine",
    year: "2026",
    synopsis: "Marimar is a naive, poor young woman living in a beach hut with her grandparents. She falls in love with and marries Sergio Santibañez, whose wealthy family, especially his stepmother Angélica, humiliates her and drives them apart. After suffering tragic losses, Marimar transforms into the sophisticated Bella Aldama to seek revenge",
    cast: ["Thalía", "Chantal Andere", "Tito Guízar"],
    episodes: [
   { title: "Episode 1", video: "https://www.youtube.com/embed/NUz_6hcABnY" },
  { title: "Episode 2", video: "https://www.youtube.com/embed/UcfIN1DHfLs" },
  { title: "Episode 3", video: "https://www.youtube.com/embed/UtYFWoU_klw" },
  { title: "Episode 4", video: "https://www.youtube.com/embed/db9D8yUzses" },
  { title: "Episode 5", video: "https://www.youtube.com/embed/9Fd-zbhgOUM" },
  { title: "Episode 6", video: "https://www.youtube.com/embed/KjCCe-YSWrI" },
  { title: "Episode 7", video: "https://www.youtube.com/embed/jzAtePeQkTY" },
  { title: "Episode 8", video: "https://www.youtube.com/embed/28cCahat4qs" },
  { title: "Episode 9", video: "https://www.youtube.com/embed/NpUnrpVbQJU" },
  { title: "Episode 10", video: "https://www.youtube.com/embed/aaQjedH7a24" },
  { title: "Episode 11", video: "https://www.youtube.com/embed/wR4ItNRrtwQ" },
  { title: "Episode 12", video: "https://www.youtube.com/embed/a4EPXOuLcN4" },
  { title: "Episode 13", video: "https://www.youtube.com/embed/R9U18cXOtxI" },
  { title: "Episode 14", video: "https://www.youtube.com/embed/SHcDDozXpzk" },
  { title: "Episode 15", video: "https://www.youtube.com/embed/bcGn9W7Lyvk" },
  { title: "Episode 16", video: "https://www.youtube.com/embed/veDLuzVQjhA" },
  { title: "Episode 17", video: "https://www.youtube.com/embed/ZAFZr39JU7g" },
  { title: "Episode 18", video: "https://www.youtube.com/embed/G8LzjrRLMBc" },
  { title: "Episode 19", video: "https://www.youtube.com/embed/Eun8gufKszw" },
  { title: "Episode 20", video: "https://www.youtube.com/embed/vrgxy7pCkC8" }
      ]
  },
{
    id: "ashur",
    title: "SPARTACUS HOUSE OF ASHUR",
    poster: "https://i.ibb.co/RTD780Ry/MV5-BZWQ1-NDUw-Yj-Et-YTYz-YS00-YTc3-LTgz-OTEt-ZTM0-ZDhh-MGM3-ODAw-Xk-Ey-Xk-Fqc-Gc-V1.jpg",
    genre: "Action",
    added: 5,
    type: "premium",
    country: "USA",
    year: "2026",
    synopsis: "a 2025 Starz miniseries exploring an alternate timeline where the treacherous Ashur (Nick E. Tarabay) survives his death on Mount Vesuvius",
    cast: ["Nick E. Tarabay", "Claudia Black", "India Shaw"],
    episodes: [
   { title: "Episode 1", video: "https://drive.google.com/file/d/1h3ZX-xolsi2sbS3GZc4UqNOhZLBeMMK2/preview" },
  { title: "Episode 2", video: "https://drive.google.com/file/d/1eNw09UOxdxksgrv70rH_0L3JrGx4x34R/preview" },
  { title: "Episode 3", video: "https://drive.google.com/file/d/1trUrYKA1d_42Yz4LpWXSbuTuwcVxT6Z1/preview" },
  { title: "Episode 4", video: "https://drive.google.com/file/d/1ny14W-WqThR0Gkm97V1X7ZCvdhJQ7dbs/preview" },
  { title: "Episode 5", video: "https://drive.google.com/file/d/1eVDBuaemkfDIe34V0vjIPvetrw9AUmgg/preview" },
  { title: "Episode 6", video: "https://drive.google.com/file/d/1eQo-qvWuD6OLeqdaVR7FdTBW9u_QMg6C/preview" },
  { title: "Episode 7", video: "https://drive.google.com/file/d/1MVDAjXAQ1IeG-cj--rXQE9ISDUQc-jxz/preview" }
]
  },
{
    id: "manvsbaby",
    title: "MAN vs BABY",
    poster: "https://www.moviemeter.nl/series/images/cover/33000/33739.jpg?cb=1766010505",
    genre: "Comedy",
    added: 6,
    type: "premium",
    country: "USA",
    year: "2025",
    synopsis: "comedy miniseries starring Rowan Atkinson as Trevor Bingley, a follow-up to the 2022 series Man vs. Bee",
    cast: ["Rowan Atkinson", "Alanah Bloor", "Susannah"],
    episodes: [
   { title: "Episode 1", video: "https://drive.google.com/file/d/1h3ZX-xolsi2sbS3GZc4UqNOhZLBeMMK2/preview" },
  { title: "Episode 2", video: "https://drive.google.com/file/d/1eNw09UOxdxksgrv70rH_0L3JrGx4x34R/preview" },
  { title: "Episode 3", video: "https://drive.google.com/file/d/1trUrYKA1d_42Yz4LpWXSbuTuwcVxT6Z1/preview" },
  { title: "Episode 4", video: "https://drive.google.com/file/d/1ny14W-WqThR0Gkm97V1X7ZCvdhJQ7dbs/preview" },
  { title: "Episode 5", video: "https://drive.google.com/file/d/1eVDBuaemkfDIe34V0vjIPvetrw9AUmgg/preview" },
  { title: "Episode 6", video: "https://drive.google.com/file/d/1eQo-qvWuD6OLeqdaVR7FdTBW9u_QMg6C/preview" },
  { title: "Episode 7", video: "https://drive.google.com/file/d/1MVDAjXAQ1IeG-cj--rXQE9ISDUQc-jxz/preview" }
      ]
  },
{
    id: "sandblades",
    title: "SAND BLADES",
    poster: "https://i.pinimg.com/originals/3c/55/18/3c5518448f60e7449fe2a5da6b63b052.png",
    genre: "Action",
    added: 7,
    type: "premium",
    country: "Chine",
    year: "2025",
    synopsis: "Fu Hong Xue, who leaves the western regions to investigate the murder of his adopted father, the leader of the Divine Knife sect, killed 20 years prior at Plum Nunnery",
    cast: ["Yu Qingbin", "Chai Biyun", "Johnny Zhang"],
    episodes: [
    { title: "Episode 1", video: "https://www.youtube.com/embed/P0ApFqgi_sE" },
  { title: "Episode 2", video: "https://www.youtube.com/embed/yQnwwj6RiAg" },
  { title: "Episode 3", video: "https://www.youtube.com/embed/meP7FLmQ-KM" },
  { title: "Episode 4", video: "https://www.youtube.com/embed/_ekTrZkQo0Q" },
  { title: "Episode 5", video: "https://www.youtube.com/embed/etUcPUb0jRs" },
  { title: "Episode 6", video: "https://www.youtube.com/embed/Tqw9pqINRVw" },
  { title: "Episode 7", video: "https://www.youtube.com/embed/uUmVT76uYt8" },
  { title: "Episode 8", video: "https://www.youtube.com/embed/AR9TPS4ABYo" },
  { title: "Episode 9", video: "https://www.youtube.com/embed/FhskZxbby7k" },
  { title: "Episode 10", video: "https://www.youtube.com/embed/Q2GQN_XHewE" },
  { title: "Episode 11", video: "https://www.youtube.com/embed/ruQHxmkdTMQ" },
  { title: "Episode 12", video: "https://www.youtube.com/embed/NkaOlMiTazc" },
  { title: "Episode 13", video: "https://www.youtube.com/embed/QEFc7S8atyg" },
  { title: "Episode 14", video: "https://www.youtube.com/embed/yAknNqEaL2Q" },
  { title: "Episode 14", video: "https://www.youtube.com/embed/vbZOdVGSIZ8" },
  { title: "Episode 15", video: "https://www.youtube.com/embed/qf1cKU3HZzI" },
  { title: "Episode 16", video: "https://www.youtube.com/embed/zBvoUsB168E" },
  { title: "Episode 17", video: "https://www.youtube.com/embed/MbtVY4DSyXw" },
  { title: "Episode 18", video: "https://www.youtube.com/embed/GEhxbbNf0Vw" },
  { title: "Episode 19", video: "https://www.youtube.com/embed/K4OeZSIKUCg" },
  { title: "Episode 20", video: "https://www.youtube.com/embed/BUZW993-8eM" },
  { title: "Episode 21", video: "https://www.youtube.com/embed/y63d1Ir0Rxs" },
  { title: "Episode 22", video: "https://www.youtube.com/embed/mZCLZYPIFwk" },
  { title: "Episode 23", video: "https://www.youtube.com/embed/SlnV39aezwA" },
  { title: "Episode 24", video: "https://www.youtube.com/embed/AE4-pNj6Y8Q" },
  { title: "Episode 25", video: "https://www.youtube.com/embed/bsM80yLyxPQ" },
  { title: "Episode 26", video: "https://www.youtube.com/embed/pSIrl-ljQF8" },
  { title: "Episode 27", video: "https://www.youtube.com/embed/uKyswP0gRr4" },
  { title: "Episode 28", video: "https://drive.google.com/file/d/1Y75jXtaGuXe-AYhXmO7pgcerHW6zGp8E/preview" },
  { title: "Episode 29", video: "https://www.youtube.com/embed/_qXLItFCJ0o" },
  { title: "Episode 30", video: "https://www.youtube.com/embed/xzQuwhxqjr8" },
  { title: "Episode 31", video: "https://www.youtube.com/embed/PlB1-_tpQyA" },
  { title: "Episode 32", video: "https://www.youtube.com/embed/5ZRqHC3aC3E" },
  { title: "Episode 33", video: "https://www.youtube.com/embed/UwFkvhsX8wg" },
  { title: "Episode 34", video: "https://www.youtube.com/embed/AvRsJvCPTKU" },
  { title: "Episode 35", video: "https://www.youtube.com/embed/EfElemYhxTo" },
  { title: "Episode 36", video: "https://www.youtube.com/embed/LoqdTI8RdIE" },
  { title: "Episode 37", video: "https://www.youtube.com/embed/hS3yGNC8o5c" },
  { title: "Episode 38", video: "https://drive.google.com/file/d/1Fvm9uifxocWXt3al60st6wmt3TM0P3uw/preview" },
  { title: "Episode 39", video: "https://drive.google.com/file/d/1nfqrd3ZYEpouyNXYOmV4CM5ajkFTzQ_-/preview" },
  { title: "Episode 40", video: "https://drive.google.com/file/d/1i3PvXjAEeKkdwtdxSjIt7WaAl0Qw8XPC/preview" },
  { title: "Episode 41", video: "https://drive.google.com/file/d/1e4vhGGHgkNpvSkO5FxIFHfYvZWuC01bY/preview" },
  { title: "Episode 42", video: "https://www.youtube.com/embed/zvsnlXNZ5k0" },
  { title: "Episode 43", video: "https://www.youtube.com/embed/cFT0RrNa3Ic" },
  { title: "Episode 44", video: "https://www.youtube.com/embed/R9cwxQ3h1sI" },
  { title: "Episode 45", video: "https://www.youtube.com/embed/pSdmaPMh4cE" }
      ]
  },
{
    id: "grandmaster",
    title: "GRAND MASTERS",
    poster: "https://img.tvb.com/mytvs/poster/1442/144157_v1_o.jpg",
    genre: "Action",
    added: 8,
    type: "premium",
    country: "Chine",
    year: "2025",
    synopsis: "Chinese wuxia drama focusing on the ultimate martial arts contest to control the Nine Yin True Sutra, featuring iconic masters like Huang Yaoshi and Ouyang Feng",
    cast: ["Ming Dao", "Meng Ziyi", "Gao Weiguang"],
    episodes: [
   { title: "Episode 1", video: "https://drive.google.com/file/d/16GGstLtVVDV-u6xr5L5jb-wtZJzqCHII/preview" },
  { title: "Episode 2", video: "https://drive.google.com/file/d/1xyr96Iz2dR6gzQzC7VYACwJqQQOJXtln/preview" },
  { title: "Episode 3", video: "https://drive.google.com/file/d/10b8NqRlFZIqAj0L3ht5onUnraWHNH21j/preview" },
  { title: "Episode 4", video: "https://drive.google.com/file/d/1tDeFttzZQQfwtJN_nOryUiG337B5iOoT/preview" },
  { title: "Episode 5", video: "https://drive.google.com/file/d/1sAn4JO_8QDT-PguEZpV2YCuf9hUVVyc0/preview" },
  { title: "Episode 6", video: "https://drive.google.com/file/d/1gvS-1jktnkJ1jl1wtu3NL8JMf5xP1vAa/preview" }
      ]
  },
{
    id: "strangelove",
    title: "Strange Love S1",
    poster: "https://img.india-forums.com/images/600x0/137436-still-image-of-arnav-and-khushi.jpg",
    genre: "Drama",
    added: 9,
    type: "premium",
    country: "India",
    year: "2025",
    synopsis: "A ruthless, arrogant, and extremely wealthy business tycoon (known as ASR) who runs AR Designs. He is an atheist, does not believe in love or marriage, and is deeply protective of his sister, Anjali and A simple, spirited, and traditional girl from Lucknow. She is deeply rooted in her values, believes in God and love, and often finds herself in chaotic situations",
    cast: ["Barun Sobti", "Sanaya Irani","Utkarsha Naik","Dalljiet Kaur", "Aabhaas Mehta"],
    episodes: [
   { title: "Episode 1", video: "https://drive.google.com/file/d/1hBa9X8kVA2ov2VR3iEDnFm4zBYrdJiwo/preview" },
  { title: "Episode 2", video: "https://drive.google.com/file/d/1uaaoXUSlxyt_Qeskl3LqnxXiwESSuBJ_/preview" },
  { title: "Episode 3", video: "https://drive.google.com/file/d/1Jw2khbCqgqk8fu5A3aE2KKXUio4P0Iv5/preview" },
  { title: "Episode 4", video: "https://drive.google.com/file/d/1A_6NtmLIOmqW9WRlg8A1wYBzI3qpIE8W/preview" },
  { title: "Episode 5", video: "https://drive.google.com/file/d/1iJO-R-RtRAzi7AMq59OTifJlX5t5FKy7/preview" },
  { title: "Episode 6", video: "https://drive.google.com/file/d/1cIaND__ayRleDy1KlB1cz3arRqbuBrM2/preview" },
  { title: "Episode 7", video: "https://drive.google.com/file/d/1LRn_hNP5oM-ECQPE5V8Hi_T7bh1zzWKu/preview" },
  { title: "Episode 8", video: "https://drive.google.com/file/d/1_7xwRU0uTRLAq22pQYjGc0XysSw_5JlE/preview" },
  { title: "Episode 9", video: "https://drive.google.com/file/d/1qmxq19Ss31nJArzR8FowecIwp9BZGn3k/preview" },
  { title: "Episode 10", video: "https://drive.google.com/file/d/1Q7jiRf6iLg_EvXWWlLuasxiTpHiGEaCu/preview" },
  { title: "Episode 11", video: "https://drive.google.com/file/d/17NSqMQsjIfGidcI2EPAf4XTVx7XCypAX/preview" },
{ title: "Episode 12", video: "https://drive.google.com/file/d/1LNHnXAyTyF6p0_pno885ye63YpElkKVc/preview" },
{ title: "Episode 13", video: "https://drive.google.com/file/d/1G2ag7nGkF9_MlZbTNQBa6NcnJ-3tsT0I/preview" },
{ title: "Episode 14", video: "https://drive.google.com/file/d/1ngM0e3OFEBKymzMrCvyi5ze9HFMcf5qC/preview" },
{ title: "Episode 15", video: "https://drive.google.com/file/d/17VUQRuH8SruaudMjtliHo9i1WRtoKeBw/preview" },
{ title: "Episode 16", video: "https://drive.google.com/file/d/1iLd6-eAwkR-7HxBulVpdXCHuj7b3YJVG/preview" },
{ title: "Episode 17", video: "https://drive.google.com/file/d/1Zm_Ji_D1wmp7YcmC8tQZNh0z6FpwvRp_/preview" },
{ title: "Episode 18", video: "https://drive.google.com/file/d/1Nt9x6HUy-ytVFof97At5bEycvIVVEbKC/preview" },
{ title: "Episode 19", video: "https://drive.google.com/file/d/1-xtblHWae1X5MICvwGb7nXQFf3UO0YU1/preview" },
{ title: "Episode 20", video: "https://drive.google.com/file/d/1Z2VBgaA_YQjVxbVebvTA7WC94omfEILH/preview" },
{ title: "Episode 21", video: "https://drive.google.com/file/d/1LZtVGkoi9jvNo2fodoRG1MaDtNGpKNzX/preview" },
{ title: "Episode 22", video: "https://drive.google.com/file/d/16UIqJwFHREY1iHL5RfobYuxVfVcFPXIC/preview" },
{ title: "Episode 23", video: "https://drive.google.com/file/d/179hNOMTuhsy-DKpKNnwLu-Pp425l11nV/preview" },
{ title: "Episode 24", video: "https://drive.google.com/file/d/1ThwuHHyGLzRFhW6GDrIQNSQOm5epvIMa/preview" },
{ title: "Episode 25", video: "https://drive.google.com/file/d/175euiF-X9PzSYh1mYX6168PdBGtWZ3or/preview" },
{ title: "Episode 26", video: "https://drive.google.com/file/d/1uYqXPF97Sj6WWWjen5P8x5vOeikeTcO1/preview" },
{ title: "Episode 27", video: "https://drive.google.com/file/d/1QhNztlT4p-ybZVU6weeVRCh9I6O0aLE1/preview" },
{ title: "Episode 28", video: "https://drive.google.com/file/d/1QdEzr4lpumJN2cvJtnLTDiULjOk9aVnH/preview" },
{ title: "Episode 29", video: "https://drive.google.com/file/d/1xaFo4IjOGR9-7NAShmfN8ueAi1RHBapg/preview" },
{ title: "Episode 30", video: "https://drive.google.com/file/d/1YhyIwvidjspSNw8vkMHNVCk1dAvUMin5/preview" },
{ title: "Episode 31", video: "https://drive.google.com/file/d/1YyNWcoWZ-CJWFDAxPAISc5y1HU4H9_k5/preview" },
{ title: "Episode 32", video: "https://drive.google.com/file/d/1a6o6Kq3Yir8WwhLqdGOPC8iyqeUDTo7u/preview" },
{ title: "Episode 33", video: "https://drive.google.com/file/d/1NZKPalSVUunPiHn3h_vBqA488Npn05tZ/preview" },
{ title: "Episode 34", video: "https://drive.google.com/file/d/1z4_ee6-ZfG6FgMZrGZdKwi5-xVY7mQE6/preview" },
{ title: "Episode 35", video: "https://drive.google.com/file/d/1KbK7NcJwk3rufA3attvU2iFxqf6Avjzg/preview" },
{ title: "Episode 36", video: "https://drive.google.com/file/d/1R9r3-EfrsGhbBfLCPkNGuo180aq6BDV-/preview" },
{ title: "Episode 37", video: "https://geo.dailymotion.com/player.html?video=k434jcYAr6bKXPDedLa" },
{ title: "Episode 38", video: "https://geo.dailymotion.com/player.html?video=k6HW7EbNT2R2VRDeini" },
{ title: "Episode 39", video: "https://dai.ly/k2gLMs7bbxzFxbDe74M" },
{ title: "Episode 40", video: "https://geo.dailymotion.com/player.html?video=k5JBIJWTl8Ey9SDe9wU" },
{ title: "Episode 41", video: "https://geo.dailymotion.com/player.html?video=k20anL1HlSSoBxDeFig" },
{ title: "Episode 42", video: "https://geo.dailymotion.com/player.html?video=k5edk3ZObYB3HQDf1yM" },
{ title: "Episode 43", video: "https://geo.dailymotion.com/player.html?video=k60hLQZAOMdDKIDfz9c" }
    ]
  }
];
